//! LuaLS `.d.lua` generation from a live [`LuaRuntime`] (VM hardening pillar 5).
//!
//! Engine classes, native userdata methods, constants, and free functions are
//! enumerated from the shipped VM so the stubs cannot rot the way a hand-maintained
//! Gap 3 inventory did. Lua-defined methods (`Tile.relocateTo` in
//! `data/lib/core/tile.lua`) stay in the data pack — LuaLS infers them from the
//! workspace.
//!
//! See `tasks/tools-actions/vm-hardening.md` pillar 5.

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use mlua::{Lua, Table, Value};

use crate::class_registry::{
    class_lua_base, registered_class_entries, registered_field_entries, registered_method_entries,
};
use crate::context::{CreatureRef, ItemRef};
use crate::npc_type::NpcTypeBuilder;
use crate::runtime::LuaRuntime;
use crate::userdata::combat::{CombatDef, CombatRef};
use crate::userdata::condition::ConditionBuilder;
use crate::userdata::container::ContainerRef;
use crate::userdata::group::GroupRef;
use crate::userdata::item_type::ItemTypeRef;
use crate::userdata::monster_type::MonsterTypeRef;
use crate::userdata::npc::NpcRef;
use crate::userdata::position::PositionRef;
use crate::userdata::spell::{PendingSpell, SpellBuilder};
use crate::userdata::tile::{HouseRef, TileRef};
use crate::userdata::town::TownRef;
use crate::userdata::vocation::VocationRef;
use crate::userdata::weapon::{PendingWeapon, WeaponBuilder};
use std::cell::RefCell;
use std::collections::HashMap;
use std::rc::Rc;
use tfs_rust_content::npcs::PendingNpcDefinition;

const GENERATED_BANNER: &str = "\
---@meta
-- Generated by `cargo run -p tfs-rust-lua --bin emit-lua-defs`. Do not edit.
-- VM hardening pillar 5 — tasks/tools-actions/vm-hardening.md
";

const STDLIB_NAMES: &[&str] = &[
    "_G",
    "_VERSION",
    "arg",
    "assert",
    "bit",
    "bit32",
    "collectgarbage",
    "coroutine",
    "debug",
    "dofile",
    "error",
    "gcinfo",
    "getfenv",
    "getmetatable",
    "io",
    "ipairs",
    "jit",
    "load",
    "loadfile",
    "loadstring",
    "math",
    "module",
    "newproxy",
    "next",
    "os",
    "package",
    "pairs",
    "pcall",
    "print",
    "rawequal",
    "rawget",
    "rawset",
    "require",
    "select",
    "setfenv",
    "setmetatable",
    "string",
    "table",
    "tonumber",
    "tostring",
    "type",
    "unpack",
    "utf8",
    "xpcall",
];

const CTOR_PROBES: &[(&str, &str)] = &[
    ("Action", "return Action()"),
    ("TalkAction", "return TalkAction('x')"),
    ("Channel", "return Channel(1, 'n')"),
    ("MoveEvent", "return MoveEvent()"),
    ("CreatureEvent", "return CreatureEvent('x')"),
    ("GlobalEvent", "return GlobalEvent('x')"),
    ("Spell", "return Spell(SPELL_INSTANT)"),
    ("Weapon", "return Weapon(WEAPON_SWORD)"),
    ("Condition", "return Condition(0)"),
    ("Variant", "return Variant('x')"),
];

/// Snapshot of the engine Lua surface for LuaLS stubs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LuaDefsSnapshot {
    pub classes: BTreeMap<String, ClassDef>,
    pub constants: BTreeMap<String, ConstantValue>,
    pub nested_tables: BTreeMap<String, BTreeMap<String, ConstantValue>>,
    pub functions: BTreeSet<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ClassDef {
    pub base: Option<String>,
    pub callable: bool,
    /// Userdata / ctor-instance methods (`obj:method()`).
    pub methods: BTreeSet<String>,
    /// Functions on the class table (`Game.createItem(...)`, no implicit self).
    pub table_functions: BTreeSet<String>,
    pub fields: BTreeSet<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ConstantValue {
    Integer(i64),
    Boolean(bool),
    String(String),
}

/// Three generated `.d.lua` files.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EmittedLuaDefs {
    pub engine: String,
    pub constants: String,
    pub globals: String,
}

/// Boot-time inventory of the engine Lua surface (no data-pack lib load).
///
/// # Errors
///
/// Returns `mlua::Error` if dummy userdata creation or table walks fail.
pub fn snapshot_lua_defs(runtime: &LuaRuntime) -> Result<LuaDefsSnapshot, mlua::Error> {
    let lua = &runtime.lua;
    populate_native_members(lua)?;

    let mut classes: BTreeMap<String, ClassDef> = BTreeMap::new();
    for (name, callable) in registered_class_entries(lua)? {
        classes.insert(
            name.clone(),
            ClassDef {
                base: class_lua_base(&name).map(str::to_string),
                callable,
                methods: BTreeSet::new(),
                table_functions: BTreeSet::new(),
                fields: BTreeSet::new(),
            },
        );
    }

    for (class, methods) in registered_method_entries(lua)? {
        let entry = classes.entry(class).or_insert_with(|| ClassDef {
            base: None,
            callable: false,
            methods: BTreeSet::new(),
            table_functions: BTreeSet::new(),
            fields: BTreeSet::new(),
        });
        entry.methods.extend(methods);
    }
    for (class, fields) in registered_field_entries(lua)? {
        let entry = classes.entry(class).or_insert_with(|| ClassDef {
            base: None,
            callable: false,
            methods: BTreeSet::new(),
            table_functions: BTreeSet::new(),
            fields: BTreeSet::new(),
        });
        entry.fields.extend(fields);
    }

    let class_names: BTreeSet<String> = classes.keys().cloned().collect();
    let globals = lua.globals();
    for name in &class_names {
        if let Ok(table) = globals.get::<Table>(name.as_str()) {
            collect_function_keys(
                &table,
                &mut classes.get_mut(name).expect("class").table_functions,
            )?;
        }
    }

    for (class, chunk) in CTOR_PROBES {
        if let Ok(Value::Table(table)) = lua.load(*chunk).set_name(*class).eval::<Value>() {
            let entry = classes
                .entry((*class).to_string())
                .or_insert_with(|| ClassDef {
                    base: None,
                    callable: true,
                    methods: BTreeSet::new(),
                    table_functions: BTreeSet::new(),
                    fields: BTreeSet::new(),
                });
            collect_function_keys(&table, &mut entry.methods)?;
        }
    }

    let mut constants = BTreeMap::new();
    let mut nested_tables = BTreeMap::new();
    let mut functions = BTreeSet::new();
    for pair in globals.pairs::<Value, Value>() {
        let (key, value) = pair?;
        let Some(name) = value_string_key(&key) else {
            continue;
        };
        if name.starts_with('_') || is_stdlib(&name) || class_names.contains(&name) {
            continue;
        }
        match value {
            Value::Integer(n) if is_constant_name(&name) => {
                constants.insert(name, ConstantValue::Integer(n));
            }
            Value::Number(n) if is_constant_name(&name) && n.fract() == 0.0 => {
                constants.insert(name, ConstantValue::Integer(n as i64));
            }
            Value::Boolean(b) if is_constant_name(&name) => {
                constants.insert(name, ConstantValue::Boolean(b));
            }
            Value::String(s) if is_constant_name(&name) => {
                constants.insert(name, ConstantValue::String(s.to_str()?.to_string()));
            }
            Value::Function(_) if is_identifier(&name) => {
                functions.insert(name);
            }
            Value::Table(t) if name == "configKeys" || looks_like_enum_table(&t)? => {
                let mut inner = BTreeMap::new();
                collect_constant_table(&t, &mut inner)?;
                if !inner.is_empty() {
                    nested_tables.insert(name, inner);
                }
            }
            Value::Table(t) if is_identifier(&name) => {
                let mut methods = BTreeSet::new();
                collect_function_keys(&t, &mut methods)?;
                if !methods.is_empty() {
                    classes.entry(name).or_insert_with(|| ClassDef {
                        base: None,
                        callable: false,
                        methods: BTreeSet::new(),
                        table_functions: methods,
                        fields: BTreeSet::new(),
                    });
                }
            }
            _ => {}
        }
    }

    Ok(LuaDefsSnapshot {
        classes,
        constants,
        nested_tables,
        functions,
    })
}

/// Render the three `.d.lua` files from a snapshot.
pub fn emit_lua_defs(snapshot: &LuaDefsSnapshot) -> EmittedLuaDefs {
    EmittedLuaDefs {
        engine: emit_engine(snapshot),
        constants: emit_constants(snapshot),
        globals: emit_globals(snapshot),
    }
}

/// Write `engine.d.lua` / `constants.d.lua` / `globals.d.lua` under `dir`.
///
/// # Errors
///
/// Returns IO errors from directory/file creation.
pub fn write_lua_defs(dir: &Path, snapshot: &LuaDefsSnapshot) -> std::io::Result<()> {
    std::fs::create_dir_all(dir)?;
    let emitted = emit_lua_defs(snapshot);
    std::fs::write(dir.join("engine.d.lua"), emitted.engine)?;
    std::fs::write(dir.join("constants.d.lua"), emitted.constants)?;
    std::fs::write(dir.join("globals.d.lua"), emitted.globals)?;
    Ok(())
}

/// Compare committed files under `dir` against a freshly emitted snapshot.
///
/// # Errors
///
/// Returns a human-readable mismatch or IO error string.
pub fn check_lua_defs(dir: &Path, snapshot: &LuaDefsSnapshot) -> Result<(), String> {
    let emitted = emit_lua_defs(snapshot);
    check_file(dir, "engine.d.lua", &emitted.engine)?;
    check_file(dir, "constants.d.lua", &emitted.constants)?;
    check_file(dir, "globals.d.lua", &emitted.globals)?;
    Ok(())
}

fn check_file(dir: &Path, name: &str, expected: &str) -> Result<(), String> {
    let path = dir.join(name);
    let actual = std::fs::read_to_string(&path).map_err(|e| {
        format!(
            "{}: {e} (run `cargo run -p tfs-rust-lua --bin emit-lua-defs`)",
            path.display()
        )
    })?;
    if actual != expected {
        return Err(format!(
            "{} is stale — run `cargo run -p tfs-rust-lua --bin emit-lua-defs`",
            path.display()
        ));
    }
    Ok(())
}

fn populate_native_members(lua: &Lua) -> Result<(), mlua::Error> {
    let _ = lua.create_userdata(TileRef { x: 0, y: 0, z: 0 })?;
    let _ = lua.create_userdata(HouseRef(0))?;
    let _ = lua.create_userdata(TownRef(0))?;
    let _ = lua.create_userdata(ItemRef(0))?;
    let _ = lua.create_userdata(CreatureRef(0))?;
    let _ = lua.create_userdata(ContainerRef(0))?;
    let _ = lua.create_userdata(PositionRef { x: 0, y: 0, z: 0 })?;
    let _ = lua.create_userdata(ItemTypeRef(0))?;
    let _ = lua.create_userdata(VocationRef(0))?;
    let _ = lua.create_userdata(GroupRef(0))?;
    let _ = lua.create_userdata(NpcRef(0))?;
    let _ = lua.create_userdata(CombatRef(Rc::new(RefCell::new(CombatDef::default()))))?;
    let _ = lua.create_userdata(ConditionBuilder::new(0, 0))?;
    let _ = lua.create_userdata(SpellBuilder {
        spell: Rc::new(RefCell::new(PendingSpell::new(1))),
        on_cast_fn: Rc::new(RefCell::new(None)),
    })?;
    let _ = lua.create_userdata(WeaponBuilder {
        weapon: Rc::new(RefCell::new(PendingWeapon::new(1))),
        on_use_fn: Rc::new(RefCell::new(None)),
    })?;
    let _ = lua.create_userdata(MonsterTypeRef {
        name: String::new(),
    })?;
    let _ = lua.create_userdata(NpcTypeBuilder {
        pending: Rc::new(RefCell::new(crate::npc_type::PendingNpc {
            def: PendingNpcDefinition {
                name: "LuaDefs".into(),
                source_file: "<lua-defs>".into(),
                health_max: 100,
                ..Default::default()
            },
        })),
        action_fns: Rc::new(RefCell::new(HashMap::new())),
        predicate_fns: Rc::new(RefCell::new(HashMap::new())),
        lifecycle_fns: Rc::new(RefCell::new(HashMap::new())),
    })?;
    Ok(())
}

fn collect_function_keys(table: &Table, into: &mut BTreeSet<String>) -> Result<(), mlua::Error> {
    for pair in table.pairs::<Value, Value>() {
        let (key, value) = pair?;
        if !matches!(value, Value::Function(_)) {
            continue;
        }
        let Some(name) = value_string_key(&key) else {
            continue;
        };
        if name.starts_with('_') {
            continue;
        }
        into.insert(name);
    }
    Ok(())
}

fn collect_constant_table(
    table: &Table,
    into: &mut BTreeMap<String, ConstantValue>,
) -> Result<(), mlua::Error> {
    for pair in table.pairs::<Value, Value>() {
        let (key, value) = pair?;
        let Some(name) = value_string_key(&key) else {
            continue;
        };
        match value {
            Value::Integer(n) => {
                into.insert(name, ConstantValue::Integer(n));
            }
            Value::Number(n) if n.fract() == 0.0 => {
                into.insert(name, ConstantValue::Integer(n as i64));
            }
            Value::Boolean(b) => {
                into.insert(name, ConstantValue::Boolean(b));
            }
            _ => {}
        }
    }
    Ok(())
}

fn looks_like_enum_table(table: &Table) -> Result<bool, mlua::Error> {
    let mut any = false;
    for pair in table.pairs::<Value, Value>() {
        let (key, value) = pair?;
        if value_string_key(&key).is_none() {
            return Ok(false);
        }
        match value {
            Value::Integer(_) | Value::Boolean(_) => any = true,
            Value::Number(n) if n.fract() == 0.0 => any = true,
            _ => return Ok(false),
        }
    }
    Ok(any)
}

fn value_string_key(key: &Value) -> Option<String> {
    match key {
        Value::String(s) => s.to_str().ok().map(|s| s.to_string()),
        _ => None,
    }
}

fn is_stdlib(name: &str) -> bool {
    STDLIB_NAMES.contains(&name)
}

fn is_constant_name(name: &str) -> bool {
    if name.starts_with("PlayerFlag_") {
        return true;
    }
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !first.is_ascii_uppercase() && first != '_' {
        return false;
    }
    chars.all(|c| c.is_ascii_uppercase() || c.is_ascii_digit() || c == '_')
}

fn is_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first.is_ascii_alphabetic() || first == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

fn emit_engine(snapshot: &LuaDefsSnapshot) -> String {
    let mut out = String::from(GENERATED_BANNER);
    out.push('\n');
    // Bases before derived classes so LuaLS sees `---@class Creature` first.
    let mut names: Vec<&String> = snapshot.classes.keys().collect();
    names.sort_by_key(|n| {
        (
            usize::from(
                snapshot
                    .classes
                    .get(*n)
                    .and_then(|c| c.base.as_ref())
                    .is_some(),
            ),
            *n,
        )
    });
    for name in names {
        let class = snapshot.classes.get(name).expect("class");
        match &class.base {
            Some(base) => out.push_str(&format!("---@class {name} : {base}\n")),
            None => out.push_str(&format!("---@class {name}\n")),
        }
        for field in &class.fields {
            out.push_str(&format!("---@field {field} any\n"));
        }
        out.push_str(&format!("{name} = {{}}\n\n"));
        for method in &class.methods {
            out.push_str(&format!("function {name}:{method}(...) end\n"));
        }
        for func in &class.table_functions {
            if class.methods.contains(func) {
                continue;
            }
            out.push_str(&format!("function {name}.{func}(...) end\n"));
        }
        if !class.methods.is_empty() || !class.table_functions.is_empty() {
            out.push('\n');
        }
    }
    out
}

fn emit_constants(snapshot: &LuaDefsSnapshot) -> String {
    let mut out = String::from(GENERATED_BANNER);
    out.push('\n');
    for (name, value) in &snapshot.constants {
        out.push_str(&format!("{name} = {}\n", format_constant(value)));
    }
    if !snapshot.nested_tables.is_empty() {
        out.push('\n');
    }
    for (name, inner) in &snapshot.nested_tables {
        out.push_str(&format!("{name} = {{\n"));
        for (key, value) in inner {
            out.push_str(&format!("    {key} = {},\n", format_constant(value)));
        }
        out.push_str("}\n");
    }
    out
}

fn emit_globals(snapshot: &LuaDefsSnapshot) -> String {
    let mut out = String::from(GENERATED_BANNER);
    out.push('\n');
    for name in &snapshot.functions {
        out.push_str(&format!("function {name}(...) end\n"));
    }
    out
}

fn format_constant(value: &ConstantValue) -> String {
    match value {
        ConstantValue::Integer(n) => n.to_string(),
        ConstantValue::Boolean(true) => "true".into(),
        ConstantValue::Boolean(false) => "false".into(),
        ConstantValue::String(s) => format!("{s:?}"),
    }
}

/// Workspace `lua-defs/` directory (two levels above this crate).
pub fn default_lua_defs_dir() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join("lua-defs")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::class_registry::REQUIRED_CLASS_GLOBALS;

    fn snapshot() -> LuaDefsSnapshot {
        let runtime = LuaRuntime::new().expect("runtime");
        snapshot_lua_defs(&runtime).expect("snapshot")
    }

    #[test]
    fn lua_defs_snapshot_covers_engine_surface() {
        let snap = snapshot();
        for name in REQUIRED_CLASS_GLOBALS {
            assert!(
                snap.classes.contains_key(*name),
                "{name} must appear in generated class stubs"
            );
        }

        let tile = snap.classes.get("Tile").expect("Tile");
        assert!(
            tile.methods.contains("getGround"),
            "Tile:getGround is a native method"
        );
        assert!(
            tile.methods.contains("getHouse"),
            "Tile:getHouse is a native method (E7)"
        );
        assert!(
            tile.methods.contains("addItemEx"),
            "Tile:addItemEx is a native method (R3)"
        );

        let house = snap.classes.get("House").expect("House");
        assert!(
            house.methods.contains("getId"),
            "House:getId is a native method (E7)"
        );

        let town = snap.classes.get("Town").expect("Town");
        assert!(town.callable, "Town(id or name) is callable");
        assert!(
            town.methods.contains("getTemplePosition"),
            "Town:getTemplePosition is a native method"
        );
        assert!(
            town.methods.contains("getId"),
            "Town:getId is a native method"
        );

        let creature = snap.classes.get("Creature").expect("Creature");
        assert!(
            creature.methods.contains("addHealth"),
            "Creature:addHealth is a native method (E4)"
        );
        assert!(
            creature.methods.contains("addItemEx"),
            "Creature:addItemEx is a native method (R3)"
        );
        assert!(
            creature.methods.contains("say"),
            "Creature:say is a native method (E5)"
        );
        assert!(
            creature.methods.contains("showTextDialog"),
            "Creature:showTextDialog is a native method (E6)"
        );
        assert!(
            creature.methods.contains("hasLearnedSpell"),
            "Creature:hasLearnedSpell is a native method (E6)"
        );
        assert!(
            creature.methods.contains("getInstantSpells"),
            "Creature:getInstantSpells is a native method (spellbook)"
        );
        assert!(
            creature.methods.contains("getTown"),
            "Creature:getTown is a native method"
        );
        assert!(
            creature.methods.contains("getIp"),
            "Creature:getIp is a native method"
        );
        assert!(
            creature.methods.contains("setGhostMode"),
            "Creature:setGhostMode is a native method"
        );
        assert!(
            creature.methods.contains("popupFYI"),
            "Creature:popupFYI is a native method"
        );
        assert!(
            creature.methods.contains("remove"),
            "Creature:remove is a native method (luaCreatureRemove)"
        );

        let game = snap.classes.get("Game").expect("Game");
        assert!(
            game.table_functions.contains("createItem"),
            "Game.createItem is a class-table function"
        );
        assert!(
            game.table_functions.contains("createTile"),
            "Game.createTile is a class-table function (R5)"
        );
        assert!(
            game.table_functions.contains("getInstantSpells"),
            "Game.getInstantSpells lists instant defs (E6)"
        );
        assert!(
            game.table_functions.contains("saveServer"),
            "Game.saveServer is a class-table function (luaSaveServer)"
        );
        assert!(
            snap.functions.contains("saveServer"),
            "saveServer is a global (luaSaveServer)"
        );

        let item_type = snap.classes.get("ItemType").expect("ItemType");
        assert!(
            item_type.methods.contains("getDestroyId"),
            "ItemType:getDestroyId is a native method"
        );
        assert!(
            item_type.methods.contains("getFluidSource"),
            "ItemType:getFluidSource is a native method"
        );
        assert!(
            item_type.methods.contains("getArticle"),
            "ItemType:getArticle is a native method (R1)"
        );
        assert!(
            item_type.methods.contains("getPluralName"),
            "ItemType:getPluralName is a native method (R1)"
        );
        assert!(
            item_type.methods.contains("getWeight"),
            "ItemType:getWeight is a native method (R1)"
        );
        assert!(
            item_type.methods.contains("isContainer"),
            "ItemType:isContainer is a native method (R1)"
        );

        let action = snap.classes.get("Action").expect("Action");
        assert!(
            action.methods.contains("allowFarUse"),
            "Action:allowFarUse is a ctor-instance method"
        );

        assert!(
            matches!(
                snap.constants.get("SKILL_FISHING"),
                Some(ConstantValue::Integer(6))
            ),
            "SKILL_FISHING must be generated as a constant"
        );

        // E1 — `other-actions-plan.md`: 772 sequential fluids, talk, sound, coins.
        assert!(
            matches!(
                snap.constants.get("FLUID_WATER"),
                Some(ConstantValue::Integer(1))
            ),
            "FLUID_WATER must be 1 (const.h:95)"
        );
        assert!(
            matches!(
                snap.constants.get("TALKTYPE_SAY"),
                Some(ConstantValue::Integer(1))
            ),
            "TALKTYPE_SAY must be 1 (const.h:62)"
        );
        assert!(
            matches!(
                snap.constants.get("CONST_ME_SOUND_YELLOW"),
                Some(ConstantValue::Integer(22))
            ),
            "CONST_ME_SOUND_YELLOW must be 22 (const.h:32)"
        );
        assert!(
            matches!(
                snap.constants.get("ITEM_GOLD_COIN"),
                Some(ConstantValue::Integer(2148))
            ),
            "ITEM_GOLD_COIN must be 2148 (const.h:451)"
        );

        assert!(
            snap.functions.contains("doTargetCombatHealth"),
            "doTargetCombatHealth is a free function"
        );

        let player = snap.classes.get("Player").expect("Player");
        assert_eq!(player.base.as_deref(), Some("Creature"));
        let container = snap.classes.get("Container").expect("Container");
        assert_eq!(container.base.as_deref(), Some("Item"));
        assert!(
            container.methods.contains("addItem"),
            "Container:addItem is a native method (R2)"
        );
        assert!(
            container.methods.contains("addItemEx"),
            "Container:addItemEx is a native method (R3)"
        );
        assert!(
            container.methods.contains("remove"),
            "Container:remove is Item::remove on container userdata (R2 / onUseQuest)"
        );

        let tfs = snap.classes.get("tfs").expect("tfs");
        assert!(
            tfs.table_functions.contains("appendLog"),
            "tfs.appendLog is the stdlib-allowlist write capability"
        );
    }

    #[test]
    fn lua_defs_committed_files_are_current() {
        let snap = snapshot();
        check_lua_defs(&default_lua_defs_dir(), &snap).expect("lua-defs/ must match emit_lua_defs");
    }
}
