-- Generated by import-npcs from gen-t-wands-prem-s.ndb. Do not edit by hand.
return {
	{
		line = 5,
		when = {
			{ words = { "wand" } },
		},
		actions = {
			{ say = "Wands can be wielded by sorcerers only and have a certain level requirement. There are five different wands, would you like to hear about them?" },
			{ set = { var = "topic", value = 90 } },
		},
	},
	{
		line = 6,
		when = {
			{ words = { "rod" } },
		},
		actions = {
			{ say = "Rods can be wielded by druids only and have a certain level requirement. There are five different rods, would you like to hear about them?" },
			{ set = { var = "topic", value = 91 } },
		},
	},
	{
		line = 8,
		when = {
			{ expr = { session = "topic" }, op = "=", rhs = 90 },
			{ words = { "yes" } },
		},
		actions = {
			{ say = "The names of the wands are 'Wand of Vortex', 'Wand of Dragonbreath', 'Wand of Plague', 'Wand of Cosmic Energy' and 'Wand of Inferno'. Which one would you like to buy?" },
		},
	},
	{
		line = 9,
		when = {
			{ expr = { session = "topic" }, op = "=", rhs = 90 },
			{ words = { "no" } },
		},
		actions = {
			{ say = "Maybe another time." },
		},
	},
	{
		line = 10,
		when = {
			{ expr = { session = "topic" }, op = "=", rhs = 90 },
		},
		actions = {
			{ say = "Maybe another time." },
		},
	},
	{
		line = 12,
		when = {
			{ expr = { session = "topic" }, op = "=", rhs = 91 },
			{ words = { "yes" } },
		},
		actions = {
			{ say = "The names of the rods are 'Snakebite Rod', 'Moonlight Rod', 'Volcanic Rod', 'Quagmire Rod', and 'Tempest Rod'. Which one would you like to buy?" },
		},
	},
	{
		line = 13,
		when = {
			{ expr = { session = "topic" }, op = "=", rhs = 91 },
			{ words = { "no" } },
		},
		actions = {
			{ say = "Maybe another time." },
		},
	},
	{
		line = 14,
		when = {
			{ expr = { session = "topic" }, op = "=", rhs = 91 },
		},
		actions = {
			{ say = "Maybe another time." },
		},
	},
	{
		line = 16,
		when = {
			{ property = "sorcerer" },
			{ words = { "wand" } },
			{ words = { "of" } },
			{ words = { "vortex" } },
			{ expr = { questValue = 333 }, op = "<", rhs = 1 },
		},
		actions = {
			{ say = "Oh, is this your first wand of vortex? Take this little present from me as a free sample!" },
			{ setQuestValue = { id = 333, value = 1 } },
			{ set = { var = "type", value = 3074 } },
			{ set = { var = "amount", value = 1 } },
			{ create = { item = { session = "type" } } },
		},
	},
	{
		line = 17,
		when = {
			{ property = "druid" },
			{ words = { "snakebite" } },
			{ words = { "rod" } },
			{ expr = { questValue = 333 }, op = "<", rhs = 1 },
		},
		actions = {
			{ say = "Oh, is this your first snakebite rod? Take this little present from me as a free sample!" },
			{ setQuestValue = { id = 333, value = 1 } },
			{ set = { var = "type", value = 3066 } },
			{ set = { var = "amount", value = 1 } },
			{ create = { item = { session = "type" } } },
		},
	},
	{
		line = 19,
		when = {
			{ words = { "wand" } },
			{ words = { "of" } },
			{ words = { "vortex" } },
		},
		actions = {
			{ set = { var = "type", value = 3074 } },
			{ set = { var = "amount", value = 1 } },
			{ set = { var = "price", value = 500 } },
			{ say = "This wand is only for sorcerers of level 7 and above. Would you like to buy a wand of vortex for %P gold?" },
			{ set = { var = "topic", value = 92 } },
		},
	},
	{
		line = 20,
		when = {
			{ words = { "wand" } },
			{ words = { "of" } },
			{ words = { "dragonbreath" } },
		},
		actions = {
			{ set = { var = "type", value = 3075 } },
			{ set = { var = "amount", value = 1 } },
			{ set = { var = "price", value = 1000 } },
			{ say = "This wand is only for sorcerers of level 13 and above. Would you like to buy a wand of dragonbreath for %P gold?" },
			{ set = { var = "topic", value = 92 } },
		},
	},
	{
		line = 21,
		when = {
			{ words = { "wand" } },
			{ words = { "of" } },
			{ words = { "plague" } },
		},
		actions = {
			{ set = { var = "type", value = 3072 } },
			{ set = { var = "amount", value = 1 } },
			{ set = { var = "price", value = 5000 } },
			{ say = "This wand is only for sorcerers of level 19 and above. Would you like to buy a wand of plague for %P gold?" },
			{ set = { var = "topic", value = 92 } },
		},
	},
	{
		line = 22,
		when = {
			{ words = { "wand" } },
			{ words = { "of" } },
			{ words = { "cosmic" } },
			{ words = { "energy" } },
		},
		actions = {
			{ set = { var = "type", value = 3073 } },
			{ set = { var = "amount", value = 1 } },
			{ set = { var = "price", value = 10000 } },
			{ say = "This wand is only for sorcerers of level 26 and above. Would you like to buy a wand of cosmic energy for %P gold?" },
			{ set = { var = "topic", value = 92 } },
		},
	},
	{
		line = 23,
		when = {
			{ words = { "wand" } },
			{ words = { "of" } },
			{ words = { "inferno" } },
		},
		actions = {
			{ set = { var = "type", value = 3071 } },
			{ set = { var = "amount", value = 1 } },
			{ set = { var = "price", value = 15000 } },
			{ say = "This wand is only for sorcerers of level 33 and above. Would you like to buy a wand of inferno for %P gold?" },
			{ set = { var = "topic", value = 92 } },
		},
	},
	{
		line = 25,
		when = {
			{ words = { "snakebite" } },
			{ words = { "rod" } },
		},
		actions = {
			{ set = { var = "type", value = 3066 } },
			{ set = { var = "amount", value = 1 } },
			{ set = { var = "price", value = 500 } },
			{ say = "This rod is only for druids of level 7 and above. Would you like to buy a snakebite rod for %P gold?" },
			{ set = { var = "topic", value = 92 } },
		},
	},
	{
		line = 26,
		when = {
			{ words = { "moonlight" } },
			{ words = { "rod" } },
		},
		actions = {
			{ set = { var = "type", value = 3070 } },
			{ set = { var = "amount", value = 1 } },
			{ set = { var = "price", value = 1000 } },
			{ say = "This rod is only for druids of level 13 and above. Would you like to buy a moonlight rod for %P gold?" },
			{ set = { var = "topic", value = 92 } },
		},
	},
	{
		line = 27,
		when = {
			{ words = { "volcanic" } },
			{ words = { "rod" } },
		},
		actions = {
			{ set = { var = "type", value = 3069 } },
			{ set = { var = "amount", value = 1 } },
			{ set = { var = "price", value = 5000 } },
			{ say = "This rod is only for druids of level 19 and above. Would you like to buy a volcanic rod for %P gold?" },
			{ set = { var = "topic", value = 92 } },
		},
	},
	{
		line = 28,
		when = {
			{ words = { "quagmire" } },
			{ words = { "rod" } },
		},
		actions = {
			{ set = { var = "type", value = 3065 } },
			{ set = { var = "amount", value = 1 } },
			{ set = { var = "price", value = 10000 } },
			{ say = "This rod is only for druids of level 26 and above. Would you like to buy a quagmire rod for %P gold?" },
			{ set = { var = "topic", value = 92 } },
		},
	},
	{
		line = 29,
		when = {
			{ words = { "tempest" } },
			{ words = { "rod" } },
		},
		actions = {
			{ set = { var = "type", value = 3067 } },
			{ set = { var = "amount", value = 1 } },
			{ set = { var = "price", value = 15000 } },
			{ say = "This rod is only for druids of level 33 and above. Would you like to buy a tempest rod for %P gold?" },
			{ set = { var = "topic", value = 92 } },
		},
	},
	{
		line = 31,
		when = {
			{ capture = 1 },
			{ expr = 1, op = "<", rhs = { capture = 1 } },
			{ words = { "wand" } },
			{ words = { "of" } },
			{ words = { "vortex" } },
		},
		actions = {
			{ set = { var = "type", value = 3074 } },
			{ set = { var = "amount", value = { capture = 1 } } },
			{ set = { var = "price", value = { binary = { op = "*", lhs = 500, rhs = { capture = 1 } } } } },
			{ say = "This wand is only for sorcerers of level 7 and above. Would you like to buy %A wands of vortex for %P gold?" },
			{ set = { var = "topic", value = 92 } },
		},
	},
	{
		line = 32,
		when = {
			{ capture = 1 },
			{ expr = 1, op = "<", rhs = { capture = 1 } },
			{ words = { "wand" } },
			{ words = { "of" } },
			{ words = { "dragonbreath" } },
		},
		actions = {
			{ set = { var = "type", value = 3075 } },
			{ set = { var = "amount", value = { capture = 1 } } },
			{ set = { var = "price", value = { binary = { op = "*", lhs = 1000, rhs = { capture = 1 } } } } },
			{ say = "This wand is only for sorcerers of level 13 and above. Would you like to buy %A wands of dragonbreath for %P gold?" },
			{ set = { var = "topic", value = 92 } },
		},
	},
	{
		line = 33,
		when = {
			{ capture = 1 },
			{ expr = 1, op = "<", rhs = { capture = 1 } },
			{ words = { "wand" } },
			{ words = { "of" } },
			{ words = { "plague" } },
		},
		actions = {
			{ set = { var = "type", value = 3072 } },
			{ set = { var = "amount", value = { capture = 1 } } },
			{ set = { var = "price", value = { binary = { op = "*", lhs = 5000, rhs = { capture = 1 } } } } },
			{ say = "This wand is only for sorcerers of level 19 and above. Would you like to buy %A wands of plague for %P gold?" },
			{ set = { var = "topic", value = 92 } },
		},
	},
	{
		line = 34,
		when = {
			{ capture = 1 },
			{ expr = 1, op = "<", rhs = { capture = 1 } },
			{ words = { "wand" } },
			{ words = { "of" } },
			{ words = { "cosmic" } },
			{ words = { "energy" } },
		},
		actions = {
			{ set = { var = "type", value = 3073 } },
			{ set = { var = "amount", value = { capture = 1 } } },
			{ set = { var = "price", value = { binary = { op = "*", lhs = 10000, rhs = { capture = 1 } } } } },
			{ say = "This wand is only for sorcerers of level 26 and above. Would you like to buy %A wands of cosmic energy for %P gold?" },
			{ set = { var = "topic", value = 92 } },
		},
	},
	{
		line = 35,
		when = {
			{ capture = 1 },
			{ expr = 1, op = "<", rhs = { capture = 1 } },
			{ words = { "wand" } },
			{ words = { "of" } },
			{ words = { "inferno" } },
		},
		actions = {
			{ set = { var = "type", value = 3071 } },
			{ set = { var = "amount", value = { capture = 1 } } },
			{ set = { var = "price", value = { binary = { op = "*", lhs = 15000, rhs = { capture = 1 } } } } },
			{ say = "This wand is only for sorcerers of level 33 and above. Would you like to buy %A wands of inferno for %P gold?" },
			{ set = { var = "topic", value = 92 } },
		},
	},
	{
		line = 37,
		when = {
			{ capture = 1 },
			{ expr = 1, op = "<", rhs = { capture = 1 } },
			{ words = { "snakebite" } },
			{ words = { "rod" } },
		},
		actions = {
			{ set = { var = "type", value = 3066 } },
			{ set = { var = "amount", value = { capture = 1 } } },
			{ set = { var = "price", value = { binary = { op = "*", lhs = 500, rhs = { capture = 1 } } } } },
			{ say = "This rod is only for druids of level 7 and above. Would you like to buy %A snakebite rods for %P gold?" },
			{ set = { var = "topic", value = 92 } },
		},
	},
	{
		line = 38,
		when = {
			{ capture = 1 },
			{ expr = 1, op = "<", rhs = { capture = 1 } },
			{ words = { "moonlight" } },
			{ words = { "rod" } },
		},
		actions = {
			{ set = { var = "type", value = 3070 } },
			{ set = { var = "amount", value = { capture = 1 } } },
			{ set = { var = "price", value = { binary = { op = "*", lhs = 1000, rhs = { capture = 1 } } } } },
			{ say = "This rod is only for druids of level 13 and above. Would you like to buy %A moonlight rods for %P gold?" },
			{ set = { var = "topic", value = 92 } },
		},
	},
	{
		line = 39,
		when = {
			{ capture = 1 },
			{ expr = 1, op = "<", rhs = { capture = 1 } },
			{ words = { "volcanic" } },
			{ words = { "rod" } },
		},
		actions = {
			{ set = { var = "type", value = 3069 } },
			{ set = { var = "amount", value = { capture = 1 } } },
			{ set = { var = "price", value = { binary = { op = "*", lhs = 5000, rhs = { capture = 1 } } } } },
			{ say = "This rod is only for druids of level 19 and above. Would you like to buy %A volcanic rods for %P gold?" },
			{ set = { var = "topic", value = 92 } },
		},
	},
	{
		line = 40,
		when = {
			{ capture = 1 },
			{ expr = 1, op = "<", rhs = { capture = 1 } },
			{ words = { "quagmire" } },
			{ words = { "rod" } },
		},
		actions = {
			{ set = { var = "type", value = 3065 } },
			{ set = { var = "amount", value = { capture = 1 } } },
			{ set = { var = "price", value = { binary = { op = "*", lhs = 10000, rhs = { capture = 1 } } } } },
			{ say = "This rod is only for druids of level 26 and above. Would you like to buy %A quagmire rods for %P gold?" },
			{ set = { var = "topic", value = 92 } },
		},
	},
	{
		line = 41,
		when = {
			{ capture = 1 },
			{ expr = 1, op = "<", rhs = { capture = 1 } },
			{ words = { "tempest" } },
			{ words = { "rod" } },
		},
		actions = {
			{ set = { var = "type", value = 3067 } },
			{ set = { var = "amount", value = { capture = 1 } } },
			{ set = { var = "price", value = { binary = { op = "*", lhs = 15000, rhs = { capture = 1 } } } } },
			{ say = "This rod is only for druids of level 33 and above. Would you like to buy %A tempest rods for %P gold?" },
			{ set = { var = "topic", value = 92 } },
		},
	},
	{
		line = 44,
		when = {
			{ expr = { session = "topic" }, op = "=", rhs = 92 },
			{ words = { "yes" } },
			{ expr = { countMoney = true }, op = ">=", rhs = { session = "price" } },
		},
		actions = {
			{ say = "Here you are." },
			{ deleteMoney = true },
			{ create = { item = { session = "type" } } },
		},
	},
	{
		line = 45,
		when = {
			{ expr = { session = "topic" }, op = "=", rhs = 92 },
			{ words = { "yes" } },
		},
		actions = {
			{ say = "Sorry, you don't have enough gold." },
		},
	},
	{
		line = 46,
		when = {
			{ expr = { session = "topic" }, op = "=", rhs = 92 },
		},
		actions = {
			{ say = "You don't know what you're missing." },
		},
	},
}
