use std::collections::{HashMap, VecDeque};
use std::time::Instant;

use slotmap::SlotMap;
use tfs_rust_common::enums::{Direction, SkullType};
use tfs_rust_common::Position;
use tfs_rust_core::{
    CreatureBase, CreatureId, CreatureKind, Outfit, Player, PlayerEconomy, PlayerInventory,
    PlayerSkills, PlayerSocial,
};

fn test_player(name: &str, guid: u32, pos: Position) -> Player {
    Player {
        base: CreatureBase {
            name: name.to_string(),
            position: pos,
            direction: Direction::North,
            health: 100,
            max_health: 100,
            outfit: Outfit::default(),
            speed: 220,
            base_speed: 220,
            var_speed: 0,
            skull: SkullType::None,
            drunkenness: 0,
            active_conditions: Vec::new(),
            walk_queue: VecDeque::new(),
            walk_destinations: VecDeque::new(),
            last_step: None,
            last_step_cost: 1,
            last_step_ground_speed: 150,
            next_wakeup: None,
            last_step_server_ms: None,
            earliest_walk_server_ms: 0,
            earliest_spell_server_ms: 0,
            earliest_multiuse_server_ms: 0,
            cancel_next_walk: false,
            force_update_follow_path: false,
            walk_update_ticks: 0,
            is_updating_path: false,
            has_follow_path: false,
            movement_blocked: false,
            stairhop_blocked_until: None,
            follow_target: None,
            attack_target: None,
            master: None,
            damage_map: Default::default(),
            last_hit_by: None,
            earliest_attack_ms: 0,
        latest_attack_round: 0,
            earliest_defend_ms: 0,
            last_defend_ms: 0,
            learning_points: 0,
            todo: Default::default(),
            chase_mode: Default::default(),
            last_auto_walk_armed_ms: u64::MAX,
        },
        account_id: 0,
        guid,
        account_type: 1,
        group_id: 1,
        set_max_speed: false,
        sex: tfs_rust_core::creature::PlayerSex::Male,
        vocation_id: 0,
        vocation_profile: tfs_rust_core::creature::vocation::VocationProfile::none_vocation(),
        level: 1,
        experience: 0,
        mana: 0,
        max_mana: 0,
        capacity: 400,
        inventory: PlayerInventory::default(),
        skills: PlayerSkills::with_levels(10, 10, 10, 10, 10, 10, 10, 0),
        economy: PlayerEconomy {
            balance: 0,
            soul: 0,
        },
        social: PlayerSocial::default(),
        town_id: 0,
        premium_ends_at: 0,
        stamina_minutes: 0,
        offline_training_ms: 0,
        spell_cooldown_end: HashMap::new(),
        spell_group_cooldown_end: HashMap::new(),
        operating_system: 0,
        otclient_v8: 0,
        ghost_mode: false,
        equipment_slots: std::array::from_fn(|_| None),
        inventory_weight: 0,
        items_light: tfs_rust_core::LightInfo::default(),
        internal_light: tfs_rust_core::LightInfo::default(),
        inventory_abilities: [false; 11],
        dact_skills: [0; 7],
        mdact_skills: [0; 7],
        last_combat_weapons: Default::default(),
        var_stats: [0; 4],
        condition_suppressions: 0,
        shop_owner: None,
        vip_list: Vec::new(),
        outfits: Vec::new(),
        health_hidden: false,
        last_activity: Instant::now(),
        last_command_round: 0,
        last_action_round: 0,
        food_remaining: 0,
        food_level: 0,
        earliest_logout_round: 0,
        attacked_players: Vec::new(),
        former_attacked_players: Vec::new(),
        aggressor: false,
        former_aggressor: false,
        former_logout_round: 0,
        playerkiller_end: 0,
        murder_timestamps: [0; 20],
        logging_out: false,
        logout_allowed: false,
        last_ping_sent: Instant::now(),
        last_pong_at: Instant::now(),
        next_action_until: None,
        walk_action: None,
        depot_chests: HashMap::new(),
        depot_lockers: HashMap::new(),
        inbox_root: None,
        last_depot_id: -1,
        persist: None,
        sim_melee_defense: 0,
        sim_melee_attack: 0,
        attack_mode: Default::default(),
        secure_mode: false,
        earliest_protection_zone_round: 0,
            client_icons: 0,
        message_buffer_count: 0,
        message_buffer_ticks: 0,
        blessings: 0,
    }
}

#[test]
fn slotmap_generation_invalidation() {
    let mut sm: SlotMap<CreatureId, CreatureKind> = SlotMap::with_key();
    let id = sm.insert(CreatureKind::Player(test_player(
        "a",
        1,
        Position::new(1, 1, 7),
    )));
    sm.remove(id);
    let id2 = sm.insert(CreatureKind::Player(test_player(
        "b",
        2,
        Position::new(2, 2, 7),
    )));
    assert_ne!(id, id2);
}
