-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: prisoner.npc

local npc = NpcType("A Prisoner")
npc:appearance({ lookType = 130, lookHead = 81, lookBody = 40, lookLegs = 55, lookFeet = 94 })
npc:movement({ radius = 2, speed = 25, goStrength = 25 })
npc:health(100)
npc:sex(1)
npc:race(1)

npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = {
		{
			line = 13,
			when = {
				{ situation = "address" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Huh? What? I can see! Wow! A non-mino. Did they capture you as well?" },
			},
		},
		{
			line = 14,
			when = {
				{ situation = "address" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 15,
			when = {
				{ situation = "address" },
				{ select = true },
			},
			actions = {
				{ idle = true },
			},
		},
		{
			line = 16,
			when = {
				{ situation = "busy" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Not much space right here. Hehe. I haven´t had a visitor for some time and right now there are two! Hehehe! Great!" },
			},
		},
		{
			line = 17,
			when = {
				{ situation = "busy" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 18,
			when = {
				{ situation = "busy" },
				{ select = true },
			},
			actions = {
				{ nop = true },
			},
		},
		{
			line = 19,
			when = {
				{ situation = "vanish" },
				{ expr = { questValue = 1 }, op = ">", rhs = 0 },
				{ select = true },
			},
			actions = {
				{ say = "Good bye! Don't forget about the secrets of mathemagics." },
			},
		},
		{
			line = 20,
			when = {
				{ situation = "vanish" },
				{ expr = { questValue = 1 }, op = "=", rhs = 0 },
				{ select = true },
			},
			actions = {
				{ say = "Wait! Don't leave! I want to tell you about my surreal numbers." },
			},
		},
		{
			line = 23,
			when = {
				{ words = { "bye" } },
			},
			actions = {
				{ say = "Next time we should talk about my surreal numbers." },
				{ idle = true },
			},
		},
		{
			line = 24,
			when = {
				{ words = { "farewell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 25,
			when = {
				{ words = { "job" } },
			},
			actions = {
				{ say = "Job? JOB? Hey man - I am in prison! But you know - once upon a time - I was a powerful mage! A mage ... come to think of it .., what is that - a mage?" },
			},
		},
		{
			line = 26,
			when = {
				{ words = { "name" } },
			},
			actions = {
				{ say = "My name is - uhm - hang on? I knew it yesterday, didn't I? Doesn't matter!" },
			},
		},
		{
			line = 27,
			when = {
				{ words = { "time" } },
			},
			actions = {
				{ say = "Better save time than comitting a crime. I am a poet and I know it!" },
			},
		},
		{
			line = 28,
			when = {
				{ words = { "sorcerer" } },
			},
			actions = {
				{ say = "I am the mightiest sorcerer from here to there! Yeah!" },
			},
		},
		{
			line = 29,
			when = {
				{ words = { "power" } },
			},
			actions = {
				{ say = "Power. Hmmm. Once while we were crossing the mountains together a man named Aureus said to me that parcels are equal to power. Any idea what that meant?" },
			},
		},
		{
			line = 30,
			when = {
				{ words = { "books" } },
			},
			actions = {
				{ say = "I have many books in my home. But only powerful people can read them. I bet you will only see three dots after the headline! Hehehe! Hahaha! Excellent!" },
			},
		},
		{
			line = 31,
			when = {
				{ words = { "mad" } },
				{ words = { "mage" } },
			},
			actions = {
				{ say = "Hey! That's me! You got it! Thanks mate - now I remember my name!" },
			},
		},
		{
			line = 32,
			when = {
				{ words = { "riddle" } },
			},
			actions = {
				{ say = "Great riddle, isn´t it? If you can tell me the correct answer, I will give you something. Hehehe!" },
			},
		},
		{
			line = 33,
			when = {
				{ words = { "something" } },
			},
			actions = {
				{ say = "No! I won´t tell you. Shame coz it would be useful for you - hehehe." },
			},
		},
		{
			line = 34,
			when = {
				{ words = { "apple" } },
			},
			actions = {
				{ set = { var = "type", value = 2674 } },
				{ set = { var = "amount", value = 1 } },
				{ say = "Apples! Real apples! Man I love them! Can I have one? Oh please say yes!" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 35,
			when = {
				{ words = { "escape" } },
			},
			actions = {
				{ say = "How could I escape? They only give me rotten food here. I can´t regain my powers because I have no mana!" },
			},
		},
		{
			line = 36,
			when = {
				{ words = { "key" } },
			},
			actions = {
				{ say = "Sure I have the key! Hehehe! Perhaps I will give it to you. IF you can solve my riddle." },
			},
		},
		{
			line = 37,
			when = {
				{ words = { "mino" } },
			},
			actions = {
				{ say = "They are trying to capture me! Or hang on! Haven't they already captured me? Hmmm - I will have to think about this." },
			},
		},
		{
			line = 38,
			when = {
				{ words = { "markwin" } },
			},
			actions = {
				{ say = "He is the worst of them all! He is the king of the minos! May he burn in hell!" },
			},
		},
		{
			line = 39,
			when = {
				{ words = { "labyrinth" } },
			},
			actions = {
				{ say = "It´s easy to find your way through it! Just follow the pools of mud. Hehe - useful hint, isn´t it?" },
			},
		},
		{
			line = 40,
			when = {
				{ words = { "way" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 41,
			when = {
				{ words = { "palkar" } },
			},
			actions = {
				{ say = "He is the leader of the outcasts. I hope he will never conquer the city of Mintwallin. That would be the end of me!" },
			},
		},
		{
			line = 42,
			when = {
				{ words = { "karl" } },
			},
			actions = {
				{ say = "Tataah!" },
			},
		},
		{
			line = 43,
			when = {
				{ words = { "demon" } },
			},
			actions = {
				{ say = "The only monster I cannot conjure. But soon I will be powerful enough!" },
			},
		},
		{
			line = 44,
			when = {
				{ words = { "monster" } },
			},
			actions = {
				{ say = "Yeah! There are many monsters guarding my home. Only the bravest hero will be able to slay them!" },
			},
		},
		{
			line = 45,
			when = {
				{ words = { "conjure" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 46,
			when = {
				{ words = { "home" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 48,
			when = {
				{ words = { "number" } },
				{ expr = { questValue = 1 }, op = "<", rhs = 1 },
			},
			actions = {
				{ say = "My surreal numbers are based on astonishing facts. Are you interested in learning the secret of mathemagics?" },
				{ set = { var = "topic", value = 7 } },
				{ set = { var = "amount", value = { random = { 1, 4 } } } },
			},
		},
		{
			line = 49,
			when = {
				{ words = { "math" } },
				{ expr = { questValue = 1 }, op = "<", rhs = 1 },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 50,
			when = {
				{ words = { "1+1$" } },
				{ expr = { questValue = 1 }, op = "<", rhs = 1 },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 51,
			when = {
				{ words = { "1$" } },
				{ words = { "+$" } },
				{ words = { "1$" } },
				{ expr = { questValue = 1 }, op = "<", rhs = 1 },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 52,
			when = {
				{ words = { "1$" } },
				{ words = { "plus" } },
				{ words = { "1$" } },
				{ expr = { questValue = 1 }, op = "<", rhs = 1 },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 53,
			when = {
				{ words = { "one" } },
				{ words = { "plus" } },
				{ words = { "one" } },
				{ expr = { questValue = 1 }, op = "<", rhs = 1 },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 55,
			when = {
				{ words = { "number" } },
				{ expr = { questValue = 1 }, op = ">", rhs = 0 },
			},
			actions = {
				{ say = "You already know the secrets of mathemagics! Now go and use them to learn." },
			},
		},
		{
			line = 56,
			when = {
				{ words = { "math" } },
				{ expr = { questValue = 1 }, op = ">", rhs = 0 },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 57,
			when = {
				{ words = { "1+1$" } },
				{ expr = { questValue = 1 }, op = ">", rhs = 0 },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 58,
			when = {
				{ words = { "1$" } },
				{ words = { "+$" } },
				{ words = { "1$" } },
				{ expr = { questValue = 1 }, op = ">", rhs = 0 },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 59,
			when = {
				{ words = { "1$" } },
				{ words = { "plus" } },
				{ words = { "1$" } },
				{ expr = { questValue = 1 }, op = ">", rhs = 0 },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 60,
			when = {
				{ words = { "one" } },
				{ words = { "plus" } },
				{ words = { "one" } },
				{ expr = { questValue = 1 }, op = ">", rhs = 0 },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 61,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 7 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "But first tell me your favourite colour please!" },
				{ set = { var = "topic", value = 8 } },
			},
		},
		{
			line = 62,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 8 },
				{ expr = { questValue = 2 }, op = "=", rhs = 1 },
				{ words = { "red" } },
				{ select = true },
			},
			actions = {
				{ say = "Very interesting. So are you ready to proceed in you lesson in mathemagics?" },
				{ set = { var = "topic", value = 9 } },
			},
		},
		{
			line = 63,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 8 },
				{ expr = { questValue = 2 }, op = "=", rhs = 2 },
				{ words = { "blue" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 64,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 8 },
				{ expr = { questValue = 2 }, op = "=", rhs = 3 },
				{ words = { "black" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 65,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 8 },
				{ expr = { questValue = 2 }, op = "=", rhs = 4 },
				{ words = { "white" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 66,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 8 },
				{ expr = { questValue = 2 }, op = "=", rhs = 5 },
				{ words = { "orange" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 67,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 8 },
				{ expr = { questValue = 2 }, op = "=", rhs = 6 },
				{ words = { "green" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 68,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 8 },
				{ expr = { questValue = 2 }, op = "=", rhs = 7 },
				{ words = { "yellow" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 69,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 8 },
				{ expr = { questValue = 2 }, op = "=", rhs = 8 },
				{ words = { "brown" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 70,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 8 },
				{ expr = { questValue = 2 }, op = "=", rhs = 9 },
				{ words = { "violet" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 71,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 8 },
				{ expr = { questValue = 2 }, op = "=", rhs = 10 },
				{ words = { "pink" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 72,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 8 },
				{ expr = { questValue = 2 }, op = "=", rhs = 11 },
				{ words = { "silver" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 73,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 8 },
				{ expr = { questValue = 2 }, op = "=", rhs = 12 },
				{ words = { "gold" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 74,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 8 },
				{ expr = { questValue = 2 }, op = "=", rhs = 13 },
				{ words = { "grey" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 76,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 8 },
				{ select = true },
			},
			actions = {
				{ say = "I think you are not in touch with yourself, come back if you have tuned in on your own feelings." },
			},
		},
		{
			line = 78,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 9 },
				{ words = { "yes" } },
				{ expr = { session = "amount" }, op = "=", rhs = 1 },
			},
			actions = {
				{ say = "So know that everthing is based on the simple fact that 1 + 1 = 49!" },
				{ setQuestValue = { id = 1, value = 1 } },
			},
		},
		{
			line = 79,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 9 },
				{ words = { "yes" } },
				{ expr = { session = "amount" }, op = "=", rhs = 2 },
			},
			actions = {
				{ say = "So know that everthing is based on the simple fact that 1 + 1 = 94!" },
				{ setQuestValue = { id = 1, value = 2 } },
			},
		},
		{
			line = 80,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 9 },
				{ words = { "yes" } },
				{ expr = { session = "amount" }, op = "=", rhs = 3 },
			},
			actions = {
				{ say = "So know that everthing is based on the simple fact that 1 + 1 = 13!" },
				{ setQuestValue = { id = 1, value = 3 } },
			},
		},
		{
			line = 81,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 9 },
				{ words = { "yes" } },
				{ expr = { session = "amount" }, op = "=", rhs = 4 },
			},
			actions = {
				{ say = "So know that everthing is based on the simple fact that 1 + 1 = 1!" },
				{ setQuestValue = { id = 1, value = 4 } },
			},
		},
		{
			line = 84,
			when = {
				{ words = { "sell" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2260 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 10 } },
				{ say = "You want to sell me blank runes! I will give you 50000 gold for each rune! Interested?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 86,
			when = {
				{ words = { "dp-d-ks-p-dp" } },
			},
			actions = {
				{ set = { var = "type", value = 2674 } },
				{ set = { var = "amount", value = 7 } },
				{ say = "Hurray! For that I will give you my key for - hmm - let´s say ... some apples. Interested?" },
				{ set = { var = "topic", value = 3 } },
			},
		},
		{
			line = 87,
			when = {
				{ words = { "dp-d-sk-p-dp" } },
			},
			actions = {
				{ set = { var = "type", value = 2674 } },
				{ set = { var = "amount", value = 7 } },
				{ say = "Hurray! For that I will give you my key for - hmm - let´s say ... some apples. Interested?" },
				{ set = { var = "topic", value = 3 } },
			},
		},
		{
			line = 88,
			when = {
				{ words = { "pd-d-ks-p-pd" } },
			},
			actions = {
				{ set = { var = "type", value = 2674 } },
				{ set = { var = "amount", value = 7 } },
				{ say = "Hurray! For that I will give you my key for - hmm - let´s say ... some apples. Interested?" },
				{ set = { var = "topic", value = 3 } },
			},
		},
		{
			line = 89,
			when = {
				{ words = { "pd-d-sk-p-pd" } },
			},
			actions = {
				{ set = { var = "type", value = 2674 } },
				{ set = { var = "amount", value = 7 } },
				{ say = "Hurray! For that I will give you my key for - hmm - let´s say ... some apples. Interested?" },
				{ set = { var = "topic", value = 3 } },
			},
		},
		{
			line = 90,
			when = {
				{ words = { "dp-p-ks-d-dp" } },
			},
			actions = {
				{ set = { var = "type", value = 2674 } },
				{ set = { var = "amount", value = 7 } },
				{ say = "Hurray! For that I will give you my key for - hmm - let´s say ... some apples. Interested?" },
				{ set = { var = "topic", value = 3 } },
			},
		},
		{
			line = 91,
			when = {
				{ words = { "dp-p-sk-d-dp" } },
			},
			actions = {
				{ set = { var = "type", value = 2674 } },
				{ set = { var = "amount", value = 7 } },
				{ say = "Hurray! For that I will give you my key for - hmm - let´s say ... some apples. Interested?" },
				{ set = { var = "topic", value = 3 } },
			},
		},
		{
			line = 92,
			when = {
				{ words = { "pd-p-ks-d-pd" } },
			},
			actions = {
				{ set = { var = "type", value = 2674 } },
				{ set = { var = "amount", value = 7 } },
				{ say = "Hurray! For that I will give you my key for - hmm - let´s say ... some apples. Interested?" },
				{ set = { var = "topic", value = 3 } },
			},
		},
		{
			line = 93,
			when = {
				{ words = { "pd-p-sk-d-pd" } },
			},
			actions = {
				{ set = { var = "type", value = 2674 } },
				{ set = { var = "amount", value = 7 } },
				{ say = "Hurray! For that I will give you my key for - hmm - let´s say ... some apples. Interested?" },
				{ set = { var = "topic", value = 3 } },
			},
		},
		{
			line = 95,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
				{ expr = { count = { session = "type" } }, op = ">=", rhs = { session = "amount" } },
			},
			actions = {
				{ say = "Mnjam. Excellent! Thanks, man!" },
				{ delete = { item = { session = "type" }, count = 1 } },
			},
		},
		{
			line = 96,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "Do you want to trick me? You don´t have one lousy apple!" },
			},
		},
		{
			line = 97,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
			},
			actions = {
				{ say = "Ooooooooooo.<sniff>" },
			},
		},
		{
			line = 99,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
				{ words = { "yes" } },
				{ expr = { count = { session = "type" } }, op = ">=", rhs = { session = "amount" } },
			},
			actions = {
				{ say = "Ok. Take my money. I can summon new money anytime - hehehe." },
				{ delete = { item = { session = "type" }, count = 1 } },
				{ createMoney = true },
			},
		},
		{
			line = 100,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "You do not have one." },
			},
		},
		{
			line = 101,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
			},
			actions = {
				{ say = "Hmmmmm." },
			},
		},
		{
			line = 103,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 3 },
				{ words = { "yes" } },
				{ expr = { count = { session = "type" } }, op = ">=", rhs = { session = "amount" } },
			},
			actions = {
				{ say = "Mnjam - excellent apples. Now - about that key. You are sure want it?" },
				{ delete = { item = { session = "type" }, count = 1 } },
				{ set = { var = "topic", value = 4 } },
			},
		},
		{
			line = 104,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 3 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "Get some more apples first!" },
			},
		},
		{
			line = 105,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 3 },
			},
			actions = {
				{ say = "Then go away!" },
				{ idle = true },
			},
		},
		{
			line = 107,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 4 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "Really, really?" },
				{ set = { var = "topic", value = 5 } },
			},
		},
		{
			line = 108,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 4 },
			},
			actions = {
				{ say = "Then go away!" },
				{ idle = true },
			},
		},
		{
			line = 110,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 5 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "Really, really, really, really?" },
				{ set = { var = "topic", value = 6 } },
			},
		},
		{
			line = 111,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 5 },
			},
			actions = {
				{ say = "Then go away!" },
				{ idle = true },
			},
		},
		{
			line = 113,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 6 },
				{ words = { "yes" } },
			},
			actions = {
				{ set = { var = "type", value = 2088 } },
				{ set = { var = "data", value = 3666 } },
				{ set = { var = "amount", value = 1 } },
				{ say = "Then take it and get happy - or die, hehe." },
				{ create = { item = { session = "type" }, count = 1 } },
			},
		},
		{
			line = 114,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 6 },
			},
			actions = {
				{ say = "Then go away!" },
				{ idle = true },
			},
		},
	},
}))

npc:register()
