-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: alwin.npc

local npc = NpcType("Alwin")
npc:appearance({ lookType = 131, lookHead = 113, lookBody = 113, lookLegs = 113, lookFeet = 115 })
npc:movement({ radius = 10, speed = 6 })
npc:health(100)
npc:sex(1)
npc:race(1)

local rules = {}
NpcAppendRules(rules, NpcCatalogs["guards-venore"])
npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = rules,
}))

npc:register()
