-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: bashira.npc

local npc = NpcType("Bashira")
npc:appearance({ lookType = 144, lookHead = 78, lookBody = 62, lookLegs = 97, lookFeet = 76 })
npc:movement({ radius = 1, speed = 6, goStrength = 6 })
npc:health(100)
npc:sex(0)
npc:race(62)

npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = {
		{
			line = 13,
			when = {
				{ situation = "address" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Ashari %N." },
			},
		},
		{
			line = 14,
			when = {
				{ situation = "address" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 15,
			when = {
				{ situation = "address" },
				{ words = { "ashari$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 16,
			when = {
				{ situation = "address" },
				{ select = true },
			},
			actions = {
				{ idle = true },
			},
		},
		{
			line = 17,
			when = {
				{ situation = "busy" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Wait one moment, %N." },
				{ queue = true },
			},
		},
		{
			line = 18,
			when = {
				{ situation = "busy" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 19,
			when = {
				{ situation = "busy" },
				{ words = { "ashari$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 20,
			when = {
				{ situation = "busy" },
				{ select = true },
			},
			actions = {
				{ nop = true },
			},
		},
		{
			line = 21,
			when = {
				{ situation = "vanish" },
				{ select = true },
			},
			actions = {
				{ say = "Asha Thrazi." },
			},
		},
		{
			line = 23,
			when = {
				{ words = { "bye" } },
			},
			actions = {
				{ say = "Asha Thrazi." },
				{ idle = true },
			},
		},
		{
			line = 24,
			when = {
				{ words = { "farewell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 25,
			when = {
				{ words = { "asha" } },
				{ words = { "thrazi" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 26,
			when = {
				{ words = { "job" } },
			},
			actions = {
				{ say = "I sell various equipment and buy some stuff." },
			},
		},
		{
			line = 27,
			when = {
				{ words = { "equipment" } },
			},
			actions = {
				{ say = "I sell shovels, picks, scythes, bags, ropes, backpacks, plates, cups, scrolls, parchments, documents, watches, various sources of light, fishing rods and sixpacks of worms." },
			},
		},
		{
			line = 28,
			when = {
				{ words = { "goods" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 29,
			when = {
				{ words = { "light" } },
			},
			actions = {
				{ say = "I sell torches, candelabra, and oil." },
			},
		},
		{
			line = 30,
			when = {
				{ words = { "name" } },
			},
			actions = {
				{ say = "I am Bashira Darkmark." },
			},
		},
		{
			line = 32,
			when = {
				{ words = { "carlin" } },
			},
			actions = {
				{ say = "Carlin has some capable fighters, allthough they lack the grace of an elf." },
			},
		},
		{
			line = 33,
			when = {
				{ words = { "thais" } },
			},
			actions = {
				{ say = "The people of thais boast about their mighty kingdom, but eventually their short lives will doom everything they buld." },
			},
		},
		{
			line = 34,
			when = {
				{ words = { "venore" } },
			},
			actions = {
				{ say = "Their merchants have no patience and all to fast they loose their masks of friedlyness." },
			},
		},
		{
			line = 35,
			when = {
				{ words = { "roderick" } },
			},
			actions = {
				{ say = "His presence here is a waste of space and talking to or even about him a waste of time." },
			},
		},
		{
			line = 36,
			when = {
				{ words = { "olrik" } },
			},
			actions = {
				{ say = "He is quite amusing for a human." },
			},
		},
		{
			line = 38,
			when = {
				{ words = { "elves" } },
			},
			actions = {
				{ say = "That's our race." },
			},
		},
		{
			line = 39,
			when = {
				{ words = { "dwarfs" } },
			},
			actions = {
				{ say = "They have some talent in mining and smithing." },
			},
		},
		{
			line = 40,
			when = {
				{ words = { "humans" } },
			},
			actions = {
				{ say = "They have nothing to give us." },
			},
		},
		{
			line = 41,
			when = {
				{ words = { "troll" } },
			},
			actions = {
				{ say = "They are lazy and clumsy. We should use dwarfs instead." },
			},
		},
		{
			line = 43,
			when = {
				{ words = { "cenath" } },
			},
			actions = {
				{ say = "Their magic is almost as impressive as their egos." },
			},
		},
		{
			line = 44,
			when = {
				{ words = { "kuridai" } },
			},
			actions = {
				{ say = "Without us and our tools nothing would work in this town." },
			},
		},
		{
			line = 45,
			when = {
				{ words = { "deraisim" } },
			},
			actions = {
				{ say = "Useless leafeaters." },
			},
		},
		{
			line = 46,
			when = {
				{ words = { "abdaisim" } },
			},
			actions = {
				{ say = "They left; perhaps we should do that, too." },
			},
		},
		{
			line = 47,
			when = {
				{ words = { "teshial" } },
			},
			actions = {
				{ say = "A stupid Cenath-myth." },
			},
		},
		{
			line = 48,
			when = {
				{ words = { "ferumbras" } },
			},
			actions = {
				{ say = "He may scare the treedwellers or the big-mouthes above, but not the Kuridai." },
			},
		},
		{
			line = 49,
			when = {
				{ words = { "crunor" } },
			},
			actions = {
				{ say = "One god of many. They are all alike and of no use." },
			},
		},
		{
			line = 51,
			when = {
				{ words = { "time" } },
			},
			actions = {
				{ say = "Buy a watch." },
			},
		},
		{
			line = 52,
			when = {
				{ words = { "food" } },
			},
			actions = {
				{ say = "I am not dealing with food." },
			},
		},
		{
			line = 54,
			when = {
				{ words = { "torch" } },
			},
			actions = {
				{ set = { var = "type", value = 2050 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 2 } },
				{ say = "Do you want to buy a torch for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 55,
			when = {
				{ words = { "candelab" } },
			},
			actions = {
				{ set = { var = "type", value = 2041 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 8 } },
				{ say = "Do you want to buy a candelabrum for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 56,
			when = {
				{ words = { "bag" } },
			},
			actions = {
				{ set = { var = "type", value = 1991 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 4 } },
				{ say = "Do you want to buy a bag for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 57,
			when = {
				{ words = { "scroll" } },
			},
			actions = {
				{ set = { var = "type", value = 1949 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 5 } },
				{ say = "Do you want to buy a scroll for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 58,
			when = {
				{ words = { "document" } },
			},
			actions = {
				{ set = { var = "type", value = 1968 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 12 } },
				{ say = "Do you want to buy a document for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 59,
			when = {
				{ words = { "parchment" } },
			},
			actions = {
				{ set = { var = "type", value = 1969 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 8 } },
				{ say = "Do you want to buy a parchment for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 60,
			when = {
				{ words = { "shovel" } },
			},
			actions = {
				{ set = { var = "type", value = 2554 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 50 } },
				{ say = "Do you want to buy a shovel for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 61,
			when = {
				{ words = { "backpack" } },
			},
			actions = {
				{ set = { var = "type", value = 1998 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 20 } },
				{ say = "Do you want to buy a backpack for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 62,
			when = {
				{ words = { "scythe" } },
			},
			actions = {
				{ set = { var = "type", value = 2550 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 50 } },
				{ say = "Do you want to buy a scythe for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 63,
			when = {
				{ words = { "pick" } },
			},
			actions = {
				{ set = { var = "type", value = 2553 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 50 } },
				{ say = "Do you want to buy a pick for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 64,
			when = {
				{ words = { "watch" } },
			},
			actions = {
				{ set = { var = "type", value = 2036 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 20 } },
				{ say = "Do you want to buy one of my high quality watches for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 65,
			when = {
				{ words = { "rope" } },
			},
			actions = {
				{ set = { var = "type", value = 2120 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 50 } },
				{ say = "Do you want to buy a rope for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 66,
			when = {
				{ words = { "rod" } },
			},
			actions = {
				{ set = { var = "type", value = 2580 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 150 } },
				{ say = "Do you want to buy a fishing rod for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 67,
			when = {
				{ words = { "present" } },
			},
			actions = {
				{ set = { var = "type", value = 1990 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 10 } },
				{ say = "Do you want to buy a present for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 68,
			when = {
				{ words = { "oil" } },
			},
			actions = {
				{ set = { var = "type", value = 2006 } },
				{ set = { var = "data", value = 7 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 20 } },
				{ say = "Do you want to buy oil for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 69,
			when = {
				{ words = { "waterskin" } },
			},
			actions = {
				{ set = { var = "type", value = 2031 } },
				{ set = { var = "data", value = 1 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 10 } },
				{ say = "Do you want to buy a waterskin for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 70,
			when = {
				{ words = { "cup" } },
			},
			actions = {
				{ set = { var = "type", value = 2013 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 2 } },
				{ say = "Do you want to buy a cup for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 71,
			when = {
				{ words = { "plate" } },
			},
			actions = {
				{ set = { var = "type", value = 2035 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 6 } },
				{ say = "Do you want to buy a plate for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 72,
			when = {
				{ words = { "bucket" } },
			},
			actions = {
				{ set = { var = "type", value = 2005 } },
				{ set = { var = "data", value = 0 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 4 } },
				{ say = "Do you want to buy a bucket for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 73,
			when = {
				{ words = { "bottle" } },
			},
			actions = {
				{ set = { var = "type", value = 2007 } },
				{ set = { var = "data", value = 0 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 3 } },
				{ say = "Do you want to buy a bottle for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 75,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "torch" } },
			},
			actions = {
				{ set = { var = "type", value = 2050 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 2, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A torches for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 76,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "candelab" } },
			},
			actions = {
				{ set = { var = "type", value = 2041 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 8, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A candelabra for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 77,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "bag" } },
			},
			actions = {
				{ set = { var = "type", value = 1991 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 4, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A bags for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 78,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "scroll" } },
			},
			actions = {
				{ set = { var = "type", value = 1949 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 5, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A scrolls for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 79,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "document" } },
			},
			actions = {
				{ set = { var = "type", value = 1968 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 12, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A documents for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 80,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "parchment" } },
			},
			actions = {
				{ set = { var = "type", value = 1969 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 8, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A parchments for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 81,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "shovel" } },
			},
			actions = {
				{ set = { var = "type", value = 2554 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 50, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A shovels for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 82,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "backpack" } },
			},
			actions = {
				{ set = { var = "type", value = 1998 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 20, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A backpacks for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 83,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "scythe" } },
			},
			actions = {
				{ set = { var = "type", value = 2550 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 50, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A scythes for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 84,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "pick" } },
			},
			actions = {
				{ set = { var = "type", value = 2553 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 50, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A picks for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 85,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "watch" } },
			},
			actions = {
				{ set = { var = "type", value = 2036 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 20, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A of my high quality watches for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 86,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "rope" } },
			},
			actions = {
				{ set = { var = "type", value = 2120 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 50, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A ropes for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 87,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "rod" } },
			},
			actions = {
				{ set = { var = "type", value = 2580 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 150, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A fishing rods for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 88,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "present" } },
			},
			actions = {
				{ set = { var = "type", value = 1990 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 10, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A presents for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 89,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "oil" } },
			},
			actions = {
				{ set = { var = "type", value = 2006 } },
				{ set = { var = "data", value = 7 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 20, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A vials of oil for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 90,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "waterskin" } },
			},
			actions = {
				{ set = { var = "type", value = 2031 } },
				{ set = { var = "data", value = 1 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 10, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A water skins for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 91,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "cup" } },
			},
			actions = {
				{ set = { var = "type", value = 2013 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 2, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A cups for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 92,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "plate" } },
			},
			actions = {
				{ set = { var = "type", value = 2035 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 6, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A plates for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 93,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "bucket" } },
			},
			actions = {
				{ set = { var = "type", value = 2005 } },
				{ set = { var = "data", value = 0 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 4, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A buckets for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 94,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "bottle" } },
			},
			actions = {
				{ set = { var = "type", value = 2007 } },
				{ set = { var = "data", value = 0 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 3, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A bottles for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 96,
			when = {
				{ words = { "worm" } },
			},
			actions = {
				{ say = "I sell worms only in sixpacks for 5 gold each, how many sixpacks of worms do you want to buy?" },
			},
		},
		{
			line = 97,
			when = {
				{ words = { "worms" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 98,
			when = {
				{ capture = 1 },
				{ words = { "worms" } },
			},
			actions = {
				{ set = { var = "type", value = 3976 } },
				{ set = { var = "amount", value = { binary = { op = "*", lhs = { capture = 1 }, rhs = 6 } } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 5, rhs = { capture = 1 } } } } },
				{ say = "So you want to buy some of my sixpacks with altogether %A worms for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 99,
			when = {
				{ capture = 1 },
				{ words = { "six" } },
				{ words = { "pack" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 101,
			when = {
				{ words = { "sell" } },
				{ words = { "rope" } },
			},
			actions = {
				{ set = { var = "type", value = 2120 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 8 } },
				{ say = "Do you want to sell a rope for %P gold?" },
				{ set = { var = "topic", value = 3 } },
			},
		},
		{
			line = 102,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "rope" } },
			},
			actions = {
				{ set = { var = "type", value = 2120 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 8, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A ropes for %P gold?" },
				{ set = { var = "topic", value = 3 } },
			},
		},
		{
			line = 104,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
				{ expr = { countMoney = true }, op = ">=", rhs = { session = "price" } },
			},
			actions = {
				{ say = "Here it is." },
				{ deleteMoney = true },
				{ create = { item = { session = "type" }, count = 1 } },
			},
		},
		{
			line = 105,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "You don't have so much money." },
			},
		},
		{
			line = 106,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
			},
			actions = {
				{ say = "Then not." },
			},
		},
		{
			line = 108,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
				{ words = { "yes" } },
				{ expr = { countMoney = true }, op = ">=", rhs = { session = "price" } },
			},
			actions = {
				{ say = "Here it is. There is a deposit of 5 gold on the vial." },
				{ deleteMoney = true },
				{ create = { item = { session = "type" }, count = 1 } },
			},
		},
		{
			line = 109,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "You don't have so much money." },
			},
		},
		{
			line = 110,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
			},
			actions = {
				{ say = "Then not." },
			},
		},
		{
			line = 112,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 3 },
				{ words = { "yes" } },
				{ expr = { count = { session = "type" } }, op = ">=", rhs = { session = "amount" } },
			},
			actions = {
				{ say = "Ok. Here's your money." },
				{ delete = { item = { session = "type" }, count = 1 } },
				{ createMoney = true },
			},
		},
		{
			line = 113,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 3 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "Sorry, you don't have one." },
			},
		},
		{
			line = 114,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 3 },
			},
			actions = {
				{ say = "Maybe next time." },
			},
		},
		{
			line = 116,
			when = {
				{ words = { "deposit" } },
			},
			actions = {
				{ say = "I will pay you 5 gold for every empty vial. Ok?" },
				{ set = { var = "data", value = 0 } },
				{ set = { var = "topic", value = 4 } },
			},
		},
		{
			line = 117,
			when = {
				{ words = { "vial" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 118,
			when = {
				{ words = { "flask" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 120,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 4 },
				{ words = { "yes" } },
				{ expr = { count = 2006 }, op = ">", rhs = 0 },
			},
			actions = {
				{ set = { var = "amount", value = { count = 2006 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = { session = "amount" }, rhs = 5 } } } },
				{ say = "Here you are ... %P gold." },
				{ delete = { item = 2006, count = 1 } },
				{ createMoney = true },
			},
		},
		{
			line = 121,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 4 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "You don't have any empty vials." },
			},
		},
		{
			line = 122,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 4 },
			},
			actions = {
				{ say = "Hmm, but please keep Tibia litter free." },
			},
		},
		{
			line = 124,
			when = {
				{ words = { "buy" } },
			},
			actions = {
				{ say = "I have shovels, picks, scythes, bags, ropes, backpacks, plates, scrolls, watches, some lightsources, and other stuff." },
			},
		},
		{
			line = 125,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "sell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 126,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "have" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 127,
			when = {
				{ words = { "offer" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 128,
			when = {
				{ words = { "stuff" } },
			},
			actions = {
				{ say = "Water hoses, pitchforks, presents, buckets, bottles, and the like." },
			},
		},
	},
}))

npc:register()
