-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: basilisk.npc

local npc = NpcType("Basilisk")
npc:appearance({ lookType = 28, lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0 })
npc:movement({ radius = 2, speed = 5 })
npc:health(100)
npc:sex(1)
npc:race(28)

npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = {
		{
			line = 13,
			when = {
				{ situation = "address" },
				{ words = { "a" } },
				{ select = true },
			},
			actions = {
				{ effectMe = 9 },
				{ idle = true },
			},
		},
		{
			line = 14,
			when = {
				{ situation = "address" },
				{ words = { "b" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 15,
			when = {
				{ situation = "address" },
				{ words = { "c" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 16,
			when = {
				{ situation = "address" },
				{ words = { "d" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 17,
			when = {
				{ situation = "address" },
				{ words = { "e" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 19,
			when = {
				{ situation = "address" },
				{ words = { "f" } },
				{ select = true },
			},
			actions = {
				{ effectMe = 13 },
				{ idle = true },
			},
		},
		{
			line = 20,
			when = {
				{ situation = "address" },
				{ words = { "g" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 21,
			when = {
				{ situation = "address" },
				{ words = { "h" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 23,
			when = {
				{ situation = "address" },
				{ words = { "i" } },
				{ select = true },
			},
			actions = {
				{ effectMe = 14 },
				{ idle = true },
			},
		},
		{
			line = 24,
			when = {
				{ situation = "address" },
				{ words = { "j" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 25,
			when = {
				{ situation = "address" },
				{ words = { "k" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 26,
			when = {
				{ situation = "address" },
				{ words = { "l" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 27,
			when = {
				{ situation = "address" },
				{ words = { "m" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 29,
			when = {
				{ situation = "address" },
				{ words = { "n" } },
				{ select = true },
			},
			actions = {
				{ effectMe = 15 },
				{ idle = true },
			},
		},
		{
			line = 30,
			when = {
				{ situation = "address" },
				{ words = { "o" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 31,
			when = {
				{ situation = "address" },
				{ words = { "p" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 32,
			when = {
				{ situation = "address" },
				{ words = { "r" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 33,
			when = {
				{ situation = "address" },
				{ words = { "s" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 35,
			when = {
				{ situation = "address" },
				{ words = { "t" } },
				{ select = true },
			},
			actions = {
				{ effectMe = 17 },
				{ idle = true },
			},
		},
		{
			line = 36,
			when = {
				{ situation = "address" },
				{ words = { "u" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 37,
			when = {
				{ situation = "address" },
				{ words = { "v" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 38,
			when = {
				{ situation = "address" },
				{ words = { "w" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 39,
			when = {
				{ situation = "address" },
				{ words = { "y" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 41,
			when = {
				{ situation = "address" },
				{ select = true },
			},
			actions = {
				{ idle = true },
			},
		},
		{
			line = 43,
			when = {
				{ situation = "busy" },
				{ select = true },
			},
			actions = {
				{ nop = true },
			},
		},
		{
			line = 45,
			when = {
				{ situation = "vanish" },
				{ select = true },
			},
			actions = {
				{ nop = true },
			},
		},
	},
}))

npc:register()
