-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: brasith.npc

local npc = NpcType("Brasith")
npc:appearance({ lookType = 144, lookHead = 60, lookBody = 94, lookLegs = 58, lookFeet = 76 })
npc:movement({ radius = 1, speed = 10, goStrength = 10 })
npc:health(100)
npc:sex(1)
npc:race(62)

npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = {
		{
			line = 13,
			when = {
				{ situation = "address" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Ashari %N." },
			},
		},
		{
			line = 14,
			when = {
				{ situation = "address" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 15,
			when = {
				{ situation = "address" },
				{ words = { "Ashari$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 16,
			when = {
				{ situation = "address" },
				{ select = true },
			},
			actions = {
				{ idle = true },
			},
		},
		{
			line = 17,
			when = {
				{ situation = "busy" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Wait %N." },
				{ queue = true },
			},
		},
		{
			line = 18,
			when = {
				{ situation = "busy" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 19,
			when = {
				{ situation = "busy" },
				{ select = true },
			},
			actions = {
				{ nop = true },
			},
		},
		{
			line = 20,
			when = {
				{ situation = "vanish" },
				{ select = true },
			},
			actions = {
				{ say = "Asha Thrazi." },
			},
		},
		{
			line = 22,
			when = {
				{ words = { "bye" } },
			},
			actions = {
				{ say = "Asha Thrazi." },
				{ idle = true },
			},
		},
		{
			line = 23,
			when = {
				{ words = { "farewell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 24,
			when = {
				{ words = { "name" } },
			},
			actions = {
				{ say = "I am Brasith Seedsinger." },
			},
		},
		{
			line = 25,
			when = {
				{ words = { "job" } },
			},
			actions = {
				{ say = "You may buy all the things we grow or gather at this place." },
			},
		},
		{
			line = 26,
			when = {
				{ words = { "time" } },
			},
			actions = {
				{ say = "Sorry, I can't help you." },
			},
		},
		{
			line = 28,
			when = {
				{ words = { "carlin" } },
			},
			actions = {
				{ say = "The humans of Carlin at least ry to live in harmony with nature." },
			},
		},
		{
			line = 29,
			when = {
				{ words = { "thais" } },
			},
			actions = {
				{ say = "I heared only terrible storys about that city." },
			},
		},
		{
			line = 30,
			when = {
				{ words = { "venore" } },
			},
			actions = {
				{ say = "Their traders seem suspiciously freindly. I don't trust them." },
			},
		},
		{
			line = 31,
			when = {
				{ words = { "roderick" } },
			},
			actions = {
				{ say = "His house is an impurity in our city in unity with nature." },
			},
		},
		{
			line = 32,
			when = {
				{ words = { "olrik" } },
			},
			actions = {
				{ say = "This poor humans seems to think he might become one of us by spendig time with us." },
			},
		},
		{
			line = 34,
			when = {
				{ words = { "elf" } },
			},
			actions = {
				{ say = "Our race lacks unity, which is a very sad thing. And the differences we have will grow and grow until eventually there is no race left." },
			},
		},
		{
			line = 35,
			when = {
				{ words = { "elves" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 36,
			when = {
				{ words = { "dwarf" } },
			},
			actions = {
				{ say = "They work the earth and claim knowledge about it, but they know only about minerals, not about the life it stands for." },
			},
		},
		{
			line = 37,
			when = {
				{ words = { "human" } },
			},
			actions = {
				{ say = "They are so many, so planless, so divided. They have choosen a path I do not want for my own race" },
			},
		},
		{
			line = 38,
			when = {
				{ words = { "troll" } },
			},
			actions = {
				{ say = "I don't claim to understand this creatures but sometimes they are more close to the roots than we are." },
			},
		},
		{
			line = 39,
			when = {
				{ words = { "cenath" } },
			},
			actions = {
				{ say = "The Cenath forgot as many as they learned. I doubt they find the wisdom they are looking for without the things they neglected in their pursuit of knowledge." },
			},
		},
		{
			line = 40,
			when = {
				{ words = { "kuridai" } },
			},
			actions = {
				{ say = "The Kuridai left the true path and can't see their error. Their way of living may have been suitable in the past, but if they don't come back to us, their path will lead into darkness." },
			},
		},
		{
			line = 41,
			when = {
				{ words = { "deraisim" } },
			},
			actions = {
				{ say = "We have still much to learn but we are on the correct path at least." },
			},
		},
		{
			line = 42,
			when = {
				{ words = { "abdaisim" } },
			},
			actions = {
				{ say = "The Abdaisim are true to the ways of our race, maybe even more close than we. But by abandoning the other elves they harm themselves more than they know." },
			},
		},
		{
			line = 43,
			when = {
				{ words = { "teshial" } },
			},
			actions = {
				{ say = "They are lost, and if they still exist they are alone in the cold and the darkness." },
			},
		},
		{
			line = 44,
			when = {
				{ words = { "ferumbras" } },
			},
			actions = {
				{ say = "He thinks that he is incredibly powerful, but his is only the mindless power of destruction." },
			},
		},
		{
			line = 45,
			when = {
				{ words = { "crunor" } },
			},
			actions = {
				{ say = "We abandoned the gods a long time ago. A short time after they abandoned us." },
			},
		},
		{
			line = 46,
			when = {
				{ words = { "plant" } },
			},
			actions = {
				{ say = "Life takes many forms. Plants are a very basic form of life. Its simplicity makes them close to the core of nature." },
			},
		},
		{
			line = 47,
			when = {
				{ words = { "tree" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 48,
			when = {
				{ words = { "forest" } },
			},
			actions = {
				{ say = "The beauty of a forest is something easy to be missed by the unobservant." },
			},
		},
		{
			line = 49,
			when = {
				{ words = { "field" } },
			},
			actions = {
				{ say = "With the growth of a community comes the need to 'use' nature rather then to 'flow' with nature. This is sad but necessary." },
			},
		},
		{
			line = 51,
			when = {
				{ words = { "offer" } },
			},
			actions = {
				{ say = "I sell corncobs, cherries, grapes, melons, pumpkins, bananas, strawberries, and carrots." },
			},
		},
		{
			line = 52,
			when = {
				{ words = { "goods" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 53,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "sell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 54,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "have" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 55,
			when = {
				{ words = { "food" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 57,
			when = {
				{ words = { "corncob" } },
			},
			actions = {
				{ set = { var = "type", value = 2686 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 3 } },
				{ say = "Do you want to buy a corncob for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 58,
			when = {
				{ words = { "cherry" } },
			},
			actions = {
				{ set = { var = "type", value = 2679 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 1 } },
				{ say = "Do you want to buy a cherry for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 59,
			when = {
				{ words = { "grapes" } },
			},
			actions = {
				{ set = { var = "type", value = 2681 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 3 } },
				{ say = "Do you want to buy grapes for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 60,
			when = {
				{ words = { "melon" } },
			},
			actions = {
				{ set = { var = "type", value = 2682 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 8 } },
				{ say = "Do you want to buy a melon for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 61,
			when = {
				{ words = { "banana" } },
			},
			actions = {
				{ set = { var = "type", value = 2676 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 2 } },
				{ say = "Do you want to buy a banana for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 62,
			when = {
				{ words = { "strawberry" } },
			},
			actions = {
				{ set = { var = "type", value = 2680 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 1 } },
				{ say = "Do you want to buy a strawberry for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 63,
			when = {
				{ words = { "carrot" } },
			},
			actions = {
				{ set = { var = "type", value = 2684 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 3 } },
				{ say = "Do you want to buy a carrot for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 64,
			when = {
				{ words = { "pumpkin" } },
			},
			actions = {
				{ set = { var = "type", value = 2683 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 10 } },
				{ say = "Do you want to buy a pumpkin for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 66,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "corncob" } },
			},
			actions = {
				{ set = { var = "type", value = 2686 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 3, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A corncobs for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 67,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "cherr" } },
			},
			actions = {
				{ set = { var = "type", value = 2679 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 1, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A cherries for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 68,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "grapes" } },
			},
			actions = {
				{ set = { var = "type", value = 2681 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 3, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A grapes for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 69,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "melon" } },
			},
			actions = {
				{ set = { var = "type", value = 2682 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 8, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A melons for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 70,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "banana" } },
			},
			actions = {
				{ set = { var = "type", value = 2676 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 2, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A bananas for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 71,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "strawberries" } },
			},
			actions = {
				{ set = { var = "type", value = 2680 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 1, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A strawberries for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 72,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "carrot" } },
			},
			actions = {
				{ set = { var = "type", value = 2684 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 3, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A carrots for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 73,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "pumpkin" } },
			},
			actions = {
				{ set = { var = "type", value = 2683 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 10, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A pumpkins for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 75,
			when = {
				{ words = { "bugmilk" } },
			},
			actions = {
				{ set = { var = "type", value = 2007 } },
				{ set = { var = "data", value = 9 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 15 } },
				{ say = "Do you want to buy a bottle of bugmilk for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 77,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
				{ expr = { countMoney = true }, op = ">=", rhs = { session = "price" } },
			},
			actions = {
				{ say = "Thank you. Here it is." },
				{ deleteMoney = true },
				{ create = { item = { session = "type" }, count = 1 } },
			},
		},
		{
			line = 78,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "Sorry, you do not have enough gold." },
			},
		},
		{
			line = 79,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
			},
			actions = {
				{ say = "Maybe you will buy it another time." },
			},
		},
	},
}))

npc:register()
