-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: cobra.npc

local npc = NpcType("Cobra")
npc:appearance({ lookType = 0, lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0 })
npc:movement({ radius = 0, speed = 1, goStrength = 0 })
npc:health(100)
npc:sex(1)
npc:race(1)

npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = {
		{
			line = 13,
			when = {
				{ situation = "address" },
				{ words = { "hello$" } },
				{ expr = { questValue = 270 }, op = ">", rhs = 0 },
				{ expr = { poison = true }, op = ">", rhs = 500 },
				{ select = true },
			},
			actions = {
				{ say = "Venture the path of decay!" },
				{ teleport = { x = 33397, y = 32836, z = 14 } },
				{ effectOpp = 11 },
				{ setQuestValue = { id = 270, value = 0 } },
			},
		},
		{
			line = 14,
			when = {
				{ situation = "address" },
				{ words = { "hi$" } },
				{ expr = { questValue = 270 }, op = ">", rhs = 0 },
				{ expr = { poison = true }, op = ">", rhs = 500 },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 16,
			when = {
				{ situation = "address" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Begone! Hissssss! You bear not the mark of the cobra!" },
				{ idle = true },
			},
		},
		{
			line = 17,
			when = {
				{ situation = "address" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 18,
			when = {
				{ situation = "address" },
				{ select = true },
			},
			actions = {
				{ idle = true },
			},
		},
		{
			line = 19,
			when = {
				{ situation = "busy" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Sssssilence!" },
				{ queue = true },
			},
		},
		{
			line = 20,
			when = {
				{ situation = "busy" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 21,
			when = {
				{ situation = "busy" },
				{ select = true },
			},
			actions = {
				{ nop = true },
			},
		},
		{
			line = 22,
			when = {
				{ situation = "vanish" },
				{ select = true },
			},
			actions = {
				{ say = "Hissssssssss." },
			},
		},
	},
}))

npc:register()
