-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: digger.npc

local npc = NpcType("Digger")
npc:appearance({ lookType = 9, lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0 })
npc:movement({ radius = 1, speed = 10, goStrength = 10 })
npc:health(100)
npc:sex(1)
npc:race(1)

npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = {
		{
			line = 13,
			when = {
				{ situation = "address" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Oh, %N is that you? You look inconveniently healthy." },
			},
		},
		{
			line = 14,
			when = {
				{ situation = "address" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 15,
			when = {
				{ situation = "address" },
				{ select = true },
			},
			actions = {
				{ idle = true },
			},
		},
		{
			line = 16,
			when = {
				{ situation = "busy" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Wait %N, your time will finally come." },
				{ queue = true },
			},
		},
		{
			line = 17,
			when = {
				{ situation = "busy" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 18,
			when = {
				{ situation = "busy" },
				{ select = true },
			},
			actions = {
				{ nop = true },
			},
		},
		{
			line = 19,
			when = {
				{ situation = "vanish" },
				{ select = true },
			},
			actions = {
				{ say = "Bye." },
			},
		},
		{
			line = 21,
			when = {
				{ words = { "bye" } },
			},
			actions = {
				{ say = "Bye." },
				{ idle = true },
			},
		},
		{
			line = 22,
			when = {
				{ words = { "farewell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 23,
			when = {
				{ words = { "name" } },
			},
			actions = {
				{ say = "They call me Digger, that fine with me." },
			},
		},
		{
			line = 24,
			when = {
				{ words = { "frans" } },
			},
			actions = {
				{ say = "I think the FRANS is bugged." },
			},
		},
		{
			line = 25,
			when = {
				{ words = { "digger" } },
			},
			actions = {
				{ say = "So what?" },
			},
		},
		{
			line = 26,
			when = {
				{ words = { "job" } },
			},
			actions = {
				{ say = "I am selling some potions." },
			},
		},
		{
			line = 27,
			when = {
				{ words = { "sorcerer" } },
			},
			actions = {
				{ say = "The way of the magicwielder is the only way to true power." },
			},
		},
		{
			line = 28,
			when = {
				{ words = { "druid" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 29,
			when = {
				{ words = { "magic" } },
			},
			actions = {
				{ say = "This is the magic market. Just have a look around." },
			},
		},
		{
			line = 30,
			when = {
				{ words = { "market" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 31,
			when = {
				{ words = { "vladruc" } },
			},
			actions = {
				{ say = "Better don't cross the master!" },
			},
		},
		{
			line = 32,
			when = {
				{ words = { "urghain" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 33,
			when = {
				{ words = { "ferumbras" } },
			},
			actions = {
				{ say = "An upstart of minor skills and great ambitions." },
			},
		},
		{
			line = 34,
			when = {
				{ words = { "excalibug" } },
			},
			actions = {
				{ say = "Just a knights' legend." },
			},
		},
		{
			line = 36,
			when = {
				{ words = { "offer" } },
			},
			actions = {
				{ say = "You may be interested in my life and mana fluids." },
			},
		},
		{
			line = 37,
			when = {
				{ words = { "goods" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 38,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "sell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 39,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "have" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 40,
			when = {
				{ words = { "potion" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 42,
			when = {
				{ words = { "life" } },
				{ words = { "fluid" } },
			},
			actions = {
				{ set = { var = "type", value = 2874 } },
				{ set = { var = "data", value = 11 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 60 } },
				{ say = "Do you want to buy life fluid for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 43,
			when = {
				{ words = { "mana" } },
				{ words = { "fluid" } },
			},
			actions = {
				{ set = { var = "type", value = 2874 } },
				{ set = { var = "data", value = 10 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 55 } },
				{ say = "Do you want to buy mana fluid for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 44,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "life" } },
				{ words = { "fluid" } },
			},
			actions = {
				{ set = { var = "type", value = 2874 } },
				{ set = { var = "data", value = 11 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 60, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A potions of life fluid for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 45,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "mana" } },
				{ words = { "fluid" } },
			},
			actions = {
				{ set = { var = "type", value = 2874 } },
				{ set = { var = "data", value = 10 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 55, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A potions of mana fluid for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 47,
			when = {
				{ words = { "deposit" } },
			},
			actions = {
				{ say = "I will pay you 5 gold for every empty vial. Ok?" },
				{ set = { var = "data", value = 0 } },
				{ set = { var = "topic", value = 3 } },
			},
		},
		{
			line = 48,
			when = {
				{ words = { "vial" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 49,
			when = {
				{ words = { "flask" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 51,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
				{ words = { "yes" } },
				{ expr = { countMoney = true }, op = ">=", rhs = { session = "price" } },
			},
			actions = {
				{ say = "Here you are. There is a deposit of 5 gold on the vial." },
				{ deleteMoney = true },
				{ create = { item = { session = "type" }, count = 1 } },
			},
		},
		{
			line = 52,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
			},
			actions = {
				{ say = "Don't overestimate my patience." },
			},
		},
		{
			line = 54,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 3 },
				{ words = { "yes" } },
				{ expr = { count = 2874 }, op = ">", rhs = 0 },
			},
			actions = {
				{ set = { var = "amount", value = { count = 2874 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = { session = "amount" }, rhs = 5 } } } },
				{ say = "Here you are ... %P gold." },
				{ delete = { item = 2874, count = 1 } },
				{ createMoney = true },
			},
		},
		{
			line = 55,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 3 },
			},
			actions = {
				{ say = "Don't overestimate my patience." },
			},
		},
	},
}))

npc:register()
