-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: ebenizer.npc

local npc = NpcType("Ebenizer")
npc:appearance({ lookType = 128, lookHead = 59, lookBody = 95, lookLegs = 87, lookFeet = 76 })
npc:movement({ radius = 1, speed = 10 })
npc:health(100)
npc:sex(1)
npc:race(1)

local rules = {}
NpcAppendRules(rules, {
	{
		line = 13,
		when = {
			{ situation = "address" },
			{ words = { "hello$" } },
			{ select = true },
		},
		actions = {
			{ say = "Yes? What may I do for you, %N?" },
		},
	},
	{
		line = 14,
		when = {
			{ situation = "address" },
			{ words = { "hi$" } },
			{ select = true },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 15,
		when = {
			{ situation = "address" },
			{ select = true },
		},
		actions = {
			{ idle = true },
		},
	},
	{
		line = 16,
		when = {
			{ situation = "busy" },
			{ words = { "hello$" } },
			{ select = true },
		},
		actions = {
			{ say = "It's not your turn %N. Wait please." },
			{ queue = true },
		},
	},
	{
		line = 17,
		when = {
			{ situation = "busy" },
			{ words = { "hi$" } },
			{ select = true },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 18,
		when = {
			{ situation = "busy" },
			{ select = true },
		},
		actions = {
			{ nop = true },
		},
	},
	{
		line = 19,
		when = {
			{ situation = "vanish" },
			{ select = true },
		},
		actions = {
			{ say = "Have a nice day." },
		},
	},
	{
		line = 21,
		when = {
			{ words = { "bye" } },
		},
		actions = {
			{ say = "Have a nice day." },
			{ idle = true },
		},
	},
	{
		line = 22,
		when = {
			{ words = { "farewell" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 23,
		when = {
			{ words = { "name" } },
		},
		actions = {
			{ say = "My name? Ebenizer!" },
		},
	},
	{
		line = 24,
		when = {
			{ words = { "job" } },
		},
		actions = {
			{ say = "I am running this Bank" },
		},
	},
	{
		line = 25,
		when = {
			{ words = { "time" } },
		},
		actions = {
			{ say = "It is %T, precisely." },
		},
	},
	{
		line = 26,
		when = {
			{ words = { "king" } },
		},
		actions = {
			{ say = "Hail to the king!" },
		},
	},
	{
		line = 27,
		when = {
			{ words = { "tibianus" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 28,
		when = {
			{ words = { "army" } },
		},
		actions = {
			{ say = "Soldiers have not that much money that I would care about." },
		},
	},
	{
		line = 29,
		when = {
			{ words = { "ferumbras" } },
		},
		actions = {
			{ say = "A true threat to wealth and trade." },
		},
	},
	{
		line = 30,
		when = {
			{ words = { "excalibug" } },
		},
		actions = {
			{ say = "This weapon, if real, might be worth a lot." },
		},
	},
	{
		line = 31,
		when = {
			{ words = { "thais" } },
		},
		actions = {
			{ say = "We are in constant contact with the city of Thais." },
		},
	},
	{
		line = 32,
		when = {
			{ words = { "tibia" } },
		},
		actions = {
			{ say = "There are countless ways of profit in this world." },
		},
	},
	{
		line = 33,
		when = {
			{ words = { "carlin" } },
		},
		actions = {
			{ say = "It's underdeveloped and economically insignificant." },
		},
	},
	{
		line = 34,
		when = {
			{ words = { "edron" } },
		},
		actions = {
			{ say = "The riches of our isle are its mineral resources." },
		},
	},
	{
		line = 35,
		when = {
			{ words = { "news" } },
		},
		actions = {
			{ say = "I only care about financial news." },
		},
	},
	{
		line = 36,
		when = {
			{ words = { "rumors" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
})
NpcAppendRules(rules, NpcCatalogs["gen-bank"])
npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = rules,
}))

npc:register()
