-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: edala.npc

local npc = NpcType("Edala")
npc:appearance({ lookType = 63, lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0 })
npc:movement({ radius = 3, speed = 10 })
npc:health(100)
npc:sex(0)
npc:race(62)

npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = {
		{
			line = 13,
			when = {
				{ situation = "address" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Ashari, %N." },
			},
		},
		{
			line = 14,
			when = {
				{ situation = "address" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 15,
			when = {
				{ situation = "address" },
				{ words = { "ashari$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 16,
			when = {
				{ situation = "address" },
				{ select = true },
			},
			actions = {
				{ idle = true },
			},
		},
		{
			line = 17,
			when = {
				{ situation = "busy" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Sorry, please wait a moment %N." },
				{ queue = true },
			},
		},
		{
			line = 18,
			when = {
				{ situation = "busy" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 19,
			when = {
				{ situation = "busy" },
				{ words = { "ashari$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 20,
			when = {
				{ situation = "busy" },
				{ select = true },
			},
			actions = {
				{ nop = true },
			},
		},
		{
			line = 21,
			when = {
				{ situation = "vanish" },
				{ select = true },
			},
			actions = {
				{ say = "Asha Thrazi, traveller." },
			},
		},
		{
			line = 23,
			when = {
				{ words = { "bye" } },
			},
			actions = {
				{ say = "Asha Thrazi, traveller." },
				{ idle = true },
			},
		},
		{
			line = 24,
			when = {
				{ words = { "asha" } },
				{ words = { "thrazi" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 25,
			when = {
				{ words = { "farewell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 26,
			when = {
				{ words = { "job" } },
			},
			actions = {
				{ say = "I am a mystic of the suns. I provide protective blessings for those in need." },
			},
		},
		{
			line = 27,
			when = {
				{ words = { "name" } },
			},
			actions = {
				{ say = "My name is Edala, pilgrim." },
			},
		},
		{
			line = 29,
			when = {
				{ words = { "mystic" } },
			},
			actions = {
				{ say = "We mystics are philosophers and healers." },
			},
		},
		{
			line = 32,
			when = {
				{ words = { "cenath" } },
			},
			actions = {
				{ say = "I don't consider me a member of any caste, and I don't want to talk about this matter." },
			},
		},
		{
			line = 33,
			when = {
				{ words = { "kuridai" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 34,
			when = {
				{ words = { "deraisim" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 35,
			when = {
				{ words = { "abdaisim" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 36,
			when = {
				{ words = { "teshial" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 38,
			when = {
				{ words = { "crunor" } },
			},
			actions = {
				{ say = "Crunor is great in his beauty." },
			},
		},
		{
			line = 39,
			when = {
				{ words = { "priyla" } },
			},
			actions = {
				{ say = "The daughter of the stars is my patron." },
			},
		},
		{
			line = 41,
			when = {
				{ words = { "excalibug" } },
			},
			actions = {
				{ say = "It is true that this weapon brings great power. But you should not look for power. It is wisdom you really need." },
			},
		},
		{
			line = 42,
			when = {
				{ words = { "news" } },
			},
			actions = {
				{ say = "News? I don't care about news." },
			},
		},
		{
			line = 44,
			when = {
				{ words = { "heal$" } },
				{ expr = { burning = true }, op = ">", rhs = 0 },
			},
			actions = {
				{ say = "You are burning. I will help you." },
				{ burning = { cycles = 0, param = 0 } },
				{ effectOpp = 15 },
			},
		},
		{
			line = 45,
			when = {
				{ words = { "heal$" } },
				{ expr = { poison = true }, op = ">", rhs = 0 },
			},
			actions = {
				{ say = "You are poisoned. I will help you." },
				{ poison = { cycles = 0, param = 0 } },
				{ effectOpp = 14 },
			},
		},
		{
			line = 46,
			when = {
				{ words = { "heal$" } },
				{ expr = { hp = true }, op = "<", rhs = 40 },
			},
			actions = {
				{ say = "You are looking really bad. Let me heal your wounds." },
				{ hp = 40 },
				{ effectOpp = 13 },
			},
		},
		{
			line = 48,
			when = {
				{ words = { "heal$" } },
				{ property = "pvpenforced" },
			},
			actions = {
				{ say = "You aren't looking that bad." },
			},
		},
		{
			line = 49,
			when = {
				{ words = { "heal$" } },
			},
			actions = {
				{ say = "You aren't looking that bad. Sorry, I can't help you. But if you are looking for additional protection you should go on the pilgrimage of ashes." },
			},
		},
		{
			line = 51,
			when = {
				{ words = { "blessing" } },
				{ property = "pvpenforced" },
				{ select = true },
			},
			actions = {
				{ say = "The lifeforce of this world is waning. There are no more blessings avaliable on this world." },
			},
		},
		{
			line = 52,
			when = {
				{ words = { "pilgrimage" } },
				{ property = "pvpenforced" },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 53,
			when = {
				{ words = { "ashes" } },
				{ property = "pvpenforced" },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 55,
			when = {
				{ words = { "spiritual" } },
				{ property = "pvpenforced" },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 56,
			when = {
				{ words = { "shielding" } },
				{ property = "pvpenforced" },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 57,
			when = {
				{ words = { "sacred" } },
				{ words = { "places" } },
				{ property = "pvpenforced" },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 58,
			when = {
				{ words = { "spark" } },
				{ property = "pvpenforced" },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 59,
			when = {
				{ words = { "phoenix" } },
				{ property = "pvpenforced" },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 60,
			when = {
				{ words = { "embrace" } },
				{ property = "pvpenforced" },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 61,
			when = {
				{ words = { "fire" } },
				{ property = "pvpenforced" },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 62,
			when = {
				{ words = { "suns" } },
				{ property = "pvpenforced" },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 63,
			when = {
				{ words = { "wisdom" } },
				{ property = "pvpenforced" },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 64,
			when = {
				{ words = { "solitude" } },
				{ property = "pvpenforced" },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 67,
			when = {
				{ words = { "pilgrimage" } },
			},
			actions = {
				{ say = "Whenever you receive a lethal wound your lifeforce is damaged. With every single of the five blessings you have this damage will be reduced." },
			},
		},
		{
			line = 68,
			when = {
				{ words = { "ashes" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 69,
			when = {
				{ words = { "blessing" } },
			},
			actions = {
				{ say = "There are five different blessings available in five sacred places. These blessings are: the spiritual shielding, the spark of the phoenix, the embrace of tibia, the fire of the suns and the wisdom of solitude." },
			},
		},
		{
			line = 70,
			when = {
				{ words = { "sacred" } },
				{ words = { "places" } },
			},
			actions = {
				{ say = "Just ask my about the blessing you are interested in." },
			},
		},
		{
			line = 71,
			when = {
				{ words = { "spiritual" } },
			},
			actions = {
				{ say = " You may receive the spiritual shielding in the whiteflowertemple south of Thais." },
			},
		},
		{
			line = 72,
			when = {
				{ words = { "shielding" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 73,
			when = {
				{ words = { "spark" } },
			},
			actions = {
				{ say = "The spark of the phoenix will be given to you by the dwarven priests of earth and fire in Kazordoon." },
			},
		},
		{
			line = 74,
			when = {
				{ words = { "phoenix" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 75,
			when = {
				{ words = { "embrace" } },
			},
			actions = {
				{ say = "The druids north of Carlin will provide you with the embrace of tibia." },
			},
		},
		{
			line = 77,
			when = {
				{ words = { "fire" } },
			},
			actions = {
				{ say = "Do you wish to receive the blessing of the two suns? It will cost you 10.000 gold, pilgrim." },
				{ set = { var = "price", value = 10000 } },
				{ set = { var = "topic", value = 5 } },
			},
		},
		{
			line = 78,
			when = {
				{ words = { "suns" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 79,
			when = {
				{ words = { "wisdom" } },
			},
			actions = {
				{ say = "Talk to the hermit Eremo on the isle of Cormaya about this blessing." },
			},
		},
		{
			line = 80,
			when = {
				{ words = { "solitude" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 82,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 5 },
				{ words = { "yes" } },
				{ expr = { questValue = 103 }, op = ">", rhs = 0 },
				{ select = true },
			},
			actions = {
				{ say = "You already possess this blessing." },
			},
		},
		{
			line = 83,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 5 },
				{ words = { "yes" } },
				{ expr = { countMoney = true }, op = "<", rhs = { session = "price" } },
				{ select = true },
			},
			actions = {
				{ say = "Oh. You do not have enough money." },
			},
		},
		{
			line = 84,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 5 },
				{ words = { "yes" } },
				{ select = true },
			},
			actions = {
				{ say = "Kneel down and receive the warmth of sunfire, pilgrim." },
				{ deleteMoney = true },
				{ effectOpp = 13 },
				{ setQuestValue = { id = 103, value = 3 } },
			},
		},
		{
			line = 85,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 5 },
				{ select = true },
			},
			actions = {
				{ say = "All right. As you wish." },
			},
		},
	},
}))

npc:register()
