-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: elvith.npc

local npc = NpcType("Elvith")
npc:appearance({ lookType = 144, lookHead = 76, lookBody = 3, lookLegs = 0, lookFeet = 76 })
npc:movement({ radius = 1, speed = 10, goStrength = 10 })
npc:health(100)
npc:sex(1)
npc:race(62)

npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = {
		{
			line = 13,
			when = {
				{ situation = "address" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Ashari %N." },
			},
		},
		{
			line = 14,
			when = {
				{ situation = "address" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 15,
			when = {
				{ situation = "address" },
				{ words = { "Ashari$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 16,
			when = {
				{ situation = "address" },
				{ select = true },
			},
			actions = {
				{ idle = true },
			},
		},
		{
			line = 17,
			when = {
				{ situation = "busy" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Wait %N." },
				{ queue = true },
			},
		},
		{
			line = 18,
			when = {
				{ situation = "busy" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 19,
			when = {
				{ situation = "busy" },
				{ select = true },
			},
			actions = {
				{ nop = true },
			},
		},
		{
			line = 20,
			when = {
				{ situation = "vanish" },
				{ select = true },
			},
			actions = {
				{ say = "Asha Thrazi." },
			},
		},
		{
			line = 22,
			when = {
				{ words = { "bye" } },
			},
			actions = {
				{ say = "Asha Thrazi." },
				{ idle = true },
			},
		},
		{
			line = 23,
			when = {
				{ words = { "farewell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 24,
			when = {
				{ words = { "name" } },
			},
			actions = {
				{ say = "I am Elvith Rollingstone." },
			},
		},
		{
			line = 25,
			when = {
				{ words = { "job" } },
			},
			actions = {
				{ say = "I sell musical instruments of many kinds." },
			},
		},
		{
			line = 26,
			when = {
				{ words = { "time" } },
			},
			actions = {
				{ say = "Time has its own song. Close your eyes and listen to the symphony of the seasons." },
			},
		},
		{
			line = 28,
			when = {
				{ words = { "carlin" } },
			},
			actions = {
				{ say = "Carlin is a city that thrives for a harmony it can never achive." },
			},
		},
		{
			line = 29,
			when = {
				{ words = { "thais" } },
			},
			actions = {
				{ say = "I heared about Thais and id did not sound like a place I'd want to visit." },
			},
		},
		{
			line = 30,
			when = {
				{ words = { "venore" } },
			},
			actions = {
				{ say = "By all what I heared this city is not only built into a swamp but its a swamp of intrigue and corruption itself." },
			},
		},
		{
			line = 31,
			when = {
				{ words = { "roderick" } },
			},
			actions = {
				{ say = "This man trys too hard not to offend someone." },
			},
		},
		{
			line = 32,
			when = {
				{ words = { "olrik" } },
			},
			actions = {
				{ say = "He appreciates my music and allthough he is loud and clumsy as all humans it seems not everything is lost." },
			},
		},
		{
			line = 34,
			when = {
				{ words = { "music" } },
			},
			actions = {
				{ say = "Music is an attempt to condensate emotions in harmonies and save them for the times to come." },
			},
		},
		{
			line = 35,
			when = {
				{ words = { "harmonies" } },
			},
			actions = {
				{ say = "Everything is a song. Life, death, history ... everything. To listen to the song of something is the first step to understand it." },
			},
		},
		{
			line = 36,
			when = {
				{ words = { "melodies" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 37,
			when = {
				{ words = { "harmony" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 38,
			when = {
				{ words = { "melody" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 39,
			when = {
				{ words = { "song" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 40,
			when = {
				{ words = { "sing" } },
			},
			actions = {
				{ say = "Sorry, but there is a melody in my heart that wants to be born. I would loose it before by singing right now." },
			},
		},
		{
			line = 41,
			when = {
				{ words = { "elf" } },
			},
			actions = {
				{ say = "We are the most graceful of all races. We feel the music of the universe in our hearts and souls." },
			},
		},
		{
			line = 42,
			when = {
				{ words = { "elves" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 43,
			when = {
				{ words = { "dwarf" } },
			},
			actions = {
				{ say = "They could at least use their picks and hammers with more rythm." },
			},
		},
		{
			line = 44,
			when = {
				{ words = { "human" } },
			},
			actions = {
				{ say = "They are too loud and don't even understand the concept of a melody." },
			},
		},
		{
			line = 45,
			when = {
				{ words = { "troll" } },
			},
			actions = {
				{ say = "I went down to the mines and tried to lighten up their spirit, the foolish creatures did not listen to my songs, though." },
			},
		},
		{
			line = 46,
			when = {
				{ words = { "cenath" } },
			},
			actions = {
				{ say = "The Cenath think they know the 'art' but the only true art is the music." },
			},
		},
		{
			line = 47,
			when = {
				{ words = { "kuridai" } },
			},
			actions = {
				{ say = "They could dig some halls for a big musical event, but they won't listen to me about that matter." },
			},
		},
		{
			line = 48,
			when = {
				{ words = { "deraisim" } },
			},
			actions = {
				{ say = "The other deraisim are too much concerned with mastering the nature so they don't listen to its music anymore." },
			},
		},
		{
			line = 49,
			when = {
				{ words = { "abdaisim" } },
			},
			actions = {
				{ say = "The wanderers have no patience. You need patience and passion to create and to enjoy music." },
			},
		},
		{
			line = 50,
			when = {
				{ words = { "teshial" } },
			},
			actions = {
				{ say = "I bet they were great musicians." },
			},
		},
		{
			line = 51,
			when = {
				{ words = { "ferumbras" } },
			},
			actions = {
				{ say = "Only humans made songs about him and his evil deeds." },
			},
		},
		{
			line = 52,
			when = {
				{ words = { "crunor" } },
			},
			actions = {
				{ say = "That is some god the humans worship. Our pople are not interested in this gods anymore." },
			},
		},
		{
			line = 53,
			when = {
				{ words = { "excalibug" } },
			},
			actions = {
				{ say = "There are too many songs about that weapon to retell them all. Most of them are human and therefore quite crude anyways." },
			},
		},
		{
			line = 54,
			when = {
				{ words = { "spell" } },
			},
			actions = {
				{ say = "Sorry, I don't feel like teaching magic today." },
			},
		},
		{
			line = 55,
			when = {
				{ words = { "magic" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 57,
			when = {
				{ words = { "elven" } },
				{ words = { "poetry" } },
				{ expr = { questValue = 311 }, op = "=", rhs = 1 },
				{ expr = { questValue = 312 }, op = "=", rhs = 0 },
			},
			actions = {
				{ say = "The last issue I had was bought by Randor Swiftfinger. He was banished through the hellgate and probably took the book with him ..." },
				{ say = "I would not recommend to seek him or the book there but of course its possible." },
			},
		},
		{
			line = 58,
			when = {
				{ words = { "song" } },
				{ words = { "forest" } },
				{ expr = { questValue = 311 }, op = "=", rhs = 1 },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 60,
			when = {
				{ words = { "elven" } },
				{ words = { "poetry" } },
				{ expr = { questValue = 311 }, op = "=", rhs = 1 },
				{ expr = { questValue = 312 }, op = "=", rhs = 1 },
			},
			actions = {
				{ set = { var = "type", value = 4855 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 500 } },
				{ say = "By luck I aquired another copy of the book you are looking for. Do you want to buy a copy of 'songs of the forest' for 500 gold?." },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 61,
			when = {
				{ words = { "song" } },
				{ words = { "forest" } },
				{ expr = { questValue = 311 }, op = "=", rhs = 1 },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 62,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
				{ words = { "yes" } },
				{ expr = { countMoney = true }, op = ">=", rhs = { session = "price" } },
			},
			actions = {
				{ say = "Thank you. Here it is." },
				{ deleteMoney = true },
				{ create = { item = { session = "type" }, count = 1 } },
			},
		},
		{
			line = 63,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "Sorry, you do not have enough gold." },
			},
		},
		{
			line = 64,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
			},
			actions = {
				{ say = "Maybe you will buy it another time." },
			},
		},
		{
			line = 68,
			when = {
				{ words = { "elven" } },
				{ words = { "poetry" } },
			},
			actions = {
				{ say = "Sorry, I have no issue of this book left." },
			},
		},
		{
			line = 69,
			when = {
				{ words = { "song" } },
				{ words = { "forest" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 71,
			when = {
				{ words = { "hellsgate" } },
			},
			actions = {
				{ say = "For the worst of crimes the criminals are cast into hellgate. Its said noone can return from there. Since it is not forbidden to enter hellgate you might convince Elathriel to grant you entrance." },
			},
		},
		{
			line = 72,
			when = {
				{ words = { "elathriel" } },
			},
			actions = {
				{ say = "He is a kuridai and the local Az'irel. Something like the head of the human townsguards." },
			},
		},
		{
			line = 74,
			when = {
				{ words = { "offer" } },
			},
			actions = {
				{ say = "I sell lyres, lutes, drums, and simple fanfares." },
			},
		},
		{
			line = 75,
			when = {
				{ words = { "goods" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 76,
			when = {
				{ words = { "buy" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 77,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "sell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 78,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "have" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 79,
			when = {
				{ words = { "instrument" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 81,
			when = {
				{ words = { "lyre" } },
			},
			actions = {
				{ set = { var = "type", value = 2071 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 120 } },
				{ say = "Do you want to buy a lyre for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 82,
			when = {
				{ words = { "lute" } },
			},
			actions = {
				{ set = { var = "type", value = 2072 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 195 } },
				{ say = "Do you want to buy a lute for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 83,
			when = {
				{ words = { "drum" } },
			},
			actions = {
				{ set = { var = "type", value = 2073 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 140 } },
				{ say = "Do you want to buy a drum for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 84,
			when = {
				{ words = { "simple" } },
				{ words = { "fanfare" } },
			},
			actions = {
				{ set = { var = "type", value = 2075 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 150 } },
				{ say = "Do you want to buy a simple fanfare for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 86,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "lyre" } },
			},
			actions = {
				{ set = { var = "type", value = 2071 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 120, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A lyre for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 87,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "lute" } },
			},
			actions = {
				{ set = { var = "type", value = 2072 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 195, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A lute for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 88,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "drum" } },
			},
			actions = {
				{ set = { var = "type", value = 2073 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 140, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A drum for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 89,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "simple" } },
				{ words = { "fanfare" } },
			},
			actions = {
				{ set = { var = "type", value = 2075 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 150, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A simple fanfare for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 91,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
				{ expr = { countMoney = true }, op = ">=", rhs = { session = "price" } },
			},
			actions = {
				{ say = "Thank you. Here it is." },
				{ deleteMoney = true },
				{ create = { item = { session = "type" }, count = 1 } },
			},
		},
		{
			line = 92,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "Sorry, you do not have enough gold." },
			},
		},
		{
			line = 93,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
			},
			actions = {
				{ say = "Maybe you will buy it another time." },
			},
		},
	},
}))

npc:register()
