-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: frans.npc

local npc = NpcType("Frans")
npc:appearance({ lookType = 0, lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0 })
npc:movement({ radius = 1, speed = 10 })
npc:health(100)
npc:sex(1)
npc:race(1)

local rules = {}
NpcAppendRules(rules, {
	{
		line = 13,
		when = {
			{ situation = "address" },
			{ words = { "hello$" } },
			{ select = true },
		},
		actions = {
			{ say = "Beeee Greeeeted %N. What is your neeeed?" },
		},
	},
	{
		line = 14,
		when = {
			{ situation = "address" },
			{ words = { "hi$" } },
			{ select = true },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 15,
		when = {
			{ situation = "address" },
			{ select = true },
		},
		actions = {
			{ idle = true },
		},
	},
	{
		line = 16,
		when = {
			{ situation = "busy" },
			{ words = { "hello$" } },
			{ select = true },
		},
		actions = {
			{ say = "%N, I am veeeerry busy. Unfoooortunately you will have to waiiiit." },
			{ queue = true },
		},
	},
	{
		line = 17,
		when = {
			{ situation = "busy" },
			{ words = { "hi$" } },
			{ select = true },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 18,
		when = {
			{ situation = "busy" },
			{ select = true },
		},
		actions = {
			{ nop = true },
		},
	},
	{
		line = 19,
		when = {
			{ situation = "vanish" },
			{ select = true },
		},
		actions = {
			{ say = "Bye." },
		},
	},
	{
		line = 21,
		when = {
			{ words = { "bye" } },
		},
		actions = {
			{ say = "Bye." },
			{ idle = true },
		},
	},
	{
		line = 22,
		when = {
			{ words = { "farewell" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 23,
		when = {
			{ words = { "name" } },
		},
		actions = {
			{ say = "I am a FRANS." },
		},
	},
	{
		line = 24,
		when = {
			{ words = { "frans" } },
		},
		actions = {
			{ say = "Floating ReeeeAnimated Necromantic Seeeervant ... FRANS." },
		},
	},
	{
		line = 25,
		when = {
			{ words = { "job" } },
		},
		actions = {
			{ say = "I am selliiiing ruuuunes, wands, roooods and spellbooooooks." },
		},
	},
	{
		line = 26,
		when = {
			{ words = { "sorcerer" } },
		},
		actions = {
			{ say = "Sorcerorssss, druidssss, they all come to ussss." },
		},
	},
	{
		line = 27,
		when = {
			{ words = { "druid" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 28,
		when = {
			{ words = { "magic" } },
		},
		actions = {
			{ say = "Is aaaall about magic more or lesssss, isn't it?" },
		},
	},
	{
		line = 29,
		when = {
			{ words = { "vladruc" } },
		},
		actions = {
			{ say = "Heeee is the bossss. Better don't messss with him!" },
		},
	},
	{
		line = 30,
		when = {
			{ words = { "urghain" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 31,
		when = {
			{ words = { "ferumbras" } },
		},
		actions = {
			{ say = "Wouldn't he beeee the perfect FRANS?" },
		},
	},
	{
		line = 32,
		when = {
			{ words = { "market" } },
		},
		actions = {
			{ say = "Yes, that's a market heeeere, smarty ... Nice to seeeee I am not the only one without a braiiiin here." },
		},
	},
	{
		line = 33,
		when = {
			{ words = { "excalibug" } },
		},
		actions = {
			{ say = "We FRANSes don't liiiike any bugssss." },
		},
	},
	{
		line = 36,
		when = {
			{ words = { "offer" } },
		},
		actions = {
			{ say = "What do youuuu think I am? A lousy barberrrr? I'm selliiiing ruuuunes and spellboooooks." },
		},
	},
	{
		line = 37,
		when = {
			{ words = { "goods" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 38,
		when = {
			{ words = { "do" } },
			{ words = { "you" } },
			{ words = { "sell" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 39,
		when = {
			{ words = { "do" } },
			{ words = { "you" } },
			{ words = { "have" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 41,
		when = {
			{ words = { "rune" } },
		},
		actions = {
			{ say = "I sell blank ruuuuunes and spell ruuuuunes." },
		},
	},
	{
		line = 42,
		when = {
			{ words = { "blank" } },
			{ words = { "rune" } },
		},
		actions = {
			{ set = { var = "type", value = 3147 } },
			{ set = { var = "amount", value = 1 } },
			{ set = { var = "price", value = 10 } },
			{ say = "Do youuuu want to buy a blank ruuuune for %P gold?" },
			{ set = { var = "topic", value = 1 } },
		},
	},
	{
		line = 43,
		when = {
			{ words = { "spellbook" } },
		},
		actions = {
			{ set = { var = "type", value = 3059 } },
			{ set = { var = "amount", value = 1 } },
			{ set = { var = "price", value = 150 } },
			{ say = "Do youuuu want to buy a spellboooook for %P gold?" },
			{ set = { var = "topic", value = 1 } },
		},
	},
	{
		line = 46,
		when = {
			{ capture = 1 },
			{ expr = 1, op = "<", rhs = { capture = 1 } },
			{ words = { "blank" } },
			{ words = { "rune" } },
		},
		actions = {
			{ set = { var = "type", value = 3147 } },
			{ set = { var = "amount", value = { capture = 1 } } },
			{ set = { var = "price", value = { binary = { op = "*", lhs = 10, rhs = { capture = 1 } } } } },
			{ say = "Do youuuu want to buy %A blank ruuuunes for %P gold?" },
			{ set = { var = "topic", value = 1 } },
		},
	},
	{
		line = 47,
		when = {
			{ capture = 1 },
			{ expr = 1, op = "<", rhs = { capture = 1 } },
			{ words = { "spellbook" } },
		},
		actions = {
			{ set = { var = "type", value = 3059 } },
			{ set = { var = "amount", value = { capture = 1 } } },
			{ set = { var = "price", value = { binary = { op = "*", lhs = 150, rhs = { capture = 1 } } } } },
			{ say = "Do youuuu want to buy %A spellboooooks for %P gold?" },
			{ set = { var = "topic", value = 1 } },
		},
	},
	{
		line = 49,
		when = {
			{ expr = { session = "topic" }, op = "=", rhs = 1 },
			{ words = { "yes" } },
			{ expr = { countMoney = true }, op = ">=", rhs = { session = "price" } },
		},
		actions = {
			{ say = "And here it isssss! Almost like magiiiic, isn't it?" },
			{ deleteMoney = true },
			{ create = { item = { session = "type" } } },
		},
	},
	{
		line = 50,
		when = {
			{ expr = { session = "topic" }, op = "=", rhs = 1 },
			{ words = { "yes" } },
		},
		actions = {
			{ say = "Sorry, too many buttonssss and not enough gold in your pursssse." },
		},
	},
	{
		line = 51,
		when = {
			{ expr = { session = "topic" }, op = "=", rhs = 1 },
		},
		actions = {
			{ say = "Better not annoy a FRANS if you don't want to deeeeal with him!" },
		},
	},
})
NpcAppendRules(rules, NpcCatalogs["gen-t-runes-free-s"])
NpcAppendRules(rules, NpcCatalogs["gen-t-wands-free-s"])
npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = rules,
}))

npc:register()
