-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: haroun.npc

local npc = NpcType("Haroun")
npc:appearance({ lookType = 80, lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0 })
npc:movement({ radius = 1, speed = 10 })
npc:health(100)
npc:sex(1)
npc:race(80)

npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = {
		{
			line = 14,
			when = {
				{ situation = "address" },
				{ words = { "hello$" } },
				{ expr = { questValue = 278 }, op = "=", rhs = 2 },
				{ select = true },
			},
			actions = {
				{ say = "Be greeted, human %N. How can a humble djinn be of service?" },
			},
		},
		{
			line = 15,
			when = {
				{ situation = "address" },
				{ words = { "hi$" } },
				{ expr = { questValue = 278 }, op = "=", rhs = 2 },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 16,
			when = {
				{ situation = "address" },
				{ words = { "greetings$" } },
				{ expr = { questValue = 278 }, op = "=", rhs = 2 },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 17,
			when = {
				{ situation = "address" },
				{ words = { "djanni'hah$" } },
				{ expr = { questValue = 278 }, op = "=", rhs = 2 },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 18,
			when = {
				{ situation = "address" },
				{ select = true },
			},
			actions = {
				{ idle = true },
			},
		},
		{
			line = 19,
			when = {
				{ situation = "busy" },
				{ words = { "hello$" } },
				{ expr = { questValue = 278 }, op = "=", rhs = 2 },
				{ select = true },
			},
			actions = {
				{ say = "Please wait, human %N. I'll be with you in a minute." },
				{ queue = true },
			},
		},
		{
			line = 20,
			when = {
				{ situation = "busy" },
				{ words = { "hi$" } },
				{ expr = { questValue = 278 }, op = "=", rhs = 2 },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 21,
			when = {
				{ situation = "busy" },
				{ words = { "greetings$" } },
				{ expr = { questValue = 278 }, op = "=", rhs = 2 },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 22,
			when = {
				{ situation = "busy" },
				{ words = { "djanni'hah$" } },
				{ expr = { questValue = 278 }, op = "=", rhs = 2 },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 23,
			when = {
				{ situation = "busy" },
				{ select = true },
			},
			actions = {
				{ nop = true },
			},
		},
		{
			line = 24,
			when = {
				{ situation = "vanish" },
			},
			actions = {
				{ say = "Farewell, human." },
			},
		},
		{
			line = 26,
			when = {
				{ words = { "bye" } },
			},
			actions = {
				{ say = "Farewell! May the serene light of the enlightened one rest shine on your travels." },
				{ idle = true },
			},
		},
		{
			line = 27,
			when = {
				{ words = { "farewell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 28,
			when = {
				{ words = { "name" } },
			},
			actions = {
				{ say = "My name is Haroun. At your service." },
			},
		},
		{
			line = 29,
			when = {
				{ words = { "haroun" } },
			},
			actions = {
				{ say = "That is the name my honourable father chose for me." },
			},
		},
		{
			line = 30,
			when = {
				{ words = { "job" } },
			},
			actions = {
				{ say = "I am a merchant. Though I have not chosen this position for myself I have accepted the task with humility and devotion. ..." },
				{ say = "If you have the permission of Gabel to trade with me, I can sell you some useful magical equipment." },
			},
		},
		{
			line = 32,
			when = {
				{ words = { "permission" } },
			},
			actions = {
				{ say = "I am not allowed to trade with you unless Gabel gave you the permission to trade with us." },
			},
		},
		{
			line = 34,
			when = {
				{ words = { "trade" } },
			},
			actions = {
				{ say = "It is my mission to trade items on behalf of our community. ..." },
				{ say = "Just ask me for my current offers." },
			},
		},
		{
			line = 36,
			when = {
				{ words = { "merchant" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 37,
			when = {
				{ words = { "gabel" } },
			},
			actions = {
				{ say = "He is our leader. Not because he desires power or distinction, of course, but because the community needs a guide in spiritual and in worldly matters. ..." },
				{ say = "He has accepted this burden with the modesty that is required of a true follower of Daraman." },
			},
		},
		{
			line = 39,
			when = {
				{ words = { "king" } },
			},
			actions = {
				{ say = "We do not have kings. Of the members of our community, Gabel is closest to being what you would consider a leader, but he would resent being called by that presumptuous title." },
			},
		},
		{
			line = 40,
			when = {
				{ words = { "djinn" } },
			},
			actions = {
				{ say = "That is my race. I like to compare it to iron. It has the potential to be forged into the finest steel, but it does need a lot of work and devotion. ..." },
				{ say = "Without that it is nothing but worthless scrap metal. Like our master said in the scriptures: Forge thyself! Be a blade of the true creed! (Book VI, chapter 14, verses 3 and 4)." },
			},
		},
		{
			line = 42,
			when = {
				{ words = { "efreet" } },
			},
			actions = {
				{ say = "Daraman has taught us restraint. But I am sure one day those apostates will pay dearly for their sinful rebellion!" },
			},
		},
		{
			line = 43,
			when = {
				{ words = { "marid" } },
			},
			actions = {
				{ say = "We are the chosen ones. Those who walk the path to enlightenment with serenity and humility." },
			},
		},
		{
			line = 44,
			when = {
				{ words = { "malor" } },
			},
			actions = {
				{ say = "That filthy heretic! To me he is the very embodiment of all the evilness and the baseness we djinn must leave behind." },
			},
		},
		{
			line = 45,
			when = {
				{ words = { "mal'ouquah" } },
			},
			actions = {
				{ say = "That is the name of the Efreets' hideout. It certainly is one filthy hotbed of vice and degeneration." },
			},
		},
		{
			line = 46,
			when = {
				{ words = { "ashta'daramai" } },
			},
			actions = {
				{ say = "This is the name of the humble abode you are currently visiting. After Daraman had shown him the true way Gabel decided to tear down his former palace and to erect the present structure. ..." },
				{ say = "Its name is meant as a tribute to the invaluable service Daraman has done to our race." },
			},
		},
		{
			line = 48,
			when = {
				{ words = { "human" } },
			},
			actions = {
				{ say = "Back in the dark days we used to be enemies, the humans and us. But then a human came and radically changed the way we see things. ..." },
				{ say = "He taught us to see your race as brothers. Of course... of course we still have lessons to learn, I suppose." },
			},
		},
		{
			line = 51,
			when = {
				{ words = { "zathroth" } },
			},
			actions = {
				{ say = "An evil, evil god. He was the creator of my race, but he rejected us because we were not evil enough and far too independent to his taste. For this reason the djinn do not worship him anymore, not even those depraved efreet. ..." },
				{ say = "It is difficult, you know. We djinn had to learn to find our own way, to create a destiny of our own. And although we are not evil by nature the fact that we were created by this fiend was lying like a curse on us. ..." },
				{ say = "For a long time we walked in darkness, filled with hate of ourselves and of all creation. But then everything changed. A human came and made us realise how blind we were. ..." },
				{ say = "Praise the gods who have spoken to us through Daraman! That human taught us how we could overcome our grim heritage and heal the scars that marred our souls. Humility and asceticism are the keys to a fuller existence. ..." },
				{ say = "The task may be tedious, but the price that awaits the disciples of the true creed is worth it all." },
			},
		},
		{
			line = 57,
			when = {
				{ words = { "tibia" } },
			},
			actions = {
				{ say = "Despite all the evil that stalks this world it is still a source of endless marvel and joy to me. Like the master said: ..." },
				{ say = "'Look at the world and reflect in admiration. For there is peace in a sunset and wisdom in the ocean's neverending melody.' (Book I, chapter 3, verses 2 and 3)." },
			},
		},
		{
			line = 59,
			when = {
				{ words = { "daraman" } },
			},
			actions = {
				{ say = "How could my unworthy tongue ever find words to praise the enlightened one the way he deserves to be praised? Daraman took the veil from our eyes. He made us realise the extent of our misery. ..." },
				{ say = "However, he did much more than that. He showed us a way out. He gave meaning to our lives. The service he has done to my race will never be forgotten." },
			},
		},
		{
			line = 61,
			when = {
				{ words = { "darashia" } },
			},
			actions = {
				{ say = "I understand the humans living there are self-indulgent and decadent. I am sure Daraman would disapprove of their ways." },
			},
		},
		{
			line = 62,
			when = {
				{ words = { "scarab" } },
			},
			actions = {
				{ say = "The scarab is an ancient species. It's chitinous shell can be turned into excellent armour." },
			},
		},
		{
			line = 63,
			when = {
				{ words = { "edron" } },
			},
			actions = {
				{ say = "They say the humans have founded impressive communities to the north. I hope their spiritual integrity matches their entrepreneurial spirit." },
			},
		},
		{
			line = 64,
			when = {
				{ words = { "thais" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 65,
			when = {
				{ words = { "venore" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 66,
			when = {
				{ words = { "kazordoon" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 67,
			when = {
				{ words = { "carlin" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 68,
			when = {
				{ words = { "ab'dendriel" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 69,
			when = {
				{ words = { "ankrahmun" } },
			},
			actions = {
				{ say = "Ankrahmun has a venerable tradition, but now that heretic fool has acceeded to the throne it has degenerated into a breeding place for wicked heresy." },
			},
		},
		{
			line = 70,
			when = {
				{ words = { "pharaoh" } },
			},
			actions = {
				{ say = "I have heard many a gruesome stories about this presumptuous fool, who calls himself a pharaoh. Such hubris! Daraman himself, who was certainly the most divine mortal that ever walked Tibia, would never have dared to call himself a god." },
			},
		},
		{
			line = 71,
			when = {
				{ words = { "palace" } },
			},
			actions = {
				{ say = "I am a peaceful djinn, but with all those stories I have heard I really feel like visiting the palace and to cleanse this place from all the evil and the misbelief infesting that place." },
			},
		},
		{
			line = 72,
			when = {
				{ words = { "ascension" } },
			},
			actions = {
				{ say = "I have heard this is what the pharaoh has promised his followers. It is sad to see this wicked sinner is still allowed to spread his heresy!" },
			},
		},
		{
			line = 73,
			when = {
				{ words = { "rah" } },
			},
			actions = {
				{ say = "Another one of the pharaoh's confused ideas." },
			},
		},
		{
			line = 74,
			when = {
				{ words = { "uthun" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 75,
			when = {
				{ words = { "akh" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 77,
			when = {
				{ words = { "kha'zeel" } },
			},
			actions = {
				{ say = "The Kha'zeel mountains have been created by the gods as a vantage point from where they could watch their creation. ..." },
				{ say = "Isn't it uplifting to think that even now we are standing on ground that was blessed by the great creators." },
			},
		},
		{
			line = 79,
			when = {
				{ words = { "kha'labal" } },
			},
			actions = {
				{ say = "Kha'labal. It makes me sad just to hear that name. Long, long time ago this used to be a garden, you know? ..." },
				{ say = "You should have seen it then. You should have seen the springs and the meadows and the flowers. It was a paradise. <sighs>. Oh, this terrible war." },
			},
		},
		{
			line = 81,
			when = {
				{ words = { "melchior" } },
			},
			actions = {
				{ say = "I remember Malchior. I used to meet him regularly, but strictly in matters of business. He was not really a likeable fellow then. ..." },
				{ say = "All money and profit he was, and not as quite as clever as he thought. He made quite a pretty penny by doing business both with us and the efreet. ..." },
				{ say = "He thought we wouldn't notice, but the truth is we just chose to look the other way." },
			},
		},
		{
			line = 84,
			when = {
				{ words = { "alesar" } },
			},
			actions = {
				{ say = "Who? Yes, I... I have never... I mean, I don't know who that is." },
			},
		},
		{
			line = 85,
			when = {
				{ words = { "fa'hradin" } },
			},
			actions = {
				{ say = "Fa'hradin is a learned man, and this alone is enough to make me respect him. However, I sometimes can't help the feeling that he is lacking spiritual strength." },
			},
		},
		{
			line = 86,
			when = {
				{ words = { "bo'ques" } },
			},
			actions = {
				{ say = "Bo'ques is a cook. Cooking! What a useless craft. If I were Gabel I would have little use for a cook such as him, but perhaps not all djinns are as spiritual as Daraman would have them be." },
			},
		},
		{
			line = 87,
			when = {
				{ words = { "lamp" } },
			},
			actions = {
				{ say = "The lamp is a djinn's resting place of choice." },
			},
		},
		{
			line = 89,
			when = {
				{ words = { "weapon" } },
			},
			actions = {
				{ say = "I'm afraid I do not trade with weapons or armour. Nah'bob only deals with magical equipment." },
			},
		},
		{
			line = 90,
			when = {
				{ words = { "armor" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 91,
			when = {
				{ words = { "armour" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 92,
			when = {
				{ words = { "wares" } },
			},
			actions = {
				{ say = "I only deal with magical equipment. Our range of goods include amulets, rings, wands and some special items." },
			},
		},
		{
			line = 93,
			when = {
				{ words = { "offer" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 94,
			when = {
				{ words = { "goods" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 95,
			when = {
				{ words = { "equipment" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 96,
			when = {
				{ words = { "magical" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 97,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "sell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 98,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "have" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 100,
			when = {
				{ words = { "amulets" } },
			},
			actions = {
				{ say = "I'm selling and buying bronze amulets, stone skin amulets, elven amulets and garlic necklaces." },
			},
		},
		{
			line = 101,
			when = {
				{ words = { "rings" } },
			},
			actions = {
				{ say = "I'm selling and buying stealth rings, power rings, sword rings, axe rings, and club rings." },
			},
		},
		{
			line = 102,
			when = {
				{ words = { "wands" } },
			},
			actions = {
				{ say = "I'm buying wands of vortex, wands of dragonbreath, wands of plague, wands of cosmic energy and wands of inferno as well as magic light wands." },
			},
		},
		{
			line = 103,
			when = {
				{ words = { "rods" } },
			},
			actions = {
				{ say = "I'm not interested in rods." },
			},
		},
		{
			line = 104,
			when = {
				{ words = { "special" } },
			},
			actions = {
				{ say = "I'm selling and buying magic light wands. I'm currently also looking for mind stones, life crystals and orbs." },
			},
		},
		{
			line = 106,
			when = {
				{ words = { "light" } },
			},
			actions = {
				{ set = { var = "type", value = 2162 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 120 } },
				{ say = "Do you want to buy a magic light wand for %P gold?" },
				{ set = { var = "topic", value = 10 } },
			},
		},
		{
			line = 107,
			when = {
				{ words = { "sword" } },
				{ words = { "ring" } },
			},
			actions = {
				{ set = { var = "type", value = 2207 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 500 } },
				{ say = "Do you want to buy a sword ring for %P gold?" },
				{ set = { var = "topic", value = 10 } },
			},
		},
		{
			line = 108,
			when = {
				{ words = { "axe" } },
				{ words = { "ring" } },
			},
			actions = {
				{ set = { var = "type", value = 2208 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 500 } },
				{ say = "Do you want to buy an axe ring for %P gold?" },
				{ set = { var = "topic", value = 10 } },
			},
		},
		{
			line = 109,
			when = {
				{ words = { "club" } },
				{ words = { "ring" } },
			},
			actions = {
				{ set = { var = "type", value = 2209 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 500 } },
				{ say = "Do you want to buy a club ring for %P gold?" },
				{ set = { var = "topic", value = 10 } },
			},
		},
		{
			line = 110,
			when = {
				{ words = { "stone" } },
				{ words = { "skin" } },
				{ words = { "amulet" } },
			},
			actions = {
				{ set = { var = "type", value = 2197 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 5000 } },
				{ say = "Do you want to buy a stone skin amulet for %P gold?" },
				{ set = { var = "topic", value = 10 } },
			},
		},
		{
			line = 111,
			when = {
				{ words = { "elven" } },
				{ words = { "amulet" } },
			},
			actions = {
				{ set = { var = "type", value = 2198 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 500 } },
				{ say = "Do you want to buy an elven amulet for %P gold?" },
				{ set = { var = "topic", value = 10 } },
			},
		},
		{
			line = 112,
			when = {
				{ words = { "garlic" } },
				{ words = { "necklace" } },
			},
			actions = {
				{ set = { var = "type", value = 2199 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 100 } },
				{ say = "Do you want to buy a garlic necklace for %P gold?" },
				{ set = { var = "topic", value = 10 } },
			},
		},
		{
			line = 113,
			when = {
				{ words = { "bronze" } },
				{ words = { "amulet" } },
			},
			actions = {
				{ set = { var = "type", value = 2172 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 100 } },
				{ say = "Do you want to buy a bronze amulet for %P gold?" },
				{ set = { var = "topic", value = 10 } },
			},
		},
		{
			line = 114,
			when = {
				{ words = { "stealth" } },
				{ words = { "ring" } },
			},
			actions = {
				{ set = { var = "type", value = 2165 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 5000 } },
				{ say = "Do you want to buy a stealth ring for %P gold?" },
				{ set = { var = "topic", value = 10 } },
			},
		},
		{
			line = 115,
			when = {
				{ words = { "power" } },
				{ words = { "ring" } },
			},
			actions = {
				{ set = { var = "type", value = 2166 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 100 } },
				{ say = "Do you want to buy a power ring for %P gold?" },
				{ set = { var = "topic", value = 10 } },
			},
		},
		{
			line = 117,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "light" } },
			},
			actions = {
				{ set = { var = "type", value = 2162 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 120, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A magic light wands for %P gold?" },
				{ set = { var = "topic", value = 10 } },
			},
		},
		{
			line = 118,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "power" } },
				{ words = { "ring" } },
			},
			actions = {
				{ set = { var = "type", value = 2166 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 100, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A power rings for %P gold?" },
				{ set = { var = "topic", value = 10 } },
			},
		},
		{
			line = 119,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "bronze" } },
				{ words = { "amulet" } },
			},
			actions = {
				{ set = { var = "type", value = 2172 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 100, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A bronze amulets for %P gold?" },
				{ set = { var = "topic", value = 10 } },
			},
		},
		{
			line = 120,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "sword" } },
				{ words = { "ring" } },
			},
			actions = {
				{ set = { var = "type", value = 2207 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 500, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A sword rings for %P gold?" },
				{ set = { var = "topic", value = 10 } },
			},
		},
		{
			line = 121,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "axe" } },
				{ words = { "ring" } },
			},
			actions = {
				{ set = { var = "type", value = 2208 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 500, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A axe rings for %P gold?" },
				{ set = { var = "topic", value = 10 } },
			},
		},
		{
			line = 122,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "club" } },
				{ words = { "ring" } },
			},
			actions = {
				{ set = { var = "type", value = 2209 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 500, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A club rings for %P gold?" },
				{ set = { var = "topic", value = 10 } },
			},
		},
		{
			line = 123,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "elven" } },
				{ words = { "amulet" } },
			},
			actions = {
				{ set = { var = "type", value = 2198 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 500, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A elven amulets for %P gold?" },
				{ set = { var = "topic", value = 10 } },
			},
		},
		{
			line = 124,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "garlic" } },
				{ words = { "necklace" } },
			},
			actions = {
				{ set = { var = "type", value = 2199 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 100, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A garlic necklaces for %P gold?" },
				{ set = { var = "topic", value = 10 } },
			},
		},
		{
			line = 125,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "stone" } },
				{ words = { "skin" } },
				{ words = { "amulet" } },
			},
			actions = {
				{ set = { var = "type", value = 2197 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 5000, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A stone skin amulets for %P gold?" },
				{ set = { var = "topic", value = 10 } },
			},
		},
		{
			line = 126,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "stealth" } },
				{ words = { "ring" } },
			},
			actions = {
				{ set = { var = "type", value = 2165 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 5000, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A stealth rings for %P gold?" },
				{ set = { var = "topic", value = 10 } },
			},
		},
		{
			line = 128,
			when = {
				{ words = { "sell" } },
				{ words = { "light" } },
			},
			actions = {
				{ set = { var = "type", value = 2162 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 35 } },
				{ say = "Do you want to sell a magic light wand for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 129,
			when = {
				{ words = { "sell" } },
				{ words = { "sword" } },
				{ words = { "ring" } },
			},
			actions = {
				{ set = { var = "type", value = 2207 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 100 } },
				{ say = "Do you want to sell a sword ring for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 130,
			when = {
				{ words = { "sell" } },
				{ words = { "axe" } },
				{ words = { "ring" } },
			},
			actions = {
				{ set = { var = "type", value = 2208 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 100 } },
				{ say = "Do you want to sell an axe ring for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 131,
			when = {
				{ words = { "sell" } },
				{ words = { "club" } },
				{ words = { "ring" } },
			},
			actions = {
				{ set = { var = "type", value = 2209 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 100 } },
				{ say = "Do you want to sell a club ring for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 132,
			when = {
				{ words = { "sell" } },
				{ words = { "stone" } },
				{ words = { "skin" } },
				{ words = { "amulet" } },
			},
			actions = {
				{ set = { var = "type", value = 2197 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 500 } },
				{ say = "Do you want to sell a stone skin amulet for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 133,
			when = {
				{ words = { "sell" } },
				{ words = { "elven" } },
				{ words = { "amulet" } },
			},
			actions = {
				{ set = { var = "type", value = 2198 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 100 } },
				{ say = "Do you want to sell an elven amulet for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 134,
			when = {
				{ words = { "sell" } },
				{ words = { "garlic" } },
				{ words = { "necklace" } },
			},
			actions = {
				{ set = { var = "type", value = 2199 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 50 } },
				{ say = "Do you want to sell a garlic necklace for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 135,
			when = {
				{ words = { "sell" } },
				{ words = { "bronze" } },
				{ words = { "amulet" } },
			},
			actions = {
				{ set = { var = "type", value = 2172 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 50 } },
				{ say = "Do you want to sell a bronze amulet for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 136,
			when = {
				{ words = { "sell" } },
				{ words = { "stealth" } },
				{ words = { "ring" } },
			},
			actions = {
				{ set = { var = "type", value = 2165 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 200 } },
				{ say = "Do you want to sell a stealth ring for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 137,
			when = {
				{ words = { "sell" } },
				{ words = { "power" } },
				{ words = { "ring" } },
			},
			actions = {
				{ set = { var = "type", value = 2166 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 50 } },
				{ say = "Do you want to sell a power ring for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 138,
			when = {
				{ words = { "sell" } },
				{ words = { "mind" } },
				{ words = { "stone" } },
			},
			actions = {
				{ set = { var = "type", value = 2178 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 100 } },
				{ say = "Do you want to sell a mind stone for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 139,
			when = {
				{ words = { "sell" } },
				{ words = { "life" } },
				{ words = { "crystal" } },
			},
			actions = {
				{ set = { var = "type", value = 2177 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 50 } },
				{ say = "Do you want to sell a life crystal for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 140,
			when = {
				{ words = { "sell" } },
				{ words = { "orb" } },
			},
			actions = {
				{ set = { var = "type", value = 2176 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 750 } },
				{ say = "Do you want to sell an orb for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 142,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "light" } },
			},
			actions = {
				{ set = { var = "type", value = 2162 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 35, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A magic light wands for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 143,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "power" } },
				{ words = { "ring" } },
			},
			actions = {
				{ set = { var = "type", value = 2166 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 50, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A power rings for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 144,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "bronze" } },
				{ words = { "amulet" } },
			},
			actions = {
				{ set = { var = "type", value = 2172 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 50, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A bronze amulets for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 145,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "sword" } },
				{ words = { "ring" } },
			},
			actions = {
				{ set = { var = "type", value = 2207 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 100, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A sword rings for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 146,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "axe" } },
				{ words = { "ring" } },
			},
			actions = {
				{ set = { var = "type", value = 2208 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 100, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A axe rings for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 147,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "club" } },
				{ words = { "ring" } },
			},
			actions = {
				{ set = { var = "type", value = 2209 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 100, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A club rings for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 148,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "elven" } },
				{ words = { "amulet" } },
			},
			actions = {
				{ set = { var = "type", value = 2198 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 100, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A elven amulets for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 149,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "garlic" } },
				{ words = { "necklace" } },
			},
			actions = {
				{ set = { var = "type", value = 2199 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 50, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A garlic necklaces for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 150,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "stone" } },
				{ words = { "skin" } },
				{ words = { "amulet" } },
			},
			actions = {
				{ set = { var = "type", value = 2197 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 500, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A stone skin amulets for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 151,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "stealth" } },
				{ words = { "ring" } },
			},
			actions = {
				{ set = { var = "type", value = 2165 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 200, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A stealth rings for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 152,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "mind" } },
				{ words = { "stone" } },
			},
			actions = {
				{ set = { var = "type", value = 2178 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 100, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A mind stones for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 153,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "life" } },
				{ words = { "crystal" } },
			},
			actions = {
				{ set = { var = "type", value = 2177 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 50, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A life crystals for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 154,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "orb" } },
			},
			actions = {
				{ set = { var = "type", value = 2176 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 750, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A orbs for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 156,
			when = {
				{ words = { "sell" } },
				{ words = { "wand" } },
				{ words = { "of" } },
				{ words = { "vortex" } },
			},
			actions = {
				{ set = { var = "type", value = 2190 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 100 } },
				{ say = "Do you want to sell a wand of vortex for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 157,
			when = {
				{ words = { "sell" } },
				{ words = { "wand" } },
				{ words = { "of" } },
				{ words = { "dragonbreath" } },
			},
			actions = {
				{ set = { var = "type", value = 2191 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 200 } },
				{ say = "Do you want to sell a wand of dragonbreath for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 158,
			when = {
				{ words = { "sell" } },
				{ words = { "wand" } },
				{ words = { "of" } },
				{ words = { "plague" } },
			},
			actions = {
				{ set = { var = "type", value = 2188 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 1000 } },
				{ say = "Do you want to sell a wand of plague for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 159,
			when = {
				{ words = { "sell" } },
				{ words = { "wand" } },
				{ words = { "of" } },
				{ words = { "cosmic" } },
				{ words = { "energy" } },
			},
			actions = {
				{ set = { var = "type", value = 2189 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 2000 } },
				{ say = "Do you want to sell a wand of cosmic energy for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 160,
			when = {
				{ words = { "sell" } },
				{ words = { "wand" } },
				{ words = { "of" } },
				{ words = { "inferno" } },
			},
			actions = {
				{ set = { var = "type", value = 2187 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 3000 } },
				{ say = "Do you want to sell a wand of inferno for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 162,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "wand" } },
				{ words = { "of" } },
				{ words = { "vortex" } },
			},
			actions = {
				{ set = { var = "type", value = 2190 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 100, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A wands of vortex for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 163,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "wand" } },
				{ words = { "of" } },
				{ words = { "dragonbreath" } },
			},
			actions = {
				{ set = { var = "type", value = 2191 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 200, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A wands of dragonbreath for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 164,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "wand" } },
				{ words = { "of" } },
				{ words = { "plague" } },
			},
			actions = {
				{ set = { var = "type", value = 2188 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 1000, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A wands of plague for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 165,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "wand" } },
				{ words = { "of" } },
				{ words = { "cosmic" } },
				{ words = { "energy" } },
			},
			actions = {
				{ set = { var = "type", value = 2189 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 2000, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A wands of cosmic energy for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 166,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "wand" } },
				{ words = { "of" } },
				{ words = { "inferno" } },
			},
			actions = {
				{ set = { var = "type", value = 2187 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 3000, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A wands of inferno for %P gold?" },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 168,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 10 },
				{ expr = { questValue = 283 }, op = "<", rhs = 3 },
				{ select = true },
			},
			actions = {
				{ say = "I'm sorry, human. But you need Gabel's permission to trade with me." },
			},
		},
		{
			line = 169,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 10 },
				{ words = { "yes" } },
				{ expr = { countMoney = true }, op = ">=", rhs = { session = "price" } },
			},
			actions = {
				{ say = "Thank you. May it bring you luck!" },
				{ deleteMoney = true },
				{ create = { item = { session = "type" } } },
			},
		},
		{
			line = 170,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 10 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "I hate to disappoint you, but it seems you do not have enough gold." },
			},
		},
		{
			line = 171,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 10 },
			},
			actions = {
				{ say = "I understand. Perhaps another time then." },
			},
		},
		{
			line = 173,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 11 },
				{ expr = { questValue = 283 }, op = "<", rhs = 3 },
				{ select = true },
			},
			actions = {
				{ say = "I'm sorry, human. But you need Gabel's permission to trade with me." },
			},
		},
		{
			line = 174,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 11 },
				{ words = { "yes" } },
				{ expr = { count = { session = "type" } }, op = ">=", rhs = { session = "amount" } },
			},
			actions = {
				{ say = "Thank you. Here is your money." },
				{ delete = { item = { session = "type" } } },
				{ createMoney = true },
			},
		},
		{
			line = 175,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 11 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "You do not have one." },
			},
		},
		{
			line = 176,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 11 },
				{ words = { "yes" } },
				{ expr = { session = "amount" }, op = ">", rhs = 1 },
			},
			actions = {
				{ say = "You do not have that many." },
			},
		},
		{
			line = 177,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 11 },
			},
			actions = {
				{ say = "I understand. Perhaps another time then." },
			},
		},
	},
}))

npc:register()
