-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: hofech.npc

local npc = NpcType("Hofech")
npc:appearance({ lookType = 128, lookHead = 95, lookBody = 2, lookLegs = 2, lookFeet = 57 })
npc:movement({ radius = 2, speed = 10 })
npc:health(100)
npc:sex(1)
npc:race(1)

local rules = {}
NpcAppendRules(rules, {
	{
		line = 13,
		when = {
			{ situation = "address" },
			{ words = { "hello$" } },
			{ select = true },
		},
		actions = {
			{ say = "Welcome %N! Have a look at my wares, my friend." },
		},
	},
	{
		line = 14,
		when = {
			{ situation = "address" },
			{ words = { "hi$" } },
			{ select = true },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 15,
		when = {
			{ situation = "address" },
			{ select = true },
		},
		actions = {
			{ idle = true },
		},
	},
	{
		line = 16,
		when = {
			{ situation = "busy" },
			{ words = { "hello$" } },
			{ select = true },
		},
		actions = {
			{ say = "%N, just a moment, please." },
			{ queue = true },
		},
	},
	{
		line = 17,
		when = {
			{ situation = "busy" },
			{ words = { "hi$" } },
			{ select = true },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 18,
		when = {
			{ situation = "busy" },
			{ select = true },
		},
		actions = {
			{ nop = true },
		},
	},
	{
		line = 19,
		when = {
			{ situation = "vanish" },
			{ select = true },
		},
		actions = {
			{ say = "Daraman's blessings." },
		},
	},
	{
		line = 21,
		when = {
			{ words = { "bye" } },
		},
		actions = {
			{ say = "Daraman's blessings." },
			{ idle = true },
		},
	},
	{
		line = 22,
		when = {
			{ words = { "name" } },
		},
		actions = {
			{ say = "I am Hofech Ibn Kalith." },
		},
	},
	{
		line = 23,
		when = {
			{ words = { "job" } },
		},
		actions = {
			{ say = "I am selling furniture and equipment to grace the homes." },
		},
	},
	{
		line = 24,
		when = {
			{ words = { "time" } },
		},
		actions = {
			{ say = "It's %T my friend." },
		},
	},
	{
		line = 25,
		when = {
			{ words = { "caliph" } },
		},
		actions = {
			{ say = "The caliph has the finest home and interior decoration in Darashia." },
		},
	},
	{
		line = 26,
		when = {
			{ words = { "kazzan" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 27,
		when = {
			{ words = { "daraman" } },
		},
		actions = {
			{ say = "The prophet is alive! Both in the heavens and in our our hearts." },
		},
	},
	{
		line = 28,
		when = {
			{ words = { "ferumbras" } },
		},
		actions = {
			{ say = "I don't know about such a person, my friend." },
		},
	},
	{
		line = 29,
		when = {
			{ words = { "excalibug" } },
		},
		actions = {
			{ say = "I think if that sword really existed, it would make a splendid decoration for any wall." },
		},
	},
	{
		line = 30,
		when = {
			{ words = { "thais" } },
		},
		actions = {
			{ say = "The wood we are using to make our exquisite furniture is partly supplied by Thais." },
		},
	},
	{
		line = 31,
		when = {
			{ words = { "tibia" } },
		},
		actions = {
			{ say = "One day I will take my flying carpet to see the whole world." },
		},
	},
	{
		line = 32,
		when = {
			{ words = { "carlin" } },
		},
		actions = {
			{ say = "I was not there yet. But I plan to travel there one day." },
		},
	},
	{
		line = 34,
		when = {
			{ words = { "offer" } },
		},
		actions = {
			{ say = "I sell statues, tables, chairs, flowers, pillows, pottery, instruments, decoration, tapestries and containers." },
		},
	},
	{
		line = 35,
		when = {
			{ words = { "goods" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 36,
		when = {
			{ words = { "do" } },
			{ words = { "you" } },
			{ words = { "sell" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 37,
		when = {
			{ words = { "do" } },
			{ words = { "you" } },
			{ words = { "have" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 38,
		when = {
			{ words = { "furniture" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 39,
		when = {
			{ words = { "equipment" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 40,
		when = {
			{ words = { "special" } },
		},
		actions = {
			{ say = "My offers are extraordinarily cheap, given the fine quality of our stock. Just look at that table!" },
		},
	},
	{
		line = 41,
		when = {
			{ words = { "carpet" } },
		},
		actions = {
			{ say = "No no, I don't sell any carpets." },
		},
	},
})
NpcAppendRules(rules, NpcCatalogs["gen-t-furniture-statues-s"])
NpcAppendRules(rules, NpcCatalogs["gen-t-furniture-tables-s"])
NpcAppendRules(rules, NpcCatalogs["gen-t-furniture-chairs-s"])
NpcAppendRules(rules, NpcCatalogs["gen-t-furniture-flowers-s"])
NpcAppendRules(rules, NpcCatalogs["gen-t-furniture-pillows-s"])
NpcAppendRules(rules, NpcCatalogs["gen-t-furniture-pottery-s"])
NpcAppendRules(rules, NpcCatalogs["gen-t-furniture-instruments-s"])
NpcAppendRules(rules, NpcCatalogs["gen-t-furniture-decoration-s"])
NpcAppendRules(rules, NpcCatalogs["gen-t-furniture-tapestries-s"])
NpcAppendRules(rules, NpcCatalogs["gen-t-furniture-containers-s"])
npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = rules,
}))

npc:register()
