-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: jakahr.npc

local npc = NpcType("Jakahr")
npc:appearance({ lookType = 133, lookHead = 95, lookBody = 37, lookLegs = 32, lookFeet = 40 })
npc:movement({ radius = 1, speed = 10 })
npc:health(100)
npc:sex(1)
npc:race(1)

local rules = {}
NpcAppendRules(rules, {
	{
		line = 13,
		when = {
			{ situation = "address" },
			{ words = { "hello$" } },
			{ select = true },
		},
		actions = {
			{ say = "Hello, mourned pilgrim. How may I help you %N?" },
		},
	},
	{
		line = 14,
		when = {
			{ situation = "address" },
			{ words = { "hi$" } },
			{ select = true },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 15,
		when = {
			{ situation = "address" },
			{ select = true },
		},
		actions = {
			{ idle = true },
		},
	},
	{
		line = 16,
		when = {
			{ situation = "busy" },
			{ words = { "hello$" } },
			{ select = true },
		},
		actions = {
			{ say = "I am already talking to a customer, %N. Please wait a moment." },
			{ queue = true },
		},
	},
	{
		line = 17,
		when = {
			{ situation = "busy" },
			{ words = { "hi$" } },
			{ select = true },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 18,
		when = {
			{ situation = "busy" },
			{ select = true },
		},
		actions = {
			{ nop = true },
		},
	},
	{
		line = 19,
		when = {
			{ situation = "vanish" },
			{ select = true },
		},
		actions = {
			{ say = "It was an honour to serve you, %N." },
		},
	},
	{
		line = 21,
		when = {
			{ words = { "bye" } },
		},
		actions = {
			{ say = "It was an honour to serve you." },
			{ idle = true },
		},
	},
	{
		line = 22,
		when = {
			{ words = { "farewell" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 25,
		when = {
			{ words = { "kevin" } },
		},
		actions = {
			{ say = "Even in our lands the name of the guildmaster is held in great respect." },
		},
	},
	{
		line = 26,
		when = {
			{ words = { "postner" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 27,
		when = {
			{ words = { "postmasters" } },
			{ words = { "guild" } },
		},
		actions = {
			{ say = "The guild plays a vital role in the economy of the known world." },
		},
	},
	{
		line = 28,
		when = {
			{ words = { "join" } },
		},
		actions = {
			{ say = "Please travel to our headquarters if you wish to join our guild." },
		},
	},
	{
		line = 29,
		when = {
			{ words = { "headquarters" } },
		},
		actions = {
			{ say = "You can find them to the south of the dwarven city of Kazordoon." },
		},
	},
	{
		line = 31,
		when = {
			{ words = { "job" } },
		},
		actions = {
			{ say = "I am a member of the Postmasters Guild. If you have questions about the Royal Tibia Mail System or the depots, ask me." },
		},
	},
	{
		line = 32,
		when = {
			{ words = { "office" } },
		},
		actions = {
			{ say = "I am always here in my office. You are welcome to visit me anytime." },
		},
	},
	{
		line = 33,
		when = {
			{ words = { "name" } },
		},
		actions = {
			{ say = "My name is Jakahr." },
		},
	},
	{
		line = 34,
		when = {
			{ words = { "time" } },
		},
		actions = {
			{ say = "The time is %T, pilgrim." },
		},
	},
	{
		line = 36,
		when = {
			{ words = { "depot" } },
		},
		actions = {
			{ say = "The depots are easy to use. Just open a locker to find your items there." },
		},
	},
	{
		line = 38,
		when = {
			{ words = { "excalibug" } },
		},
		actions = {
			{ say = "A weapon of legend. We rarely hear stories about it around here, however." },
		},
	},
	{
		line = 39,
		when = {
			{ words = { "news" } },
		},
		actions = {
			{ say = "It does not befit a member of my position to spread rumours and stories, pilgrim." },
		},
	},
	{
		line = 40,
		when = {
			{ words = { "thais" } },
		},
		actions = {
			{ say = "Thais is the capital of a kingdom on a far-off continent." },
		},
	},
	{
		line = 41,
		when = {
			{ words = { "carlin" } },
		},
		actions = {
			{ say = "Carlin is a city far, far away from here. They say it is run by women and druids." },
		},
	},
})
NpcAppendRules(rules, NpcCatalogs["gen-post"])
NpcAppendRules(rules, {
	{
		line = 45,
		when = {
			{ words = { "darama" } },
		},
		actions = {
			{ say = "On this continent, the only place of real importance is our city." },
		},
	},
	{
		line = 46,
		when = {
			{ words = { "darashia" } },
		},
		actions = {
			{ say = "A minor settlement to the north." },
		},
	},
	{
		line = 47,
		when = {
			{ words = { "daraman" } },
		},
		actions = {
			{ say = "As far as I can tell he was some philosopher." },
		},
	},
	{
		line = 48,
		when = {
			{ words = { "ankrahmun" } },
		},
		actions = {
			{ say = "This city is a safe haven that protects its citizens from the dangers of the desert." },
		},
	},
	{
		line = 49,
		when = {
			{ words = { "city" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 51,
		when = {
			{ words = { "pharaoh" } },
		},
		actions = {
			{ say = "The pharaoh keeps this city safe. He is both our political and our spiritual leader." },
		},
	},
	{
		line = 52,
		when = {
			{ words = { "arkhothep" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 54,
		when = {
			{ words = { "ascension" } },
		},
		actions = {
			{ say = "Sorry, but you should discuss religous issues like these in the temple. I am not a priest, and there is little I can tell you about it." },
		},
	},
	{
		line = 55,
		when = {
			{ words = { "Akh'rah" } },
			{ words = { "Uthun" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 56,
		when = {
			{ words = { "Akh" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 57,
		when = {
			{ words = { "Rah" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 58,
		when = {
			{ words = { "uthun" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 60,
		when = {
			{ words = { "arena" } },
		},
		actions = {
			{ say = "Fights are frequently staged in the arena to entertain the people." },
		},
	},
	{
		line = 61,
		when = {
			{ words = { "palace" } },
		},
		actions = {
			{ say = "You can't miss the palace. It is probably the biggest pyramid in the whole world." },
		},
	},
	{
		line = 62,
		when = {
			{ words = { "temple" } },
		},
		actions = {
			{ say = "The temple is to the east of the city." },
		},
	},
})
npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = rules,
}))

npc:register()
