-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: james.npc

local npc = NpcType("James")
npc:appearance({ lookType = 128, lookHead = 115, lookBody = 41, lookLegs = 45, lookFeet = 118 })
npc:movement({ radius = 2, speed = 5, goStrength = 5 })
npc:health(100)
npc:sex(1)
npc:race(1)

npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = {
		{
			line = 13,
			when = {
				{ situation = "address" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Hi there %N." },
			},
		},
		{
			line = 14,
			when = {
				{ situation = "address" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 15,
			when = {
				{ situation = "address" },
				{ select = true },
			},
			actions = {
				{ idle = true },
			},
		},
		{
			line = 16,
			when = {
				{ situation = "busy" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Talking right now, %N. Wait a second." },
				{ queue = true },
			},
		},
		{
			line = 17,
			when = {
				{ situation = "busy" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 18,
			when = {
				{ situation = "busy" },
				{ select = true },
			},
			actions = {
				{ nop = true },
			},
		},
		{
			line = 19,
			when = {
				{ situation = "vanish" },
				{ select = true },
			},
			actions = {
				{ say = "Bye." },
			},
		},
		{
			line = 21,
			when = {
				{ words = { "bye" } },
			},
			actions = {
				{ say = "Bye." },
				{ idle = true },
			},
		},
		{
			line = 22,
			when = {
				{ words = { "how" } },
				{ words = { "are" } },
				{ words = { "you" } },
			},
			actions = {
				{ say = "Fine, thanks." },
			},
		},
		{
			line = 23,
			when = {
				{ words = { "sell" } },
			},
			actions = {
				{ say = "I sell some food." },
			},
		},
		{
			line = 24,
			when = {
				{ words = { "job" } },
			},
			actions = {
				{ say = "I am a humble farmer." },
			},
		},
		{
			line = 25,
			when = {
				{ words = { "name" } },
			},
			actions = {
				{ say = "James." },
			},
		},
		{
			line = 26,
			when = {
				{ words = { "time" } },
			},
			actions = {
				{ say = "I am too poor to afford a watch." },
			},
		},
		{
			line = 27,
			when = {
				{ words = { "help" } },
			},
			actions = {
				{ say = "Sorry, can't offer you any help." },
			},
		},
		{
			line = 28,
			when = {
				{ words = { "monster" } },
			},
			actions = {
				{ say = "There are dangerous monsters and renegade knights in the northwest behind the river and the mountain." },
			},
		},
		{
			line = 29,
			when = {
				{ words = { "dungeon" } },
			},
			actions = {
				{ say = "I stay away from dungeons as far as I can." },
			},
		},
		{
			line = 30,
			when = {
				{ words = { "god" } },
			},
			actions = {
				{ say = "May Crunor bless our harvests." },
			},
		},
		{
			line = 31,
			when = {
				{ words = { "king" } },
			},
			actions = {
				{ say = "I never saw him in person." },
			},
		},
		{
			line = 32,
			when = {
				{ words = { "daniel" } },
			},
			actions = {
				{ say = "A brave warrior as far as a farmer like me can tell." },
			},
		},
		{
			line = 33,
			when = {
				{ words = { "avar$" } },
			},
			actions = {
				{ say = "He scares me a little." },
			},
		},
		{
			line = 34,
			when = {
				{ words = { "academy" } },
			},
			actions = {
				{ say = "The mages and druids have quite an appetite. They buy much from me and summon even more food." },
			},
		},
		{
			line = 35,
			when = {
				{ words = { "magic" } },
			},
			actions = {
				{ say = "I am nothing but a humble farmer and know nothing about that." },
			},
		},
		{
			line = 36,
			when = {
				{ words = { "weapon" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 37,
			when = {
				{ words = { "spell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 38,
			when = {
				{ words = { "tibia" } },
			},
			actions = {
				{ say = "If I were you, I would stay here." },
			},
		},
		{
			line = 39,
			when = {
				{ words = { "thais" } },
			},
			actions = {
				{ say = "I was born in Thais, but my family moved to Edron among the first settlers." },
			},
		},
		{
			line = 40,
			when = {
				{ words = { "edron" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 42,
			when = {
				{ words = { "bread" } },
			},
			actions = {
				{ set = { var = "type", value = 2689 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 3 } },
				{ say = "Do you want to buy a bread for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 43,
			when = {
				{ words = { "cheese" } },
			},
			actions = {
				{ set = { var = "type", value = 2696 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 5 } },
				{ say = "Do you want to buy a cheese for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 44,
			when = {
				{ words = { "meat" } },
			},
			actions = {
				{ set = { var = "type", value = 2666 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 5 } },
				{ say = "Do you want to buy meat for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 45,
			when = {
				{ words = { "ham" } },
			},
			actions = {
				{ set = { var = "type", value = 2671 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 8 } },
				{ say = "Do you want to buy a ham for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 46,
			when = {
				{ words = { "apple" } },
			},
			actions = {
				{ set = { var = "type", value = 2674 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 3 } },
				{ say = "Do you want to buy an apple for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 48,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "bread" } },
			},
			actions = {
				{ set = { var = "type", value = 2689 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 3, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A breads for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 49,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "cheese" } },
			},
			actions = {
				{ set = { var = "type", value = 2696 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 5, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A cheese for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 50,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "meat" } },
			},
			actions = {
				{ set = { var = "type", value = 2666 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 5, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A meat for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 51,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "ham" } },
			},
			actions = {
				{ set = { var = "type", value = 2671 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 8, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A ham for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 52,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "apple" } },
			},
			actions = {
				{ set = { var = "type", value = 2674 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 3, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A apples for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 55,
			when = {
				{ words = { "buy" } },
			},
			actions = {
				{ say = "I can offer you bread, cheese, ham, meat, and apples." },
			},
		},
		{
			line = 56,
			when = {
				{ words = { "food" } },
			},
			actions = {
				{ say = "Are you looking for food? I have bread, cheese, ham, meat, and apples." },
			},
		},
		{
			line = 58,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
				{ expr = { countMoney = true }, op = ">=", rhs = { session = "price" } },
			},
			actions = {
				{ say = "Here it is." },
				{ deleteMoney = true },
				{ create = { item = { session = "type" }, count = 1 } },
			},
		},
		{
			line = 59,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "I am sorry, but you do not have enough gold." },
			},
		},
		{
			line = 60,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
			},
			actions = {
				{ say = "Maybe later." },
			},
		},
	},
}))

npc:register()
