-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: lector.npc

local npc = NpcType("Lector")
npc:appearance({ lookType = 128, lookHead = 79, lookBody = 38, lookLegs = 0, lookFeet = 124 })
npc:movement({ radius = 3, speed = 10, goStrength = 10 })
npc:health(100)
npc:sex(1)
npc:race(1)

npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = {
		{
			line = 13,
			when = {
				{ situation = "address" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Welcome to my humble shop, %N." },
			},
		},
		{
			line = 14,
			when = {
				{ situation = "address" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 15,
			when = {
				{ situation = "address" },
				{ select = true },
			},
			actions = {
				{ idle = true },
			},
		},
		{
			line = 16,
			when = {
				{ situation = "busy" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Just a minute, %N." },
				{ queue = true },
			},
		},
		{
			line = 17,
			when = {
				{ situation = "busy" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 18,
			when = {
				{ situation = "busy" },
				{ select = true },
			},
			actions = {
				{ nop = true },
			},
		},
		{
			line = 19,
			when = {
				{ situation = "vanish" },
				{ select = true },
			},
			actions = {
				{ say = "Please come and buy again." },
			},
		},
		{
			line = 21,
			when = {
				{ words = { "bye" } },
			},
			actions = {
				{ say = "Please come and buy again." },
				{ idle = true },
			},
		},
		{
			line = 22,
			when = {
				{ words = { "farewell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 23,
			when = {
				{ words = { "job" } },
			},
			actions = {
				{ say = "I am the butcher. I am selling delicious meat." },
			},
		},
		{
			line = 24,
			when = {
				{ words = { "butcher" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 25,
			when = {
				{ words = { "name" } },
			},
			actions = {
				{ say = "My father named me Lector." },
			},
		},
		{
			line = 26,
			when = {
				{ words = { "father" } },
			},
			actions = {
				{ say = "My father, Hannibal, was the royal cook. He died some years ago in an attack of the evil Ferumbras." },
			},
		},
		{
			line = 27,
			when = {
				{ words = { "time" } },
			},
			actions = {
				{ say = "It is exactly %T." },
			},
		},
		{
			line = 28,
			when = {
				{ words = { "graveyard" } },
			},
			actions = {
				{ say = "I heared, the mausoleum is haunted!" },
			},
		},
		{
			line = 29,
			when = {
				{ words = { "mausoleum" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 30,
			when = {
				{ words = { "dragon" } },
				{ words = { "steak" } },
			},
			actions = {
				{ say = "Dragon steak was the favourite meal of Tark Trueblade." },
			},
		},
		{
			line = 31,
			when = {
				{ words = { "tark" } },
				{ words = { "trueblade" } },
			},
			actions = {
				{ say = "Tark Trueblade was the greatest dragonslayer of all. I heared, he died in a battle with an ancient dragon lord." },
			},
		},
		{
			line = 32,
			when = {
				{ words = { "ghostlands" } },
			},
			actions = {
				{ say = "A bloody place with a bloody history. I wonder if it realy drove people mad or if it just attracted those already disbalanced in their minds." },
			},
		},
		{
			line = 34,
			when = {
				{ words = { "buy" } },
			},
			actions = {
				{ say = "I can offer you ham or meat. Dragon steaks are out. <giggle>" },
			},
		},
		{
			line = 35,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "sell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 36,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "have" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 37,
			when = {
				{ words = { "food" } },
			},
			actions = {
				{ say = "Are you looking for food? I can offer you ham or meat." },
			},
		},
		{
			line = 39,
			when = {
				{ words = { "meat" } },
			},
			actions = {
				{ set = { var = "type", value = 2666 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 3 } },
				{ say = "Do you want to buy meat for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 40,
			when = {
				{ words = { "ham" } },
			},
			actions = {
				{ set = { var = "type", value = 2671 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 6 } },
				{ say = "Do you want to buy a ham for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 42,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "meat" } },
			},
			actions = {
				{ set = { var = "type", value = 2666 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 3, rhs = { capture = 1 } } } } },
				{ say = "Do you wanna buy %A meat for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 43,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "ham" } },
			},
			actions = {
				{ set = { var = "type", value = 2671 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 6, rhs = { capture = 1 } } } } },
				{ say = "Do you wanna buy %A ham for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 45,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
				{ expr = { countMoney = true }, op = ">=", rhs = { session = "price" } },
			},
			actions = {
				{ say = "Here it is." },
				{ deleteMoney = true },
				{ create = { item = { session = "type" } } },
			},
		},
		{
			line = 46,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "I am sorry, but you do not have enough gold." },
			},
		},
		{
			line = 47,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
			},
			actions = {
				{ say = "Maybe later." },
			},
		},
	},
}))

npc:register()
