-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: livielle.npc

local npc = NpcType("Livielle")
npc:appearance({ lookType = 138, lookHead = 114, lookBody = 94, lookLegs = 132, lookFeet = 132 })
npc:movement({ radius = 2, speed = 10, goStrength = 10 })
npc:health(100)
npc:sex(0)
npc:race(1)

npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = {
		{
			line = 13,
			when = {
				{ situation = "address" },
				{ words = { "hello$" } },
				{ property = "male" },
				{ select = true },
			},
			actions = {
				{ say = "Ah, 'ello, %N! I can see you're longing for my delicious fruits, chéri." },
			},
		},
		{
			line = 14,
			when = {
				{ situation = "address" },
				{ words = { "hi$" } },
				{ property = "male" },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 15,
			when = {
				{ situation = "address" },
				{ words = { "salut$" } },
				{ property = "male" },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 16,
			when = {
				{ situation = "address" },
				{ words = { "hello$" } },
				{ property = "female" },
				{ select = true },
			},
			actions = {
				{ say = "Bienvenue, %N! My fruits will complete the icing on your cake." },
			},
		},
		{
			line = 17,
			when = {
				{ situation = "address" },
				{ words = { "hi$" } },
				{ property = "female" },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 18,
			when = {
				{ situation = "address" },
				{ words = { "salut$" } },
				{ property = "female" },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 19,
			when = {
				{ situation = "address" },
				{ select = true },
			},
			actions = {
				{ idle = true },
			},
		},
		{
			line = 20,
			when = {
				{ situation = "busy" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Don't push me, don't push me. One after another, %N." },
			},
		},
		{
			line = 21,
			when = {
				{ situation = "busy" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 22,
			when = {
				{ situation = "busy" },
				{ words = { "salut$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 23,
			when = {
				{ situation = "busy" },
				{ select = true },
			},
			actions = {
				{ nop = true },
			},
		},
		{
			line = 24,
			when = {
				{ situation = "vanish" },
				{ select = true },
			},
			actions = {
				{ say = "Aww, I don't even deserve a farewell?" },
			},
		},
		{
			line = 26,
			when = {
				{ words = { "bye" } },
			},
			actions = {
				{ say = "Bon appétit, and come back soon for your daily dose of vitamins!" },
				{ idle = true },
			},
		},
		{
			line = 27,
			when = {
				{ words = { "au" } },
				{ words = { "revoir" } },
			},
			actions = {
				{ say = "Bon appétit, and come back soon for your daily dose of vitamins!" },
				{ idle = true },
			},
		},
		{
			line = 28,
			when = {
				{ words = { "job" } },
			},
			actions = {
				{ say = "Alors, guess what my job might be, standing 'ere in the middle of all these juicy exotic fruits?" },
			},
		},
		{
			line = 29,
			when = {
				{ words = { "shop" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 30,
			when = {
				{ words = { "name" } },
				{ property = "male" },
			},
			actions = {
				{ say = "Moi? Livielle for you, chéri. " },
			},
		},
		{
			line = 31,
			when = {
				{ words = { "name" } },
				{ property = "female" },
			},
			actions = {
				{ say = "I'm Livielle Delacroix, madame." },
			},
		},
		{
			line = 32,
			when = {
				{ words = { "time" } },
			},
			actions = {
				{ say = "Time is %T now." },
			},
		},
		{
			line = 33,
			when = {
				{ words = { "help" } },
			},
			actions = {
				{ say = "Oh, for sure will my fruits 'elp you driving off all these nasty diseases and strengthen your immune system!" },
			},
		},
		{
			line = 34,
			when = {
				{ words = { "thanks" } },
			},
			actions = {
				{ say = "You're welcome, enjoy." },
			},
		},
		{
			line = 35,
			when = {
				{ words = { "thank" } },
				{ words = { "you" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 37,
			when = {
				{ words = { "buy" } },
			},
			actions = {
				{ say = "What's your favorite flavour today? I offer all sorts of exotic fruits." },
			},
		},
		{
			line = 38,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "sell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 39,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "have" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 40,
			when = {
				{ words = { "offer" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 41,
			when = {
				{ words = { "fruits" } },
			},
			actions = {
				{ say = "I offer you bananas, melons, pumpkins, white mushrooms, oranges, strawberries, and blueberries." },
			},
		},
		{
			line = 43,
			when = {
				{ words = { "banana" } },
			},
			actions = {
				{ set = { var = "type", value = 3587 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 5 } },
				{ say = "Do you want to buy a banana for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 44,
			when = {
				{ words = { "white" } },
				{ words = { "mushroom" } },
			},
			actions = {
				{ set = { var = "type", value = 3723 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 10 } },
				{ say = "Do you want to buy one of the white mushrooms for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 45,
			when = {
				{ words = { "orange" } },
			},
			actions = {
				{ set = { var = "type", value = 3586 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 10 } },
				{ say = "Do you want to buy an orange for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 46,
			when = {
				{ words = { "strawberr" } },
			},
			actions = {
				{ set = { var = "type", value = 3591 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 2 } },
				{ say = "Do you want to buy a strawberry for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 47,
			when = {
				{ words = { "melon" } },
			},
			actions = {
				{ set = { var = "type", value = 3593 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 10 } },
				{ say = "Do you want to buy a melon for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 48,
			when = {
				{ words = { "pumpkin" } },
			},
			actions = {
				{ set = { var = "type", value = 3594 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 10 } },
				{ say = "Do you want to buy a pumpkin for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 49,
			when = {
				{ words = { "blueberr" } },
			},
			actions = {
				{ set = { var = "type", value = 3588 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 1 } },
				{ say = "Do you want to buy a blueberry for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 51,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "banana" } },
			},
			actions = {
				{ set = { var = "type", value = 3587 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 5, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A bananas for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 52,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "white" } },
				{ words = { "mushroom" } },
			},
			actions = {
				{ set = { var = "type", value = 3723 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 10, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A of the white mushrooms for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 53,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "orange" } },
			},
			actions = {
				{ set = { var = "type", value = 3586 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 10, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A oranges for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 54,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "strawberr" } },
			},
			actions = {
				{ set = { var = "type", value = 3591 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 2, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A strawberries for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 55,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "melon" } },
			},
			actions = {
				{ set = { var = "type", value = 3593 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 10, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A melons for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 56,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "pumpkin" } },
			},
			actions = {
				{ set = { var = "type", value = 3594 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 10, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A pumpkins for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 57,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "blueberr" } },
			},
			actions = {
				{ set = { var = "type", value = 3588 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 1, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A blueberries for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 59,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
				{ expr = { countMoney = true }, op = ">=", rhs = { session = "price" } },
			},
			actions = {
				{ say = "Merci, 'ere you go." },
				{ deleteMoney = true },
				{ create = { item = { session = "type" }, count = 1 } },
			},
		},
		{
			line = 60,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "Sorry, but that's not enough money, please count again." },
			},
		},
		{
			line = 61,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
			},
			actions = {
				{ say = "You should really prefer my fruits over all this fat meat offered elsewhere. They keep you lithe and lissom." },
			},
		},
	},
}))

npc:register()
