-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: memech.npc

local npc = NpcType("Memech")
npc:appearance({ lookType = 131, lookHead = 21, lookBody = 21, lookLegs = 40, lookFeet = 116 })
npc:movement({ radius = 2, speed = 2, goStrength = 2 })
npc:health(100)
npc:sex(1)
npc:race(1)

npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = {
		{
			line = 13,
			when = {
				{ situation = "address" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Be mourned pilgrim in flesh." },
			},
		},
		{
			line = 14,
			when = {
				{ situation = "address" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ say = "Be mourned pilgrim in flesh." },
			},
		},
		{
			line = 15,
			when = {
				{ situation = "address" },
				{ words = { "be" } },
				{ words = { "mourned" } },
				{ words = { "pilgrim" } },
				{ words = { "flesh" } },
				{ select = true },
			},
			actions = {
				{ say = "Be mourned pilgrim in flesh." },
			},
		},
		{
			line = 16,
			when = {
				{ situation = "address" },
				{ select = true },
			},
			actions = {
				{ idle = true },
			},
		},
		{
			line = 18,
			when = {
				{ situation = "busy" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Mourned %N, know that I am busy." },
				{ queue = true },
			},
		},
		{
			line = 19,
			when = {
				{ situation = "busy" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 20,
			when = {
				{ situation = "busy" },
				{ words = { "be" } },
				{ words = { "mourned" } },
				{ words = { "pilgrim" } },
				{ words = { "flesh" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 21,
			when = {
				{ situation = "busy" },
				{ select = true },
			},
			actions = {
				{ nop = true },
			},
		},
		{
			line = 22,
			when = {
				{ situation = "vanish" },
				{ select = true },
			},
			actions = {
				{ say = "Taken away by the hands of time." },
			},
		},
		{
			line = 24,
			when = {
				{ words = { "bye" } },
			},
			actions = {
				{ say = "May enlightenment be your path." },
				{ idle = true },
			},
		},
		{
			line = 25,
			when = {
				{ words = { "farewell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 26,
			when = {
				{ words = { "job" } },
			},
			actions = {
				{ say = "I sell weapons and armor to protect your mortal shell." },
			},
		},
		{
			line = 27,
			when = {
				{ words = { "name" } },
			},
			actions = {
				{ say = "I am the mourned Memech." },
			},
		},
		{
			line = 28,
			when = {
				{ words = { "time" } },
			},
			actions = {
				{ say = "Time is only a burden to the flesh." },
			},
		},
		{
			line = 29,
			when = {
				{ words = { "temple" } },
			},
			actions = {
				{ say = "You will find the temple in the northeastern part of the town." },
			},
		},
		{
			line = 30,
			when = {
				{ words = { "pharaoh" } },
			},
			actions = {
				{ say = "Praise to the pharaoh. Blessed be our saviour." },
			},
		},
		{
			line = 31,
			when = {
				{ words = { "oldpharaoh" } },
			},
			actions = {
				{ say = "Praised be our pharaoh who gave his father all the time in the world for contemplation and ascension." },
			},
		},
		{
			line = 32,
			when = {
				{ words = { "scarab" } },
			},
			actions = {
				{ say = "The scarabs are wise as far as I know. They test each warrior's strength." },
			},
		},
		{
			line = 34,
			when = {
				{ words = { "tibia" } },
			},
			actions = {
				{ say = "This world is but a dying spark of a once great fire." },
			},
		},
		{
			line = 35,
			when = {
				{ words = { "carlin" } },
			},
			actions = {
				{ say = "The lost cities of the Tibian continent are caught in their false gods' jaws." },
			},
		},
		{
			line = 36,
			when = {
				{ words = { "thais" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 37,
			when = {
				{ words = { "edron" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 38,
			when = {
				{ words = { "venore" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 39,
			when = {
				{ words = { "kazordoon" } },
			},
			actions = {
				{ say = "I have been told the dwarves are worthy fighters. It is a shame their Rah will perish upon death." },
			},
		},
		{
			line = 40,
			when = {
				{ words = { "dwarves" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 41,
			when = {
				{ words = { "dwarfes" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 42,
			when = {
				{ words = { "ab'dendriel" } },
			},
			actions = {
				{ say = "Elves are a rare sight on this continent. I know little about this race and their ways." },
			},
		},
		{
			line = 43,
			when = {
				{ words = { "elves" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 44,
			when = {
				{ words = { "elfes" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 45,
			when = {
				{ words = { "darama" } },
			},
			actions = {
				{ say = "The continent's name was changed to Darama after Daraman spread his teachings here. I don't know its old name, I'm afraid." },
			},
		},
		{
			line = 46,
			when = {
				{ words = { "daraman" } },
			},
			actions = {
				{ say = "Daraman is acknowledged as a prophet, though it is said he was misguided. I think you should better ask somebody in the temple about such issues." },
			},
		},
		{
			line = 47,
			when = {
				{ words = { "ankrahmun" } },
			},
			actions = {
				{ say = "Our home is blessed and protected by the power of our pharaoh." },
			},
		},
		{
			line = 49,
			when = {
				{ words = { "pharaoh" } },
			},
			actions = {
				{ say = "The pharaoh is a living god and his power is rising with every day." },
			},
		},
		{
			line = 50,
			when = {
				{ words = { "false" } },
				{ words = { "gods" } },
			},
			actions = {
				{ say = "Well, the temple teaches us that the false gods want to steal our Rah." },
			},
		},
		{
			line = 51,
			when = {
				{ words = { "ascension" } },
			},
			actions = {
				{ say = "This is nothing I understand. I am but a simple man." },
			},
		},
		{
			line = 52,
			when = {
				{ words = { "Akh'rah" } },
				{ words = { "Uthun" } },
			},
			actions = {
				{ say = "Thats religious stuff, and I don't know much about it. It's about the union and the separation of Akh, Rah and Uthun." },
			},
		},
		{
			line = 53,
			when = {
				{ words = { "Akh" } },
			},
			actions = {
				{ say = "Well, that is the mortal body. It is full of needs and thus sinful." },
			},
		},
		{
			line = 54,
			when = {
				{ words = { "undead" } },
			},
			actions = {
				{ say = "Undeath must be great. No need to eat, to sleep or to do other things like that, you know." },
			},
		},
		{
			line = 55,
			when = {
				{ words = { "undeath" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 56,
			when = {
				{ words = { "Rah" } },
			},
			actions = {
				{ say = "The Rah is what people from other religions call the soul." },
			},
		},
		{
			line = 57,
			when = {
				{ words = { "uthun" } },
			},
			actions = {
				{ say = "That's what we learn and remember. It is who we are because of our memories. At least that's what I understand." },
			},
		},
		{
			line = 58,
			when = {
				{ words = { "mourn" } },
			},
			actions = {
				{ say = "Mortality is a bad thing. The dead mourn us for that. Quite nice of them. We should mourn ourselves as well, if I understand the priests correctly." },
			},
		},
		{
			line = 59,
			when = {
				{ words = { "arena" } },
			},
			actions = {
				{ say = "The arena is a fun place to visit. You should go there to try out our quality equipment." },
			},
		},
		{
			line = 60,
			when = {
				{ words = { "palace" } },
			},
			actions = {
				{ say = "That's where our pharaohs resides. The palace is to the east." },
			},
		},
		{
			line = 61,
			when = {
				{ words = { "offer" } },
			},
			actions = {
				{ say = "My offers are weapons, armors, helmets, legs, and shields." },
			},
		},
		{
			line = 62,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "sell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 63,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "have" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 64,
			when = {
				{ words = { "weapon" } },
			},
			actions = {
				{ say = "I have hand axes, axes, spears, maces, battle hammers, swords, rapiers, daggers, and sabres. What's your choice?" },
			},
		},
		{
			line = 65,
			when = {
				{ words = { "helmet" } },
			},
			actions = {
				{ say = "I am selling leather helmets and chain helmets. What do you want?" },
			},
		},
		{
			line = 66,
			when = {
				{ words = { "armor" } },
			},
			actions = {
				{ say = "I am selling leather, chain, and brass armor. What do you need?" },
			},
		},
		{
			line = 67,
			when = {
				{ words = { "shield" } },
			},
			actions = {
				{ say = "I am selling wooden shields and steel shields. What do you want?" },
			},
		},
		{
			line = 68,
			when = {
				{ words = { "trousers" } },
			},
			actions = {
				{ say = "I am selling chain legs. Do you want to buy any?" },
			},
		},
		{
			line = 69,
			when = {
				{ words = { "legs" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 71,
			when = {
				{ words = { "dagger" } },
			},
			actions = {
				{ set = { var = "type", value = 3267 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 5 } },
				{ say = "Do you want to buy a dagger for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 72,
			when = {
				{ words = { "hand" } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 3268 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 8 } },
				{ say = "Do you want to buy a hand axe for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 73,
			when = {
				{ words = { "spear" } },
			},
			actions = {
				{ set = { var = "type", value = 3277 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 10 } },
				{ say = "Do you want to buy a spear for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 74,
			when = {
				{ words = { "rapier" } },
			},
			actions = {
				{ set = { var = "type", value = 3272 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 15 } },
				{ say = "Do you want to buy a rapier for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 75,
			when = {
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 3274 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 20 } },
				{ say = "Do you want to buy an axe for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 76,
			when = {
				{ words = { "sabre" } },
			},
			actions = {
				{ set = { var = "type", value = 3273 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 35 } },
				{ say = "Do you want to buy a sabre for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 77,
			when = {
				{ words = { "sword" } },
			},
			actions = {
				{ set = { var = "type", value = 3264 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 85 } },
				{ say = "Do you want to buy a sword for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 78,
			when = {
				{ words = { "mace" } },
			},
			actions = {
				{ set = { var = "type", value = 3286 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 90 } },
				{ say = "Do you want to buy a mace for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 79,
			when = {
				{ words = { "battle" } },
				{ words = { "hammer" } },
			},
			actions = {
				{ set = { var = "type", value = 3305 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 350 } },
				{ say = "Do you want to buy a battle hammer for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 80,
			when = {
				{ words = { "throwing" } },
				{ words = { "star" } },
			},
			actions = {
				{ set = { var = "type", value = 3287 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 50 } },
				{ say = "Do you want to buy a throwing star for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 82,
			when = {
				{ words = { "chain" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 3358 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 200 } },
				{ say = "Do you want to buy a chain armor for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 83,
			when = {
				{ words = { "brass" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 3359 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 450 } },
				{ say = "Do you want to buy a brass armor for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 84,
			when = {
				{ words = { "leather" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 3361 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 35 } },
				{ say = "Do you want to buy a leather armor for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 85,
			when = {
				{ words = { "chain" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 3352 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 52 } },
				{ say = "Do you want to buy a chain helmet for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 86,
			when = {
				{ words = { "leather" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 3355 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 12 } },
				{ say = "Do you want to buy a leather helmet for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 87,
			when = {
				{ words = { "steel" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 3409 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 240 } },
				{ say = "Do you want to buy a steel shield for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 88,
			when = {
				{ words = { "wooden" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 3412 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 15 } },
				{ say = "Do you want to buy a wooden shield for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 89,
			when = {
				{ words = { "chain" } },
				{ words = { "legs" } },
			},
			actions = {
				{ set = { var = "type", value = 3558 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 80 } },
				{ say = "Do you want to buy chain legs for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 91,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "dagger" } },
			},
			actions = {
				{ set = { var = "type", value = 3267 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 5, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A daggers for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 92,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "hand" } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 3268 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 8, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A hand axes for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 93,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "spear" } },
			},
			actions = {
				{ set = { var = "type", value = 3277 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 10, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A spears for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 94,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "rapier" } },
			},
			actions = {
				{ set = { var = "type", value = 3272 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 15, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A rapiers for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 95,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 3274 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 20, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A axes for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 96,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "sabre" } },
			},
			actions = {
				{ set = { var = "type", value = 3273 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 35, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A sabres for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 97,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "sword" } },
			},
			actions = {
				{ set = { var = "type", value = 3264 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 85, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A swords for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 98,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "mace" } },
			},
			actions = {
				{ set = { var = "type", value = 3286 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 90, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A maces for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 99,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "battle" } },
				{ words = { "hammer" } },
			},
			actions = {
				{ set = { var = "type", value = 3305 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 350, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A battle hammers for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 100,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "throwing" } },
				{ words = { "star" } },
			},
			actions = {
				{ set = { var = "type", value = 3287 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 50, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A throwing stars for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 102,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "chain" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 3358 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 200, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A chain armors for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 103,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "brass" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 3359 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 450, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A brass armors for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 104,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "leather" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 3361 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 35, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A leather armors for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 105,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "chain" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 3352 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 52, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A chain helmets for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 106,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "leather" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 3355 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 12, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A leather helmets for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 107,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "steel" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 3409 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 240, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A steel shields for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 108,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "wooden" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 3412 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 15, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A wooden shields for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 109,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "chain" } },
				{ words = { "legs" } },
			},
			actions = {
				{ set = { var = "type", value = 3558 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 80, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A chain legs for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 111,
			when = {
				{ words = { "sell" } },
				{ words = { "two" } },
				{ words = { "handed" } },
				{ words = { "sword" } },
			},
			actions = {
				{ set = { var = "type", value = 3265 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 450 } },
				{ say = "Do you want to sell a two handed sword for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 112,
			when = {
				{ words = { "sell" } },
				{ words = { "battle" } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 3266 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 80 } },
				{ say = "Do you want to sell a battle axe for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 113,
			when = {
				{ words = { "sell" } },
				{ words = { "dagger" } },
			},
			actions = {
				{ set = { var = "type", value = 3267 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 2 } },
				{ say = "Do you want to sell this garbage? I give you %P gold, ok?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 114,
			when = {
				{ words = { "sell" } },
				{ words = { "hand" } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 3268 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 4 } },
				{ say = "Do you want to sell a hand axe for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 115,
			when = {
				{ words = { "sell" } },
				{ words = { "halberd" } },
			},
			actions = {
				{ set = { var = "type", value = 3269 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 400 } },
				{ say = "Do you want to sell a halberd for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 116,
			when = {
				{ words = { "sell" } },
				{ words = { "club" } },
			},
			actions = {
				{ set = { var = "type", value = 3270 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 1 } },
				{ say = "Are you sure, you want to sell this garbage? Hmm, I give you %P gold, ok?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 117,
			when = {
				{ words = { "sell" } },
				{ words = { "rapier" } },
			},
			actions = {
				{ set = { var = "type", value = 3272 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 5 } },
				{ say = "Do you want to sell a rapier for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 118,
			when = {
				{ words = { "sell" } },
				{ words = { "sabre" } },
			},
			actions = {
				{ set = { var = "type", value = 3273 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 12 } },
				{ say = "Do you want to sell a sabre for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 119,
			when = {
				{ words = { "sell" } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 3274 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 7 } },
				{ say = "Do you want to sell an axe for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 120,
			when = {
				{ words = { "sell" } },
				{ words = { "spear" } },
			},
			actions = {
				{ set = { var = "type", value = 3277 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 3 } },
				{ say = "Do you want to sell this garbage? I give you %P gold, ok?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 121,
			when = {
				{ words = { "sell" } },
				{ words = { "morning" } },
				{ words = { "star" } },
			},
			actions = {
				{ set = { var = "type", value = 3282 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 90 } },
				{ say = "Do you want to sell a morning star for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 122,
			when = {
				{ words = { "sell" } },
				{ words = { "mace" } },
			},
			actions = {
				{ set = { var = "type", value = 3286 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 30 } },
				{ say = "Do you want to sell a mace for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 123,
			when = {
				{ words = { "sell" } },
				{ words = { "short" } },
				{ words = { "sword" } },
			},
			actions = {
				{ set = { var = "type", value = 3294 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 10 } },
				{ say = "Do you want to sell a short sword for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 124,
			when = {
				{ words = { "sell" } },
				{ words = { "battle" } },
				{ words = { "hammer" } },
			},
			actions = {
				{ set = { var = "type", value = 3305 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 120 } },
				{ say = "Do you want to sell a battle hammer for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 125,
			when = {
				{ words = { "sell" } },
				{ words = { "sword" } },
			},
			actions = {
				{ set = { var = "type", value = 3264 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 25 } },
				{ say = "Do you want to sell a sword for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 127,
			when = {
				{ words = { "sell" } },
				{ words = { "leather" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 3361 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 12 } },
				{ say = "Do you want to sell a leather armor for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 128,
			when = {
				{ words = { "sell" } },
				{ words = { "chain" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 3358 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 70 } },
				{ say = "Do you want to sell a chain armor for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 129,
			when = {
				{ words = { "sell" } },
				{ words = { "brass" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 3359 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 150 } },
				{ say = "Do you want to sell a brass armor for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 130,
			when = {
				{ words = { "sell" } },
				{ words = { "plate" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 3357 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 400 } },
				{ say = "Do you want to sell a plate armor for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 131,
			when = {
				{ words = { "sell" } },
				{ words = { "chain" } },
				{ words = { "legs" } },
			},
			actions = {
				{ set = { var = "type", value = 3558 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 25 } },
				{ say = "Do you want to sell chain legs for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 132,
			when = {
				{ words = { "sell" } },
				{ words = { "leather" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 3355 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 4 } },
				{ say = "Do you want to sell a leather helmet for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 133,
			when = {
				{ words = { "sell" } },
				{ words = { "chain" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 3352 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 17 } },
				{ say = "Do you want to sell a chain helmet for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 134,
			when = {
				{ words = { "sell" } },
				{ words = { "steel" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 3351 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 190 } },
				{ say = "Do you want to sell a steel helmet for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 135,
			when = {
				{ words = { "sell" } },
				{ words = { "wooden" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 3412 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 5 } },
				{ say = "Do you want to sell a wooden shield for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 136,
			when = {
				{ words = { "sell" } },
				{ words = { "battle" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 3413 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 95 } },
				{ say = "Do you want to sell a battle shield for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 137,
			when = {
				{ words = { "sell" } },
				{ words = { "steel" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 3409 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 80 } },
				{ say = "Do you want to sell a steel shield for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 139,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "two" } },
				{ words = { "handed" } },
				{ words = { "sword" } },
			},
			actions = {
				{ set = { var = "type", value = 3265 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 450, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A two handed swords for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 140,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "battle" } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 3266 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 80, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A battle axes for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 141,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "dagger" } },
			},
			actions = {
				{ set = { var = "type", value = 3267 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 2, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell this garbage? I give you %P gold, ok?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 142,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "hand" } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 3268 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 4, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A hand axes for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 143,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "halberd" } },
			},
			actions = {
				{ set = { var = "type", value = 3269 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 400, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A halberds for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 144,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "club" } },
			},
			actions = {
				{ set = { var = "type", value = 3270 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 1, rhs = { capture = 1 } } } } },
				{ say = "Are you sure, you want to sell this garbage? Hmm, I give you %P gold, ok?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 145,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "rapier" } },
			},
			actions = {
				{ set = { var = "type", value = 3272 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 5, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A rapiers for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 146,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "sabre" } },
			},
			actions = {
				{ set = { var = "type", value = 3273 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 12, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A sabres for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 147,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 3274 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 7, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A axes for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 148,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "spear" } },
			},
			actions = {
				{ set = { var = "type", value = 3277 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 3, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell this garbage? I give you %P gold, ok?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 149,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "morning" } },
				{ words = { "star" } },
			},
			actions = {
				{ set = { var = "type", value = 3282 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 90, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A morning stars for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 150,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "mace" } },
			},
			actions = {
				{ set = { var = "type", value = 3286 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 30, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A maces for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 151,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "short" } },
				{ words = { "sword" } },
			},
			actions = {
				{ set = { var = "type", value = 3294 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 10, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A short swords for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 152,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "battle" } },
				{ words = { "hammer" } },
			},
			actions = {
				{ set = { var = "type", value = 3305 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 120, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A battle hammers for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 153,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "sword" } },
			},
			actions = {
				{ set = { var = "type", value = 3264 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 25, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A swords for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 155,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "leather" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 3361 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 12, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A leather armors for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 156,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "chain" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 3358 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 70, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A chain armors for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 157,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "brass" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 3359 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 150, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A brass armors for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 158,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "plate" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 3357 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 400, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A plate armors for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 159,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "chain" } },
				{ words = { "legs" } },
			},
			actions = {
				{ set = { var = "type", value = 3558 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 25, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A chain legss for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 160,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "leather" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 3355 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 4, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A leather helmets for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 161,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "chain" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 3352 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 17, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A chain helmets for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 162,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "steel" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 3351 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 190, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A steel helmets for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 163,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "wooden" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 3412 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 5, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A wooden shields for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 164,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "battle" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 3413 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 95, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A battle shields for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 165,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "steel" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 3409 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 80, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A steel shields for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 167,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
				{ expr = { countMoney = true }, op = ">=", rhs = { session = "price" } },
			},
			actions = {
				{ say = "Thank you. Here it is." },
				{ deleteMoney = true },
				{ create = { item = { session = "type" }, count = 1 } },
			},
		},
		{
			line = 168,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "Sorry, you do not have enough gold." },
			},
		},
		{
			line = 169,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
			},
			actions = {
				{ say = "Maybe you will buy it another time." },
			},
		},
		{
			line = 171,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
				{ words = { "yes" } },
				{ expr = { count = { session = "type" } }, op = ">=", rhs = { session = "amount" } },
			},
			actions = {
				{ say = "Ok. Here is your money." },
				{ delete = { item = { session = "type" }, count = 1 } },
				{ createMoney = true },
			},
		},
		{
			line = 172,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "Sorry, you do not have one." },
			},
		},
		{
			line = 173,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
				{ words = { "yes" } },
				{ expr = { session = "amount" }, op = ">", rhs = 1 },
			},
			actions = {
				{ say = "Sorry, you do not have so much." },
			},
		},
		{
			line = 174,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
			},
			actions = {
				{ say = "Maybe next time." },
			},
		},
		{
			line = 176,
			when = {
				{ words = { "sell" } },
				{ words = { "magic" } },
				{ words = { "plate" } },
				{ words = { "armor" } },
			},
			actions = {
				{ say = "WOW! Do you really want to sell me a MAGIC plate armor?" },
				{ set = { var = "topic", value = 3 } },
			},
		},
		{
			line = 177,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 3 },
				{ words = { "yes" } },
			},
			actions = {
				{ set = { var = "type", value = 3366 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 6400 } },
				{ say = "Oh, unbelievable! I would pay %P gold for this wonderful piece of armor. Are you still interested?" },
				{ set = { var = "topic", value = 4 } },
			},
		},
		{
			line = 178,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 3 },
			},
			actions = {
				{ say = "Hmmm, what a pity! I have been looking for such an armor since a long time." },
			},
		},
		{
			line = 179,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 4 },
				{ words = { "yes" } },
				{ expr = { count = { session = "type" } }, op = ">=", rhs = { session = "amount" } },
			},
			actions = {
				{ say = "Finally it is mine! Here is your money. Can I be of any further help?" },
				{ delete = { item = { session = "type" }, count = 1 } },
				{ createMoney = true },
			},
		},
		{
			line = 180,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 4 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "Argl! You do not have one! Trying to tease me? Get lost or I call the guards!" },
				{ idle = true },
			},
		},
		{
			line = 181,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 4 },
			},
			actions = {
				{ say = "Maybe my offer is too low? Unfortunately I can not bring up more money, I am just a smith." },
			},
		},
	},
}))

npc:register()
