-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: riddler.npc

local npc = NpcType("Riddler")
npc:appearance({ lookType = 48, lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0 })
npc:movement({ radius = 5, speed = 10, goStrength = 10 })
npc:health(100)
npc:sex(1)
npc:race(48)

npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = {
		{
			line = 16,
			when = {
				{ situation = "address" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "%N! HEHEHEHE! Another fool! Excellent!" },
			},
		},
		{
			line = 17,
			when = {
				{ situation = "address" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 18,
			when = {
				{ situation = "address" },
				{ select = true },
			},
			actions = {
				{ idle = true },
			},
		},
		{
			line = 19,
			when = {
				{ situation = "busy" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Wait %N, you'll die next!" },
				{ queue = true },
			},
		},
		{
			line = 20,
			when = {
				{ situation = "busy" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 21,
			when = {
				{ situation = "busy" },
				{ select = true },
			},
			actions = {
				{ nop = true },
			},
		},
		{
			line = 22,
			when = {
				{ situation = "vanish" },
				{ select = true },
			},
			actions = {
				{ say = "COWARD! CHICKEN! HEHEHEHE!" },
			},
		},
		{
			line = 24,
			when = {
				{ words = { "bye" } },
			},
			actions = {
				{ say = "HEHEHE! I knew you don't have the stomach." },
				{ idle = true },
			},
		},
		{
			line = 25,
			when = {
				{ words = { "name" } },
			},
			actions = {
				{ say = "I am known as the riddler. That is all you need to know." },
			},
		},
		{
			line = 26,
			when = {
				{ words = { "job" } },
			},
			actions = {
				{ say = "I am the guardian of the paradox tower." },
			},
		},
		{
			line = 27,
			when = {
				{ words = { "time" } },
			},
			actions = {
				{ say = "It is the age of the talon." },
			},
		},
		{
			line = 28,
			when = {
				{ words = { "tower" } },
			},
			actions = {
				{ say = "This tower, of course, silly one. It holds my master's treasure." },
			},
		},
		{
			line = 29,
			when = {
				{ words = { "paradox" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 30,
			when = {
				{ words = { "master" } },
			},
			actions = {
				{ say = "His name is none of your business." },
			},
		},
		{
			line = 31,
			when = {
				{ words = { "guard" } },
			},
			actions = {
				{ say = "I am guarding the treasures of the tower. Only those who pass the test of the three sigils may pass." },
			},
		},
		{
			line = 32,
			when = {
				{ words = { "treasure" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 33,
			when = {
				{ words = { "test" } },
			},
			actions = {
				{ say = "Death awaits those who fail the test of the three seals! Do you really want me to test you?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 34,
			when = {
				{ words = { "sigil" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 35,
			when = {
				{ words = { "key" } },
			},
			actions = {
				{ say = "The key of this tower! You will never find it! A malicious plant spirit is guarding it!" },
			},
		},
		{
			line = 36,
			when = {
				{ words = { "door" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 38,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
				{ expr = { questValue = 212 }, op = "=", rhs = 0 },
			},
			actions = {
				{ say = "FOOL! Now you're doomed! But well ... So be it! Let's start out with the Seal of Knowledge and the first question: What name did the necromant king choose for himself?" },
				{ setQuestValue = { id = 212, value = 1 } },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 39,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
				{ expr = { questValue = 212 }, op = "=", rhs = 1 },
			},
			actions = {
				{ say = "So you think you're smart! But well ... So be it! Let's start out with the Seal of Knowledge and the first question: What do I have in my pocket?" },
				{ set = { var = "topic", value = 14 } },
			},
		},
		{
			line = 40,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "no" } },
			},
			actions = {
				{ say = "HEHEHE! I knew you wouldn't have the stomach." },
				{ idle = true },
			},
		},
		{
			line = 42,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 14 },
				{ select = true },
			},
			actions = {
				{ say = "WRONG!" },
				{ idle = true },
				{ effectOpp = 11 },
				{ setQuestValue = { id = 212, value = 0 } },
				{ teleport = { x = 32725, y = 31589, z = 12 } },
				{ effectOpp = 11 },
			},
		},
		{
			line = 44,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
				{ words = { "goshnar" } },
				{ select = true },
			},
			actions = {
				{ say = "HOHO! You have learned your lesson well. Question number two then: Who or what is the feared Hugo?" },
				{ set = { var = "topic", value = 3 } },
			},
		},
		{
			line = 45,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
				{ select = true },
			},
			actions = {
				{ say = "WRONG!" },
				{ idle = true },
				{ effectOpp = 11 },
				{ setQuestValue = { id = 212, value = 0 } },
				{ teleport = { x = 32725, y = 31589, z = 12 } },
				{ effectOpp = 11 },
			},
		},
		{
			line = 47,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 3 },
				{ expr = { questValue = 211 }, op = "=", rhs = 4 },
				{ words = { "demonbunny" } },
				{ select = true },
			},
			actions = {
				{ say = "HOHO! Right again. All right. The final question of the first seal: Who was the first warrior to follow the path of the Mooh'Tah?" },
				{ set = { var = "topic", value = 4 } },
			},
		},
		{
			line = 48,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 3 },
				{ expr = { questValue = 211 }, op = "<>", rhs = 4 },
				{ words = { "demonbunny" } },
				{ select = true },
			},
			actions = {
				{ say = "Hmmm, so you think cheating will get you through that test? Then your final question of the first seal is: What is the meaning of life?" },
				{ set = { var = "topic", value = 13 } },
			},
		},
		{
			line = 49,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 3 },
				{ expr = { questValue = 211 }, op = "=", rhs = 4 },
				{ words = { "demonrabbit" } },
				{ select = true },
			},
			actions = {
				{ say = "HOHO! Right again. All right. The final question of the first seal: Who was the first warrior to follow the path of the Mooh'Tah?" },
				{ set = { var = "topic", value = 4 } },
			},
		},
		{
			line = 50,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 3 },
				{ expr = { questValue = 211 }, op = "<>", rhs = 4 },
				{ words = { "demonrabbit" } },
				{ select = true },
			},
			actions = {
				{ say = "Hmmm, so you think cheating will get you through that test? Then your final question of the first seal is: What is the meaning of life?" },
				{ set = { var = "topic", value = 13 } },
			},
		},
		{
			line = 51,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 3 },
				{ select = true },
			},
			actions = {
				{ say = "WRONG!" },
				{ idle = true },
				{ effectOpp = 11 },
				{ setQuestValue = { id = 212, value = 0 } },
				{ teleport = { x = 32725, y = 31589, z = 12 } },
				{ effectOpp = 11 },
			},
		},
		{
			line = 52,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 13 },
				{ select = true },
			},
			actions = {
				{ say = "WRONG! Next time get your own answers. To hell with thee, cheater!" },
				{ idle = true },
				{ effectOpp = 11 },
				{ setQuestValue = { id = 212, value = 0 } },
				{ teleport = { x = 32725, y = 31589, z = 12 } },
				{ effectOpp = 11 },
			},
		},
		{
			line = 54,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 4 },
				{ words = { "Tha'kull" } },
				{ select = true },
			},
			actions = {
				{ say = "HOHO! Lucky you. You have passed the first seal! So ... would you like to continue with the Seal of the Mind?" },
				{ set = { var = "topic", value = 5 } },
			},
		},
		{
			line = 55,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 4 },
				{ select = true },
			},
			actions = {
				{ say = "WRONG!" },
				{ idle = true },
				{ effectOpp = 11 },
				{ setQuestValue = { id = 212, value = 0 } },
				{ teleport = { x = 32725, y = 31589, z = 12 } },
				{ effectOpp = 11 },
			},
		},
		{
			line = 57,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 5 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "As you wish, foolish one! Here is my first question: Its lighter then a feather but no living creature can hold it for ten minutes?" },
				{ set = { var = "topic", value = 6 } },
			},
		},
		{
			line = 58,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 5 },
			},
			actions = {
				{ say = "HEHEHE! I knew you don't have the stomach." },
				{ setQuestValue = { id = 212, value = 0 } },
				{ idle = true },
			},
		},
		{
			line = 60,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 6 },
				{ words = { "breath" } },
				{ select = true },
			},
			actions = {
				{ say = "That was an easy one. Let's try the second: If you name it, you break it." },
				{ set = { var = "topic", value = 7 } },
			},
		},
		{
			line = 61,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 6 },
				{ select = true },
			},
			actions = {
				{ say = "WRONG!" },
				{ idle = true },
				{ effectOpp = 11 },
				{ setQuestValue = { id = 212, value = 0 } },
				{ teleport = { x = 32725, y = 31589, z = 12 } },
				{ effectOpp = 11 },
			},
		},
		{
			line = 63,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 7 },
				{ words = { "silence" } },
				{ select = true },
			},
			actions = {
				{ say = "Hm. I bet you think you're smart. All right. How about this: What does everybody want to become but nobody to be?" },
				{ set = { var = "topic", value = 8 } },
			},
		},
		{
			line = 64,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 7 },
				{ select = true },
			},
			actions = {
				{ say = "WRONG!" },
				{ idle = true },
				{ effectOpp = 11 },
				{ setQuestValue = { id = 212, value = 0 } },
				{ teleport = { x = 32725, y = 31589, z = 12 } },
				{ effectOpp = 11 },
			},
		},
		{
			line = 66,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 8 },
				{ words = { "old" } },
				{ select = true },
			},
			actions = {
				{ say = "ARGH! You did it again! Well all right. Do you wish to break the Seal of Madness?" },
				{ set = { var = "topic", value = 9 } },
			},
		},
		{
			line = 67,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 8 },
				{ select = true },
			},
			actions = {
				{ say = "WRONG!" },
				{ idle = true },
				{ effectOpp = 11 },
				{ setQuestValue = { id = 212, value = 0 } },
				{ teleport = { x = 32725, y = 31589, z = 12 } },
				{ effectOpp = 11 },
			},
		},
		{
			line = 69,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 9 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "GOOD! So I will get you at last. Answer this: What is your favourite colour?" },
				{ set = { var = "topic", value = 10 } },
			},
		},
		{
			line = 70,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 9 },
			},
			actions = {
				{ say = "HEHEHE! I knew you don't have the stomach." },
				{ setQuestValue = { id = 212, value = 0 } },
				{ idle = true },
			},
		},
		{
			line = 72,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 10 },
				{ words = { "red" } },
				{ select = true },
			},
			actions = {
				{ say = "UHM UH OH ... How could you guess that? Are you mad??? All right. Question number two: What is the opposite?" },
				{ setQuestValue = { id = 2, value = 1 } },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 73,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 10 },
				{ words = { "blue" } },
				{ select = true },
			},
			actions = {
				{ say = "UHM UH OH ... How could you guess that? Are you mad??? All right. Question number two: What is the opposite?" },
				{ setQuestValue = { id = 2, value = 2 } },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 74,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 10 },
				{ words = { "black" } },
				{ select = true },
			},
			actions = {
				{ say = "UHM UH OH ... How could you guess that? Are you mad??? All right. Question number two: What is the opposite?" },
				{ setQuestValue = { id = 2, value = 3 } },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 75,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 10 },
				{ words = { "white" } },
				{ select = true },
			},
			actions = {
				{ say = "UHM UH OH ... How could you guess that? Are you mad??? All right. Question number two: What is the opposite?" },
				{ setQuestValue = { id = 2, value = 4 } },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 76,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 10 },
				{ words = { "orange" } },
				{ select = true },
			},
			actions = {
				{ say = "UHM UH OH ... How could you guess that? Are you mad??? All right. Question number two: What is the opposite?" },
				{ setQuestValue = { id = 2, value = 5 } },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 77,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 10 },
				{ words = { "green" } },
				{ select = true },
			},
			actions = {
				{ say = "UHM UH OH ... How could you guess that? Are you mad??? All right. Question number two: What is the opposite?" },
				{ setQuestValue = { id = 2, value = 6 } },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 78,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 10 },
				{ words = { "yellow" } },
				{ select = true },
			},
			actions = {
				{ say = "UHM UH OH ... How could you guess that? Are you mad??? All right. Question number two: What is the opposite?" },
				{ setQuestValue = { id = 2, value = 7 } },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 79,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 10 },
				{ words = { "brown" } },
				{ select = true },
			},
			actions = {
				{ say = "UHM UH OH ... How could you guess that? Are you mad??? All right. Question number two: What is the opposite?" },
				{ setQuestValue = { id = 2, value = 8 } },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 80,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 10 },
				{ words = { "violet" } },
				{ select = true },
			},
			actions = {
				{ say = "UHM UH OH ... How could you guess that? Are you mad??? All right. Question number two: What is the opposite?" },
				{ setQuestValue = { id = 2, value = 9 } },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 81,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 10 },
				{ words = { "pink" } },
				{ select = true },
			},
			actions = {
				{ say = "UHM UH OH ... How could you guess that? Are you mad??? All right. Question number two: What is the opposite?" },
				{ setQuestValue = { id = 2, value = 10 } },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 82,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 10 },
				{ words = { "silver" } },
				{ select = true },
			},
			actions = {
				{ say = "UHM UH OH ... How could you guess that? Are you mad??? All right. Question number two: What is the opposite?" },
				{ setQuestValue = { id = 2, value = 11 } },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 83,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 10 },
				{ words = { "gold" } },
				{ select = true },
			},
			actions = {
				{ say = "UHM UH OH ... How could you guess that? Are you mad??? All right. Question number two: What is the opposite?" },
				{ setQuestValue = { id = 2, value = 12 } },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 84,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 10 },
				{ words = { "grey" } },
				{ select = true },
			},
			actions = {
				{ say = "UHM UH OH ... How could you guess that? Are you mad??? All right. Question number two: What is the opposite?" },
				{ setQuestValue = { id = 2, value = 13 } },
				{ set = { var = "topic", value = 11 } },
			},
		},
		{
			line = 86,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 10 },
				{ select = true },
			},
			actions = {
				{ say = "WRONG!" },
				{ idle = true },
				{ effectOpp = 11 },
				{ setQuestValue = { id = 212, value = 0 } },
				{ teleport = { x = 32725, y = 31589, z = 12 } },
				{ effectOpp = 11 },
			},
		},
		{
			line = 88,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 11 },
				{ words = { "nothing" } },
				{ select = true },
			},
			actions = {
				{ say = "NO! NO! NO! That can't be true. You're not only mad, you are a complete idiot! Ah well. Here is the last question: What is 1 plus 1?" },
				{ set = { var = "topic", value = 12 } },
			},
		},
		{
			line = 89,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 11 },
				{ words = { "none" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 90,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 11 },
				{ select = true },
			},
			actions = {
				{ say = "SORRY I AM NOT ALLOWD TO HELP HEHEHE!" },
				{ idle = true },
				{ effectOpp = 11 },
				{ setQuestValue = { id = 212, value = 0 } },
				{ teleport = { x = 32725, y = 31589, z = 12 } },
				{ effectOpp = 11 },
			},
		},
		{
			line = 92,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 12 },
				{ expr = { questValue = 1 }, op = "=", rhs = 1 },
				{ words = { "49$" } },
				{ select = true },
			},
			actions = {
				{ say = "DAMN YOUUUUUUUUUUUUUUUUUUUUUU!" },
				{ idle = true },
				{ effectOpp = 11 },
				{ setQuestValue = { id = 212, value = 0 } },
				{ teleport = { x = 32478, y = 31905, z = 1 } },
				{ effectOpp = 11 },
			},
		},
		{
			line = 93,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 12 },
				{ expr = { questValue = 1 }, op = "=", rhs = 2 },
				{ words = { "94$" } },
				{ select = true },
			},
			actions = {
				{ say = "DAMN YOUUUUUUUUUUUUUUUUUUUUUU!" },
				{ idle = true },
				{ effectOpp = 11 },
				{ setQuestValue = { id = 212, value = 0 } },
				{ teleport = { x = 32478, y = 31905, z = 1 } },
				{ effectOpp = 11 },
			},
		},
		{
			line = 94,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 12 },
				{ expr = { questValue = 1 }, op = "=", rhs = 3 },
				{ words = { "13$" } },
				{ select = true },
			},
			actions = {
				{ say = "DAMN YOUUUUUUUUUUUUUUUUUUUUUU!" },
				{ idle = true },
				{ effectOpp = 11 },
				{ setQuestValue = { id = 212, value = 0 } },
				{ teleport = { x = 32478, y = 31905, z = 1 } },
				{ effectOpp = 11 },
			},
		},
		{
			line = 95,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 12 },
				{ expr = { questValue = 1 }, op = "=", rhs = 4 },
				{ words = { "1$" } },
				{ select = true },
			},
			actions = {
				{ say = "DAMN YOUUUUUUUUUUUUUUUUUUUUUU!" },
				{ idle = true },
				{ effectOpp = 11 },
				{ setQuestValue = { id = 212, value = 0 } },
				{ teleport = { x = 32478, y = 31905, z = 1 } },
				{ effectOpp = 11 },
			},
		},
		{
			line = 96,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 12 },
				{ select = true },
			},
			actions = {
				{ say = "WRONG!" },
				{ idle = true },
				{ effectOpp = 11 },
				{ setQuestValue = { id = 212, value = 0 } },
				{ teleport = { x = 32725, y = 31589, z = 12 } },
				{ effectOpp = 11 },
			},
		},
	},
}))

npc:register()
