-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: rudolph.npc

local npc = NpcType("Rudolph")
npc:appearance({ lookType = 128, lookHead = 41, lookBody = 29, lookLegs = 78, lookFeet = 76 })
npc:movement({ radius = 1, speed = 10, goStrength = 10 })
npc:health(100)
npc:sex(1)
npc:race(1)

npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = {
		{
			line = 13,
			when = {
				{ situation = "address" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Oh, a customer. Hello %N." },
			},
		},
		{
			line = 14,
			when = {
				{ situation = "address" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 15,
			when = {
				{ situation = "address" },
				{ select = true },
			},
			actions = {
				{ idle = true },
			},
		},
		{
			line = 16,
			when = {
				{ situation = "busy" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Oh, so wait a little, %N." },
				{ queue = true },
			},
		},
		{
			line = 17,
			when = {
				{ situation = "busy" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 18,
			when = {
				{ situation = "busy" },
				{ select = true },
			},
			actions = {
				{ nop = true },
			},
		},
		{
			line = 19,
			when = {
				{ situation = "vanish" },
				{ select = true },
			},
			actions = {
				{ say = "Oh, good bye." },
			},
		},
		{
			line = 21,
			when = {
				{ words = { "bye" } },
			},
			actions = {
				{ say = "Oh, good bye." },
				{ idle = true },
			},
		},
		{
			line = 22,
			when = {
				{ words = { "name" } },
			},
			actions = {
				{ say = "I'm Rudolph, you know." },
			},
		},
		{
			line = 23,
			when = {
				{ words = { "job" } },
			},
			actions = {
				{ say = "Oh, I am a tailor, can't you see?" },
			},
		},
		{
			line = 24,
			when = {
				{ words = { "time" } },
			},
			actions = {
				{ say = "Oh, now it's %T." },
			},
		},
		{
			line = 25,
			when = {
				{ words = { "king" } },
			},
			actions = {
				{ say = "Oh, the king. What a well dressed man he is." },
			},
		},
		{
			line = 26,
			when = {
				{ words = { "tibianus" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 27,
			when = {
				{ words = { "army" } },
			},
			actions = {
				{ say = "Oh, such handsome guys and such ugly uniforms." },
			},
		},
		{
			line = 28,
			when = {
				{ words = { "ferumbras" } },
			},
			actions = {
				{ say = "Oh, dear." },
			},
		},
		{
			line = 29,
			when = {
				{ words = { "excalibug" } },
			},
			actions = {
				{ say = "Oh, that thing must be dangerous. One could hurt himself quite badly with it I guess." },
			},
		},
		{
			line = 30,
			when = {
				{ words = { "thais" } },
			},
			actions = {
				{ say = "Oh, what a lovely city it was once." },
			},
		},
		{
			line = 31,
			when = {
				{ words = { "tibia" } },
			},
			actions = {
				{ say = "Oh, there is not much sense for fashion in this world." },
			},
		},
		{
			line = 32,
			when = {
				{ words = { "carlin" } },
			},
			actions = {
				{ say = "Oh, these women ... oh, go away." },
			},
		},
		{
			line = 33,
			when = {
				{ words = { "edron" } },
			},
			actions = {
				{ say = "Oh, what a lovely city it is." },
			},
		},
		{
			line = 34,
			when = {
				{ words = { "news" } },
			},
			actions = {
				{ say = "Oh, we tailors learn much, but don't talk about it. It's the tailors' code of honor, you know." },
			},
		},
		{
			line = 35,
			when = {
				{ words = { "rumors" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 37,
			when = {
				{ words = { "offer" } },
			},
			actions = {
				{ say = "Oh, I have wonderful clothes and shoes." },
			},
		},
		{
			line = 38,
			when = {
				{ words = { "goods" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 39,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "sell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 40,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "have" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 41,
			when = {
				{ words = { "clothes" } },
			},
			actions = {
				{ say = "Oh, I have wonderful jackets, capes, tunics, leather legs, and scarfs." },
			},
		},
		{
			line = 42,
			when = {
				{ words = { "shoes" } },
			},
			actions = {
				{ say = "Oh, I have wonderful leather boots and sandals." },
			},
		},
		{
			line = 44,
			when = {
				{ words = { "jacket" } },
			},
			actions = {
				{ set = { var = "type", value = 2650 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 12 } },
				{ say = "Oh, do you want to buy one of my wonderful jackets for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 45,
			when = {
				{ words = { "tunic" } },
			},
			actions = {
				{ set = { var = "type", value = 2652 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 10 } },
				{ say = "Oh, do you want to buy one of my wonderful green tunics for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 46,
			when = {
				{ words = { "cape" } },
			},
			actions = {
				{ set = { var = "type", value = 2654 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 9 } },
				{ say = "Oh, do you want to buy one of my wonderful capes for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 47,
			when = {
				{ words = { "leather" } },
				{ words = { "legs" } },
			},
			actions = {
				{ set = { var = "type", value = 2649 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 10 } },
				{ say = "Oh, do you want to buy one of my wonderful leather legs for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 48,
			when = {
				{ words = { "scarf" } },
			},
			actions = {
				{ set = { var = "type", value = 2661 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 15 } },
				{ say = "Oh, do you want to buy one of my wonderful silky scarfs for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 49,
			when = {
				{ words = { "sandals" } },
			},
			actions = {
				{ set = { var = "type", value = 2642 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 2 } },
				{ say = "Oh, do you want to buy one of my wonderful sandals for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 50,
			when = {
				{ words = { "leather" } },
				{ words = { "boot" } },
			},
			actions = {
				{ set = { var = "type", value = 2643 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 2 } },
				{ say = "Oh, do you want to buy one of my wonderful leather boots for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 52,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "jacket" } },
			},
			actions = {
				{ set = { var = "type", value = 2650 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 12, rhs = { capture = 1 } } } } },
				{ say = "Oh, do you want to buy %A of my wonderful jackets for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 53,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "tunic" } },
			},
			actions = {
				{ set = { var = "type", value = 2652 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 10, rhs = { capture = 1 } } } } },
				{ say = "Oh, do you want to buy %A of my wonderful green tunics for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 54,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "cape" } },
			},
			actions = {
				{ set = { var = "type", value = 2654 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 9, rhs = { capture = 1 } } } } },
				{ say = "Oh, do you want to buy %A of my wonderful capes for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 55,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "leather" } },
				{ words = { "legs" } },
			},
			actions = {
				{ set = { var = "type", value = 2649 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 10, rhs = { capture = 1 } } } } },
				{ say = "Oh, do you want to buy %A of my wonderful leather legs for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 56,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "scar" } },
			},
			actions = {
				{ set = { var = "type", value = 2661 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 15, rhs = { capture = 1 } } } } },
				{ say = "Oh, do you want to buy %A of my wonderful silky scarves for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 57,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "sandals" } },
			},
			actions = {
				{ set = { var = "type", value = 2642 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 2, rhs = { capture = 1 } } } } },
				{ say = "Oh, do you want to buy %A of my wonderful sandals for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 58,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "leather" } },
				{ words = { "boot" } },
			},
			actions = {
				{ set = { var = "type", value = 2643 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 2, rhs = { capture = 1 } } } } },
				{ say = "Oh, do you want to buy %A of my wonderful leather boots for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 60,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
				{ expr = { countMoney = true }, op = ">=", rhs = { session = "price" } },
			},
			actions = {
				{ say = "Oh, here you are." },
				{ deleteMoney = true },
				{ create = { item = { session = "type" } } },
			},
		},
		{
			line = 61,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "Oh, you do not have enough money." },
			},
		},
		{
			line = 62,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
			},
			actions = {
				{ say = "Oh, but next time." },
			},
		},
	},
}))

npc:register()
