-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: thomas.npc

local npc = NpcType("Thomas")
npc:appearance({ lookType = 128, lookHead = 116, lookBody = 11, lookLegs = 101, lookFeet = 76 })
npc:movement({ radius = 2, speed = 7, goStrength = 7 })
npc:health(100)
npc:sex(1)
npc:race(1)

npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = {
		{
			line = 13,
			when = {
				{ situation = "address" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Feel welcome, %N." },
			},
		},
		{
			line = 14,
			when = {
				{ situation = "address" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 15,
			when = {
				{ situation = "address" },
				{ select = true },
			},
			actions = {
				{ idle = true },
			},
		},
		{
			line = 16,
			when = {
				{ situation = "busy" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Don't be that impatient, %N. Wait a moment!" },
				{ queue = true },
			},
		},
		{
			line = 17,
			when = {
				{ situation = "busy" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 18,
			when = {
				{ situation = "busy" },
				{ select = true },
			},
			actions = {
				{ nop = true },
			},
		},
		{
			line = 19,
			when = {
				{ situation = "vanish" },
				{ select = true },
			},
			actions = {
				{ say = "Bye." },
			},
		},
		{
			line = 21,
			when = {
				{ words = { "bye" } },
			},
			actions = {
				{ say = "Bye." },
				{ idle = true },
			},
		},
		{
			line = 22,
			when = {
				{ words = { "name" } },
			},
			actions = {
				{ say = "Thomas." },
			},
		},
		{
			line = 23,
			when = {
				{ words = { "job" } },
			},
			actions = {
				{ say = "Selling spellbooks, notebooks, scrolls, documents, parchments, inkwells, and the like." },
			},
		},
		{
			line = 24,
			when = {
				{ words = { "time" } },
			},
			actions = {
				{ say = "No idea." },
			},
		},
		{
			line = 25,
			when = {
				{ words = { "king" } },
			},
			actions = {
				{ say = "Know nothing interesting about him." },
			},
		},
		{
			line = 26,
			when = {
				{ words = { "tibianus" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 27,
			when = {
				{ words = { "army" } },
			},
			actions = {
				{ say = "Ask in the castle." },
			},
		},
		{
			line = 28,
			when = {
				{ words = { "ferumbras" } },
			},
			actions = {
				{ say = "Only heard of him." },
			},
		},
		{
			line = 29,
			when = {
				{ words = { "excalibug" } },
			},
			actions = {
				{ say = "No idea." },
			},
		},
		{
			line = 30,
			when = {
				{ words = { "thais" } },
			},
			actions = {
				{ say = "Never been there." },
			},
		},
		{
			line = 31,
			when = {
				{ words = { "tibia" } },
			},
			actions = {
				{ say = "Like it here best." },
			},
		},
		{
			line = 32,
			when = {
				{ words = { "carlin" } },
			},
			actions = {
				{ say = "Never been there." },
			},
		},
		{
			line = 33,
			when = {
				{ words = { "edron" } },
			},
			actions = {
				{ say = "This town." },
			},
		},
		{
			line = 34,
			when = {
				{ words = { "news" } },
			},
			actions = {
				{ say = "Nothing interesting." },
			},
		},
		{
			line = 35,
			when = {
				{ words = { "rumors" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 37,
			when = {
				{ words = { "offer" } },
			},
			actions = {
				{ say = "Selling scrolls, documents, parchments, spellbooks, books, and inkwells." },
			},
		},
		{
			line = 38,
			when = {
				{ words = { "goods" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 39,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "sell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 40,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "have" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 41,
			when = {
				{ words = { "book" } },
			},
			actions = {
				{ say = "I offer different kind of books: brown, black and small books. Which book do you want?" },
			},
		},
		{
			line = 43,
			when = {
				{ words = { "scroll" } },
			},
			actions = {
				{ set = { var = "type", value = 2815 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 5 } },
				{ say = "Do you want to buy a scroll for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 44,
			when = {
				{ words = { "document" } },
			},
			actions = {
				{ set = { var = "type", value = 2834 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 12 } },
				{ say = "Do you want to buy a document for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 45,
			when = {
				{ words = { "parchment" } },
			},
			actions = {
				{ set = { var = "type", value = 2835 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 8 } },
				{ say = "Do you want to buy a parchment for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 46,
			when = {
				{ words = { "spellbook" } },
			},
			actions = {
				{ set = { var = "type", value = 3059 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 150 } },
				{ say = "Do you want to buy a spellbook for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 47,
			when = {
				{ words = { "brown" } },
				{ words = { "book" } },
			},
			actions = {
				{ set = { var = "type", value = 2837 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 15 } },
				{ say = "Do you want to buy a brown book for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 48,
			when = {
				{ words = { "black" } },
				{ words = { "book" } },
			},
			actions = {
				{ set = { var = "type", value = 2838 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 15 } },
				{ say = "Do you want to buy a black book for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 49,
			when = {
				{ words = { "small" } },
				{ words = { "book" } },
			},
			actions = {
				{ set = { var = "type", value = 2839 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 15 } },
				{ say = "Do you want to buy a small book for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 50,
			when = {
				{ words = { "inkwell" } },
			},
			actions = {
				{ set = { var = "type", value = 3509 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 8 } },
				{ say = "Do you want to buy an inkwell for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 52,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "scroll" } },
			},
			actions = {
				{ set = { var = "type", value = 2815 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 5, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A scrolls for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 53,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "document" } },
			},
			actions = {
				{ set = { var = "type", value = 2834 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 12, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A documents for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 54,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "parchment" } },
			},
			actions = {
				{ set = { var = "type", value = 2835 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 8, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A parchments for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 55,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "spellbook" } },
			},
			actions = {
				{ set = { var = "type", value = 3059 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 150, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A spellbooks for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 56,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "brown" } },
				{ words = { "book" } },
			},
			actions = {
				{ set = { var = "type", value = 2837 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 15, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A brown books for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 57,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "black" } },
				{ words = { "book" } },
			},
			actions = {
				{ set = { var = "type", value = 2838 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 15, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A black books for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 58,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "small" } },
				{ words = { "book" } },
			},
			actions = {
				{ set = { var = "type", value = 2839 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 15, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A small books for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 59,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "inkwell" } },
			},
			actions = {
				{ set = { var = "type", value = 3509 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 8, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A inkwells for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 61,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
				{ expr = { countMoney = true }, op = ">=", rhs = { session = "price" } },
			},
			actions = {
				{ say = "Here you are." },
				{ deleteMoney = true },
				{ create = { item = { session = "type" }, count = 1 } },
			},
		},
		{
			line = 62,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "Come back, when you have enough money." },
			},
		},
		{
			line = 63,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
			},
			actions = {
				{ say = "Hmm, but next time." },
			},
		},
	},
}))

npc:register()
