-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: topsy.npc

local npc = NpcType("Topsy")
npc:appearance({ lookType = 139, lookHead = 78, lookBody = 52, lookLegs = 64, lookFeet = 115 })
npc:movement({ radius = 2, speed = 3, goStrength = 3 })
npc:health(100)
npc:sex(0)
npc:race(1)

npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = {
		{
			line = 13,
			when = {
				{ situation = "address" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ say = "Hello, dear %N. How can I help you?" },
			},
		},
		{
			line = 14,
			when = {
				{ situation = "address" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 15,
			when = {
				{ situation = "address" },
				{ select = true },
			},
			actions = {
				{ idle = true },
			},
		},
		{
			line = 16,
			when = {
				{ situation = "busy" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ say = "My apologies, but I really must talk to this customer first. Sugar, I am busy with a customer at the moment. Please have some patience." },
				{ queue = true },
			},
		},
		{
			line = 17,
			when = {
				{ situation = "busy" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 18,
			when = {
				{ situation = "busy" },
				{ select = true },
			},
			actions = {
				{ nop = true },
			},
		},
		{
			line = 19,
			when = {
				{ situation = "vanish" },
				{ select = true },
			},
			actions = {
				{ say = "Good bye. Do come again!" },
			},
		},
		{
			line = 21,
			when = {
				{ words = { "bye" } },
			},
			actions = {
				{ say = "Good bye. Do come again!" },
				{ idle = true },
			},
		},
		{
			line = 22,
			when = {
				{ words = { "farewell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 23,
			when = {
				{ words = { "how" } },
				{ words = { "are" } },
				{ words = { "you" } },
			},
			actions = {
				{ say = "I'm just wonderful - thank you for asking." },
			},
		},
		{
			line = 24,
			when = {
				{ words = { "job" } },
			},
			actions = {
				{ say = "I sell runes, life and mana fluids - your best friends in any dungeon!" },
			},
		},
		{
			line = 25,
			when = {
				{ words = { "name" } },
			},
			actions = {
				{ say = "My name is Topsy." },
			},
		},
		{
			line = 26,
			when = {
				{ words = { "time" } },
			},
			actions = {
				{ say = "Time waits for no one! Not even you, sweetheart, so please do hurry up." },
			},
		},
		{
			line = 27,
			when = {
				{ words = { "help" } },
			},
			actions = {
				{ say = "I'd love to help, but I have a business to run - I am busy busy busy!." },
			},
		},
		{
			line = 28,
			when = {
				{ words = { "monster" } },
			},
			actions = {
				{ say = "Better buy and charge a lot of runes before facing any monster." },
			},
		},
		{
			line = 29,
			when = {
				{ words = { "dungeon" } },
			},
			actions = {
				{ say = "Dungeons - dank cold places if you ask me. They lead to rusty armour, severe colds and death ... on the other hand you use a lot of runes there ... so just think about the treasures you'll surely find there." },
			},
		},
		{
			line = 30,
			when = {
				{ words = { "sewer" } },
			},
			actions = {
				{ say = "The Thais sewerage system is a model of modern rat breeding and for some reason is very popular with young adventurers such as yourself." },
			},
		},
		{
			line = 31,
			when = {
				{ words = { "boss" } },
			},
			actions = {
				{ say = "I had one once. He should have bought better armour. Actually - he's upstairs." },
			},
		},
		{
			line = 32,
			when = {
				{ words = { "thank" } },
				{ words = { "you" } },
			},
			actions = {
				{ say = "Oh, such a sweetie ... and so polite. I thought politeness was out of fashion, these days." },
			},
		},
		{
			line = 33,
			when = {
				{ words = { "god" } },
			},
			actions = {
				{ say = "Gods - if we didn't have them, we would have invented them." },
			},
		},
		{
			line = 34,
			when = {
				{ words = { "king" } },
			},
			actions = {
				{ say = "<mutters> Here we go again  ... Hail to King Tibianus! ... Don't make me do that again!" },
			},
		},
		{
			line = 35,
			when = {
				{ words = { "sam" } },
			},
			actions = {
				{ say = "Ah, such a sweetie.  A simple man, with simple tastes and a simple mind." },
			},
		},
		{
			line = 36,
			when = {
				{ words = { "benjamin" } },
			},
			actions = {
				{ say = "Bless him, he stood, he fought, and then left his sanity on the battlefield." },
			},
		},
		{
			line = 37,
			when = {
				{ words = { "gorn" } },
			},
			actions = {
				{ say = "Ah yes ... Gorn ... the used-cart salesman of scrolls." },
			},
		},
		{
			line = 38,
			when = {
				{ words = { "quentin" } },
			},
			actions = {
				{ say = "I can't tell much about that old monk." },
			},
		},
		{
			line = 39,
			when = {
				{ words = { "bozo" } },
			},
			actions = {
				{ say = "He wanted to be the court jester but got upset when people laughed at him" },
			},
		},
		{
			line = 40,
			when = {
				{ words = { "rumour" } },
			},
			actions = {
				{ say = "I'm all ears" },
				{ set = { var = "topic", value = 4 } },
			},
		},
		{
			line = 41,
			when = {
				{ words = { "gossip" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 42,
			when = {
				{ words = { "news" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 43,
			when = {
				{ words = { "Gamon" } },
			},
			actions = {
				{ say = "I think he is a spy ... so I smile at him the whole day. He won't get anything out of me!" },
			},
		},
		{
			line = 44,
			when = {
				{ words = { "carlin" } },
			},
			actions = {
				{ say = "I went there on holiday once. Just goes to show that women are much better at running a place than men. King Tibianus could learn a thing or two from Queen Eloise." },
			},
		},
		{
			line = 45,
			when = {
				{ words = { "weapon" } },
			},
			actions = {
				{ say = "Wrong shop - go to my sister, silly!" },
			},
		},
		{
			line = 46,
			when = {
				{ words = { "magic" } },
			},
			actions = {
				{ say = "Magic will only protect you - a rune and some magic fluids." },
			},
		},
		{
			line = 47,
			when = {
				{ words = { "power" } },
			},
			actions = {
				{ say = "There is a power struggle between Venore and Thais." },
			},
		},
		{
			line = 48,
			when = {
				{ words = { "rebellion" } },
			},
			actions = {
				{ say = "There is talk of a rebellion in Venore to gain independence from the Oppressor - I mean - King of Thais - it can only help business." },
			},
		},
		{
			line = 49,
			when = {
				{ words = { "quest" } },
			},
			actions = {
				{ say = "I sell magic stuff, my dear. If you want a quest, you've come to the wrong shop." },
			},
		},
		{
			line = 50,
			when = {
				{ words = { "spells" } },
			},
			actions = {
				{ say = "You never know when you run out of mana. All the more reason to buy some good runes or fluids." },
			},
		},
		{
			line = 51,
			when = {
				{ words = { "muriel" } },
			},
			actions = {
				{ say = "You should ask this guy Oswald about him ... or other pointless rumors." },
			},
		},
		{
			line = 52,
			when = {
				{ words = { "elane" } },
			},
			actions = {
				{ say = "Some call her the preying mantis - apparently she has killed over a dozen husbands already." },
			},
		},
		{
			line = 53,
			when = {
				{ words = { "venore" } },
			},
			actions = {
				{ say = "A marvellous city! Modern! Prosperous! Thais could learn a thing or two from Venore" },
			},
		},
		{
			line = 54,
			when = {
				{ words = { "marvik" } },
			},
			actions = {
				{ say = "Who knows what the old man is up to in his hideout when no one is watching?" },
			},
		},
		{
			line = 55,
			when = {
				{ words = { "gregor" } },
			},
			actions = {
				{ say = "Ah Knight ... can't expect much from those guys." },
			},
		},
		{
			line = 56,
			when = {
				{ words = { "lugri" } },
			},
			actions = {
				{ say = "I only heared rumours about him, isn't he a hermit somewhere in the north?" },
			},
		},
		{
			line = 57,
			when = {
				{ words = { "excalibug" } },
			},
			actions = {
				{ say = "If you want to find out about excalibug you should ask the more sinister characters in Thais not a respectable woman like myself!" },
			},
		},
		{
			line = 58,
			when = {
				{ words = { "chester" } },
			},
			actions = {
				{ say = "I have never seen him at all. I only heared hes kind of the townsguards chief or such." },
			},
		},
		{
			line = 59,
			when = {
				{ words = { "ardua" } },
			},
			actions = {
				{ say = "What a strange woman. She lingers in our shop now and then ... I wonder what shes up to." },
			},
		},
		{
			line = 60,
			when = {
				{ words = { "partos" } },
			},
			actions = {
				{ say = "I heared he was a thief. Good thing he was caught." },
			},
		},
		{
			line = 61,
			when = {
				{ words = { "gamel" } },
			},
			actions = {
				{ say = "He hung around with that partos a lot. I wouldn't be suprised if he's a thief too. He is not allowed to enter our markethall." },
			},
		},
		{
			line = 62,
			when = {
				{ words = { "quest" } },
			},
			actions = {
				{ say = "Sure. Just ask my sister Turvy." },
			},
		},
		{
			line = 63,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 4 },
			},
			actions = {
				{ say = "Really? Tststs." },
			},
		},
		{
			line = 65,
			when = {
				{ words = { "offer" } },
			},
			actions = {
				{ say = "I'm selling life and mana fluids, runes, wands, rods and spellbooks." },
			},
		},
		{
			line = 66,
			when = {
				{ words = { "goods" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 67,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "sell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 68,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "have" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 70,
			when = {
				{ words = { "rune" } },
			},
			actions = {
				{ say = "I sell blank runes and spell runes." },
			},
		},
		{
			line = 71,
			when = {
				{ words = { "life" } },
				{ words = { "fluid" } },
			},
			actions = {
				{ set = { var = "type", value = 2006 } },
				{ set = { var = "data", value = 11 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 60 } },
				{ say = "Do you want to buy life fluid for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 72,
			when = {
				{ words = { "mana" } },
				{ words = { "fluid" } },
			},
			actions = {
				{ set = { var = "type", value = 2006 } },
				{ set = { var = "data", value = 10 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 55 } },
				{ say = "Do you want to buy mana fluid for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 73,
			when = {
				{ words = { "blank" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2260 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 10 } },
				{ say = "Do you want to buy a blank rune for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 74,
			when = {
				{ words = { "spellbook" } },
			},
			actions = {
				{ set = { var = "type", value = 2175 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 150 } },
				{ say = "Do you want to buy a spellbook for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 77,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "life" } },
				{ words = { "fluid" } },
			},
			actions = {
				{ set = { var = "type", value = 2006 } },
				{ set = { var = "data", value = 11 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 60, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A potions of life fluid for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 78,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "mana" } },
				{ words = { "fluid" } },
			},
			actions = {
				{ set = { var = "type", value = 2006 } },
				{ set = { var = "data", value = 10 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 55, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A potions of mana fluid for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 79,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "blank" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2260 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 10, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A blank runes for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 80,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "spellbook" } },
			},
			actions = {
				{ set = { var = "type", value = 2175 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 150, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A spellbooks for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 82,
			when = {
				{ words = { "deposit" } },
			},
			actions = {
				{ say = "I will pay you 5 gold for every empty vial. Ok?" },
				{ set = { var = "data", value = 0 } },
				{ set = { var = "topic", value = 3 } },
			},
		},
		{
			line = 83,
			when = {
				{ words = { "vial" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 84,
			when = {
				{ words = { "flask" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 86,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
				{ expr = { countMoney = true }, op = ">=", rhs = { session = "price" } },
			},
			actions = {
				{ say = "Here you are." },
				{ deleteMoney = true },
				{ create = { item = { session = "type" } } },
			},
		},
		{
			line = 87,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "Come back, when you have enough money." },
			},
		},
		{
			line = 88,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
			},
			actions = {
				{ say = "Hmm, but next time." },
			},
		},
		{
			line = 90,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
				{ words = { "yes" } },
				{ expr = { countMoney = true }, op = ">=", rhs = { session = "price" } },
			},
			actions = {
				{ say = "Here you are. There is a deposit of 5 gold on the vial." },
				{ deleteMoney = true },
				{ create = { item = { session = "type" } } },
			},
		},
		{
			line = 91,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "Come back, when you have enough money." },
			},
		},
		{
			line = 92,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
			},
			actions = {
				{ say = "Hmm, but next time." },
			},
		},
		{
			line = 94,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 3 },
				{ words = { "yes" } },
				{ expr = { count = 2006 }, op = ">", rhs = 0 },
			},
			actions = {
				{ set = { var = "amount", value = { count = 2006 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = { session = "amount" }, rhs = 5 } } } },
				{ say = "Here you are ... %P gold." },
				{ delete = { item = 2006 } },
				{ createMoney = true },
			},
		},
		{
			line = 95,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 3 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "You don't have any empty vials." },
			},
		},
		{
			line = 96,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 3 },
			},
			actions = {
				{ say = "Hmm, but please keep Tibia litter free." },
			},
		},
		{
			line = 5,
			when = {
				{ words = { "spell" } },
				{ words = { "rune" } },
			},
			actions = {
				{ say = "I sell missile runes, explosive runes, field runes, wall runes, bomb runes, healing runes, convince creature runes and chameleon runes." },
			},
		},
		{
			line = 6,
			when = {
				{ words = { "missile" } },
				{ words = { "rune" } },
			},
			actions = {
				{ say = "I can offer you light magic missile runes, heavy magic missile runes and sudden death runes." },
			},
		},
		{
			line = 7,
			when = {
				{ words = { "explosive" } },
				{ words = { "rune" } },
			},
			actions = {
				{ say = "I can offer you fireball runes, great fireball runes and explosion runes." },
			},
		},
		{
			line = 8,
			when = {
				{ words = { "field" } },
				{ words = { "rune" } },
			},
			actions = {
				{ say = "I can offer you fire field runes, energy field runes, poison field runes and destroy field runes." },
			},
		},
		{
			line = 9,
			when = {
				{ words = { "wall" } },
				{ words = { "rune" } },
			},
			actions = {
				{ say = "I can offer you fire wall runes, energy wall runes and poison wall runes." },
			},
		},
		{
			line = 10,
			when = {
				{ words = { "bomb" } },
				{ words = { "rune" } },
			},
			actions = {
				{ say = "I can offer you firebomb runes." },
			},
		},
		{
			line = 11,
			when = {
				{ words = { "healing" } },
				{ words = { "rune" } },
			},
			actions = {
				{ say = "I can offer you antidote runes, intense healing runes and ultimate healing runes." },
			},
		},
		{
			line = 13,
			when = {
				{ words = { "light" } },
				{ words = { "magic" } },
				{ words = { "missile" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2287 } },
				{ set = { var = "data", value = 5 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 40 } },
				{ say = "Do you want to buy a light magic missile rune for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 14,
			when = {
				{ words = { "poison" } },
				{ words = { "field" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2285 } },
				{ set = { var = "data", value = 3 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 65 } },
				{ say = "Do you want to buy a poison field rune for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 15,
			when = {
				{ words = { "antidote" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2266 } },
				{ set = { var = "data", value = 1 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 65 } },
				{ say = "Do you want to buy an antidote rune for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 16,
			when = {
				{ words = { "fire" } },
				{ words = { "field" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2301 } },
				{ set = { var = "data", value = 3 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 85 } },
				{ say = "Do you want to buy a fire field rune for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 17,
			when = {
				{ words = { "intense" } },
				{ words = { "healing" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2265 } },
				{ set = { var = "data", value = 1 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 95 } },
				{ say = "Do you want to buy an intense healing rune for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 18,
			when = {
				{ words = { "fireball" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2302 } },
				{ set = { var = "data", value = 2 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 95 } },
				{ say = "Do you want to buy a fireball rune for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 19,
			when = {
				{ words = { "destroy" } },
				{ words = { "field" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2261 } },
				{ set = { var = "data", value = 3 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 45 } },
				{ say = "Do you want to buy a destroy field rune for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 20,
			when = {
				{ words = { "heavy" } },
				{ words = { "magic" } },
				{ words = { "missile" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2311 } },
				{ set = { var = "data", value = 5 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 125 } },
				{ say = "Do you want to buy a heavy magic missile rune for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 21,
			when = {
				{ words = { "energy" } },
				{ words = { "field" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2277 } },
				{ set = { var = "data", value = 3 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 115 } },
				{ say = "Do you want to buy an energy field rune for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 22,
			when = {
				{ words = { "ultimate" } },
				{ words = { "healing" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2273 } },
				{ set = { var = "data", value = 1 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 175 } },
				{ say = "Do you want to buy an ultimate healing rune for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 23,
			when = {
				{ words = { "convince" } },
				{ words = { "creature" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2290 } },
				{ set = { var = "data", value = 1 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 80 } },
				{ say = "Do you want to buy a convince creature rune for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 24,
			when = {
				{ words = { "great" } },
				{ words = { "fireball" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2304 } },
				{ set = { var = "data", value = 2 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 180 } },
				{ say = "Do you want to buy a great fireball rune for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 25,
			when = {
				{ words = { "chameleon" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2291 } },
				{ set = { var = "data", value = 1 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 210 } },
				{ say = "Do you want to buy a chameleon rune for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 26,
			when = {
				{ words = { "fire" } },
				{ words = { "bomb" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2305 } },
				{ set = { var = "data", value = 2 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 235 } },
				{ say = "Do you want to buy a firebomb rune for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 27,
			when = {
				{ words = { "poison" } },
				{ words = { "wall" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2289 } },
				{ set = { var = "data", value = 4 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 210 } },
				{ say = "Do you want to buy a poison wall rune for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 28,
			when = {
				{ words = { "explosion" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2313 } },
				{ set = { var = "data", value = 3 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 250 } },
				{ say = "Do you want to buy an explosion rune for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 29,
			when = {
				{ words = { "fire" } },
				{ words = { "wall" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2303 } },
				{ set = { var = "data", value = 4 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 245 } },
				{ say = "Do you want to buy a fire wall rune for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 30,
			when = {
				{ words = { "sudden" } },
				{ words = { "death" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2268 } },
				{ set = { var = "data", value = 1 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 325 } },
				{ say = "Do you want to buy a sudden death rune for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 31,
			when = {
				{ words = { "energy" } },
				{ words = { "wall" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2279 } },
				{ set = { var = "data", value = 4 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 340 } },
				{ say = "Do you want to buy an energy wall rune for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 33,
			when = {
				{ words = { "envenom" } },
				{ words = { "rune" } },
			},
			actions = {
				{ say = "Sorry, but runes of this type can't be purchased here." },
			},
		},
		{
			line = 34,
			when = {
				{ words = { "desintegrate" } },
				{ words = { "rune" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 35,
			when = {
				{ words = { "poison" } },
				{ words = { "bomb" } },
				{ words = { "rune" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 36,
			when = {
				{ words = { "soulfire" } },
				{ words = { "rune" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 37,
			when = {
				{ words = { "energy" } },
				{ words = { "bomb" } },
				{ words = { "rune" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 38,
			when = {
				{ words = { "magic" } },
				{ words = { "wall" } },
				{ words = { "rune" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 39,
			when = {
				{ words = { "animate" } },
				{ words = { "dead" } },
				{ words = { "rune" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 40,
			when = {
				{ words = { "paralyze" } },
				{ words = { "rune" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 42,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "light" } },
				{ words = { "magic" } },
				{ words = { "missile" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2287 } },
				{ set = { var = "data", value = 5 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 40, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A light magic missile runes for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 43,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "poison" } },
				{ words = { "field" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2285 } },
				{ set = { var = "data", value = 3 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 65, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A poison field runes for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 44,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "antidote" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2266 } },
				{ set = { var = "data", value = 1 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 65, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A antidote runes for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 45,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "fire" } },
				{ words = { "field" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2301 } },
				{ set = { var = "data", value = 3 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 85, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A fire field runes for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 46,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "intense" } },
				{ words = { "healing" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2265 } },
				{ set = { var = "data", value = 1 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 95, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A intense healing runes for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 47,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "fireball" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2302 } },
				{ set = { var = "data", value = 2 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 95, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A fireball runes for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 48,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "destroy" } },
				{ words = { "field" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2261 } },
				{ set = { var = "data", value = 3 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 45, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A destroy field runes for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 49,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "heavy" } },
				{ words = { "magic" } },
				{ words = { "missile" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2311 } },
				{ set = { var = "data", value = 5 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 125, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A heavy magic missile runes for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 50,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "energy" } },
				{ words = { "field" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2277 } },
				{ set = { var = "data", value = 3 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 115, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A energy field runes for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 51,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "ultimate" } },
				{ words = { "healing" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2273 } },
				{ set = { var = "data", value = 1 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 175, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A ultimate healing runes for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 52,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "convince" } },
				{ words = { "creature" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2290 } },
				{ set = { var = "data", value = 1 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 80, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A convince creature runes for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 53,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "great" } },
				{ words = { "fireball" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2304 } },
				{ set = { var = "data", value = 2 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 180, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A great fireball runes for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 54,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "chameleon" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2291 } },
				{ set = { var = "data", value = 1 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 210, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A chameleon runes for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 55,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "fire" } },
				{ words = { "bomb" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2305 } },
				{ set = { var = "data", value = 2 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 235, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A firebomb runes for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 56,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "poison" } },
				{ words = { "wall" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2289 } },
				{ set = { var = "data", value = 4 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 210, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A poison wall runes for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 57,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "explosion" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2313 } },
				{ set = { var = "data", value = 3 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 250, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A explosion runes for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 58,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "fire" } },
				{ words = { "wall" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2303 } },
				{ set = { var = "data", value = 4 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 245, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A fire wall runes for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 59,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "sudden" } },
				{ words = { "death" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2268 } },
				{ set = { var = "data", value = 1 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 325, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A sudden death runes for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 60,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "energy" } },
				{ words = { "wall" } },
				{ words = { "rune" } },
			},
			actions = {
				{ set = { var = "type", value = 2279 } },
				{ set = { var = "data", value = 4 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 340, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A energy wall runes for %P gold?" },
				{ set = { var = "topic", value = 99 } },
			},
		},
		{
			line = 63,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 99 },
				{ words = { "yes" } },
				{ expr = { countMoney = true }, op = ">=", rhs = { session = "price" } },
			},
			actions = {
				{ say = "Here you are." },
				{ deleteMoney = true },
				{ create = { item = { session = "type" } } },
			},
		},
		{
			line = 64,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 99 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "Sorry, you don't have enough gold." },
			},
		},
		{
			line = 65,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 99 },
			},
			actions = {
				{ say = "As you wish." },
			},
		},
		{
			line = 5,
			when = {
				{ words = { "wand" } },
			},
			actions = {
				{ say = "Wands can be wielded by sorcerers only and have a certain level requirement. There are five different wands, would you like to hear about them?" },
				{ set = { var = "topic", value = 90 } },
			},
		},
		{
			line = 6,
			when = {
				{ words = { "rod" } },
			},
			actions = {
				{ say = "Rods can be wielded by druids only and have a certain level requirement. There are five different rods, would you like to hear about them?" },
				{ set = { var = "topic", value = 91 } },
			},
		},
		{
			line = 8,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 90 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "The names of the wands are 'Wand of Vortex', 'Wand of Dragonbreath', 'Wand of Plague', 'Wand of Cosmic Energy' and 'Wand of Inferno'. Which one would you like to buy?" },
			},
		},
		{
			line = 9,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 90 },
				{ words = { "no" } },
			},
			actions = {
				{ say = "Maybe another time." },
			},
		},
		{
			line = 10,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 90 },
			},
			actions = {
				{ say = "Maybe another time." },
			},
		},
		{
			line = 12,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 91 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "The names of the rods are 'Snakebite Rod', 'Moonlight Rod', 'Volcanic Rod', 'Quagmire Rod', and 'Tempest Rod'. Which one would you like to buy?" },
			},
		},
		{
			line = 13,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 91 },
				{ words = { "no" } },
			},
			actions = {
				{ say = "Maybe another time." },
			},
		},
		{
			line = 14,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 91 },
			},
			actions = {
				{ say = "Maybe another time." },
			},
		},
		{
			line = 16,
			when = {
				{ property = "sorcerer" },
				{ words = { "wand" } },
				{ words = { "of" } },
				{ words = { "vortex" } },
				{ expr = { questValue = 333 }, op = "<", rhs = 1 },
			},
			actions = {
				{ say = "Oh, is this your first wand of vortex? Take this little present from me as a free sample!" },
				{ setQuestValue = { id = 333, value = 1 } },
				{ set = { var = "type", value = 2190 } },
				{ set = { var = "amount", value = 1 } },
				{ create = { item = { session = "type" } } },
			},
		},
		{
			line = 17,
			when = {
				{ property = "druid" },
				{ words = { "snakebite" } },
				{ words = { "rod" } },
				{ expr = { questValue = 333 }, op = "<", rhs = 1 },
			},
			actions = {
				{ say = "Oh, is this your first snakebite rod? Take this little present from me as a free sample!" },
				{ setQuestValue = { id = 333, value = 1 } },
				{ set = { var = "type", value = 2182 } },
				{ set = { var = "amount", value = 1 } },
				{ create = { item = { session = "type" } } },
			},
		},
		{
			line = 19,
			when = {
				{ words = { "wand" } },
				{ words = { "of" } },
				{ words = { "vortex" } },
			},
			actions = {
				{ set = { var = "type", value = 2190 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 500 } },
				{ say = "This wand is only for sorcerers of level 7 and above. Would you like to buy a wand of vortex for %P gold?" },
				{ set = { var = "topic", value = 92 } },
			},
		},
		{
			line = 20,
			when = {
				{ words = { "wand" } },
				{ words = { "of" } },
				{ words = { "dragonbreath" } },
			},
			actions = {
				{ set = { var = "type", value = 2191 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 1000 } },
				{ say = "This wand is only for sorcerers of level 13 and above. Would you like to buy a wand of dragonbreath for %P gold?" },
				{ set = { var = "topic", value = 92 } },
			},
		},
		{
			line = 21,
			when = {
				{ words = { "wand" } },
				{ words = { "of" } },
				{ words = { "plague" } },
			},
			actions = {
				{ set = { var = "type", value = 2188 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 5000 } },
				{ say = "This wand is only for sorcerers of level 19 and above. Would you like to buy a wand of plague for %P gold?" },
				{ set = { var = "topic", value = 92 } },
			},
		},
		{
			line = 22,
			when = {
				{ words = { "wand" } },
				{ words = { "of" } },
				{ words = { "cosmic" } },
				{ words = { "energy" } },
			},
			actions = {
				{ set = { var = "type", value = 2189 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 10000 } },
				{ say = "This wand is only for sorcerers of level 26 and above. Would you like to buy a wand of cosmic energy for %P gold?" },
				{ set = { var = "topic", value = 92 } },
			},
		},
		{
			line = 23,
			when = {
				{ words = { "wand" } },
				{ words = { "of" } },
				{ words = { "inferno" } },
			},
			actions = {
				{ say = "Sorry, this wand contains magic far too powerful and we are afraid to store it here. I heard they have a few of these at the Edron academy though." },
			},
		},
		{
			line = 25,
			when = {
				{ words = { "snakebite" } },
				{ words = { "rod" } },
			},
			actions = {
				{ set = { var = "type", value = 2182 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 500 } },
				{ say = "This rod is only for druids of level 7 and above. Would you like to buy a snakebite rod for %P gold?" },
				{ set = { var = "topic", value = 92 } },
			},
		},
		{
			line = 26,
			when = {
				{ words = { "moonlight" } },
				{ words = { "rod" } },
			},
			actions = {
				{ set = { var = "type", value = 2186 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 1000 } },
				{ say = "This rod is only for druids of level 13 and above. Would you like to buy a moonlight rod for %P gold?" },
				{ set = { var = "topic", value = 92 } },
			},
		},
		{
			line = 27,
			when = {
				{ words = { "volcanic" } },
				{ words = { "rod" } },
			},
			actions = {
				{ set = { var = "type", value = 2185 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 5000 } },
				{ say = "This rod is only for druids of level 19 and above. Would you like to buy a volcanic rod for %P gold?" },
				{ set = { var = "topic", value = 92 } },
			},
		},
		{
			line = 28,
			when = {
				{ words = { "quagmire" } },
				{ words = { "rod" } },
			},
			actions = {
				{ set = { var = "type", value = 2181 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 10000 } },
				{ say = "This rod is only for druids of level 26 and above. Would you like to buy a quagmire rod for %P gold?" },
				{ set = { var = "topic", value = 92 } },
			},
		},
		{
			line = 29,
			when = {
				{ words = { "tempest" } },
				{ words = { "rod" } },
			},
			actions = {
				{ say = "Sorry, this rod contains magic far too powerful and we are afraid to store it here. I heard they have a few of these at the Edron academy though." },
			},
		},
		{
			line = 31,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "wand" } },
				{ words = { "of" } },
				{ words = { "vortex" } },
			},
			actions = {
				{ set = { var = "type", value = 2190 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 500, rhs = { capture = 1 } } } } },
				{ say = "This wand is only for sorcerers of level 7 and above. Would you like to buy %A wands of vortex for %P gold?" },
				{ set = { var = "topic", value = 92 } },
			},
		},
		{
			line = 32,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "wand" } },
				{ words = { "of" } },
				{ words = { "dragonbreath" } },
			},
			actions = {
				{ set = { var = "type", value = 2191 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 1000, rhs = { capture = 1 } } } } },
				{ say = "This wand is only for sorcerers of level 13 and above. Would you like to buy %A wands of dragonbreath for %P gold?" },
				{ set = { var = "topic", value = 92 } },
			},
		},
		{
			line = 33,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "wand" } },
				{ words = { "of" } },
				{ words = { "plague" } },
			},
			actions = {
				{ set = { var = "type", value = 2188 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 5000, rhs = { capture = 1 } } } } },
				{ say = "This wand is only for sorcerers of level 19 and above. Would you like to buy %A wands of plague for %P gold?" },
				{ set = { var = "topic", value = 92 } },
			},
		},
		{
			line = 34,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "wand" } },
				{ words = { "of" } },
				{ words = { "cosmic" } },
				{ words = { "energy" } },
			},
			actions = {
				{ set = { var = "type", value = 2189 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 10000, rhs = { capture = 1 } } } } },
				{ say = "This wand is only for sorcerers of level 26 and above. Would you like to buy %A wands of cosmic energy for %P gold?" },
				{ set = { var = "topic", value = 92 } },
			},
		},
		{
			line = 35,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "wand" } },
				{ words = { "of" } },
				{ words = { "inferno" } },
			},
			actions = {
				{ say = "Sorry, this wand contains far too powerful magic and we are afraid to store it here. I heard they have a few of these at the Edron academy though." },
			},
		},
		{
			line = 38,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "snakebite" } },
				{ words = { "rod" } },
			},
			actions = {
				{ set = { var = "type", value = 2182 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 500, rhs = { capture = 1 } } } } },
				{ say = "This rod is only for druids of level 7 and above. Would you like to buy %A snakebite rods for %P gold?" },
				{ set = { var = "topic", value = 92 } },
			},
		},
		{
			line = 39,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "moonlight" } },
				{ words = { "rod" } },
			},
			actions = {
				{ set = { var = "type", value = 2186 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 1000, rhs = { capture = 1 } } } } },
				{ say = "This rod is only for druids of level 13 and above. Would you like to buy %A moonlight rods for %P gold?" },
				{ set = { var = "topic", value = 92 } },
			},
		},
		{
			line = 40,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "volcanic" } },
				{ words = { "rod" } },
			},
			actions = {
				{ set = { var = "type", value = 2185 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 5000, rhs = { capture = 1 } } } } },
				{ say = "This rod is only for druids of level 19 and above. Would you like to buy %A volcanic rods for %P gold?" },
				{ set = { var = "topic", value = 92 } },
			},
		},
		{
			line = 41,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "quagmire" } },
				{ words = { "rod" } },
			},
			actions = {
				{ set = { var = "type", value = 2181 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 10000, rhs = { capture = 1 } } } } },
				{ say = "This rod is only for druids of level 26 and above. Would you like to buy %A quagmire rods for %P gold?" },
				{ set = { var = "topic", value = 92 } },
			},
		},
		{
			line = 42,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "tempest" } },
				{ words = { "rod" } },
			},
			actions = {
				{ say = "Sorry, this rod contains far too powerful magic and we are afraid to store it here. I heard they have a few of these at the Edron academy though." },
			},
		},
		{
			line = 45,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 92 },
				{ words = { "yes" } },
				{ expr = { countMoney = true }, op = ">=", rhs = { session = "price" } },
			},
			actions = {
				{ say = "Here you are." },
				{ deleteMoney = true },
				{ create = { item = { session = "type" } } },
			},
		},
		{
			line = 46,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 92 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "Sorry, you don't have enough gold." },
			},
		},
		{
			line = 47,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 92 },
			},
			actions = {
				{ say = "You don't know what you're missing." },
			},
		},
	},
}))

npc:register()
