-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: velvet.npc

local npc = NpcType("Velvet")
npc:appearance({ lookType = 136, lookHead = 59, lookBody = 96, lookLegs = 115, lookFeet = 95 })
npc:movement({ radius = 1, speed = 10 })
npc:health(100)
npc:sex(0)
npc:race(1)

local rules = {}
NpcAppendRules(rules, {
	{
		line = 13,
		when = {
			{ situation = "address" },
			{ words = { "hello$" } },
			{ select = true },
		},
		actions = {
			{ say = "Welcome to our shop, %N!" },
		},
	},
	{
		line = 14,
		when = {
			{ situation = "address" },
			{ words = { "hi$" } },
			{ select = true },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 15,
		when = {
			{ situation = "address" },
			{ select = true },
		},
		actions = {
			{ idle = true },
		},
	},
	{
		line = 16,
		when = {
			{ situation = "busy" },
			{ words = { "hello$" } },
			{ select = true },
		},
		actions = {
			{ say = "Just a moment please, %N." },
			{ queue = true },
		},
	},
	{
		line = 17,
		when = {
			{ situation = "busy" },
			{ words = { "hi$" } },
			{ select = true },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 18,
		when = {
			{ situation = "busy" },
			{ select = true },
		},
		actions = {
			{ nop = true },
		},
	},
	{
		line = 19,
		when = {
			{ situation = "vanish" },
			{ select = true },
		},
		actions = {
			{ say = "Good bye." },
		},
	},
	{
		line = 21,
		when = {
			{ words = { "bye" } },
		},
		actions = {
			{ say = "Good bye." },
			{ idle = true },
		},
	},
	{
		line = 22,
		when = {
			{ words = { "farewell" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 23,
		when = {
			{ words = { "name" } },
		},
		actions = {
			{ say = "I am Velvet. How can I help you?" },
		},
	},
	{
		line = 24,
		when = {
			{ words = { "job" } },
		},
		actions = {
			{ say = "I'm working here in this shop. Are you interested in any of our goods?" },
		},
	},
	{
		line = 25,
		when = {
			{ words = { "time" } },
			{ property = "male" },
		},
		actions = {
			{ say = "It's %T, sire." },
		},
	},
	{
		line = 26,
		when = {
			{ words = { "time" } },
			{ property = "female" },
		},
		actions = {
			{ say = "It's %T, my lady." },
		},
	},
	{
		line = 28,
		when = {
			{ words = { "offer" } },
		},
		actions = {
			{ say = "I sell pillows and tapestries." },
		},
	},
	{
		line = 29,
		when = {
			{ words = { "goods" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 30,
		when = {
			{ words = { "do" } },
			{ words = { "you" } },
			{ words = { "sell" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 31,
		when = {
			{ words = { "do" } },
			{ words = { "you" } },
			{ words = { "have" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 32,
		when = {
			{ words = { "furniture" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
	{
		line = 33,
		when = {
			{ words = { "equipment" } },
		},
		actions = {
			{ repeatPrevious = true },
		},
	},
})
NpcAppendRules(rules, NpcCatalogs["gen-t-furniture-pillows-s"])
NpcAppendRules(rules, NpcCatalogs["gen-t-furniture-tapestries-s"])
npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = rules,
}))

npc:register()
