-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: vladruc.npc

local npc = NpcType("Vladruc")
npc:appearance({ lookType = 68, lookHead = 0, lookBody = 0, lookLegs = 0, lookFeet = 0 })
npc:movement({ radius = 2, speed = 3 })
npc:health(100)
npc:sex(1)
npc:race(1)

npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = {
		{
			line = 13,
			when = {
				{ situation = "address" },
				{ words = { "hello$" } },
				{ expr = { count = 2199 }, op = ">", rhs = 0 },
				{ select = true },
			},
			actions = {
				{ say = "Chhhh ... Sorry, I'm busy. <cough>" },
				{ idle = true },
			},
		},
		{
			line = 14,
			when = {
				{ situation = "address" },
				{ words = { "hi$" } },
				{ expr = { count = 2199 }, op = ">", rhs = 0 },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 15,
			when = {
				{ situation = "address" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "I am Vladruc Urghain and welcome you, %N, to my house." },
			},
		},
		{
			line = 16,
			when = {
				{ situation = "address" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 17,
			when = {
				{ situation = "address" },
				{ select = true },
			},
			actions = {
				{ idle = true },
			},
		},
		{
			line = 18,
			when = {
				{ situation = "busy" },
				{ words = { "hello$" } },
				{ expr = { count = 2199 }, op = ">", rhs = 0 },
				{ select = true },
			},
			actions = {
				{ say = "Sorry, I'm busy." },
			},
		},
		{
			line = 19,
			when = {
				{ situation = "busy" },
				{ words = { "hi$" } },
				{ expr = { count = 2199 }, op = ">", rhs = 0 },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 20,
			when = {
				{ situation = "busy" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Please be seated and wait, %N." },
			},
		},
		{
			line = 21,
			when = {
				{ situation = "busy" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 22,
			when = {
				{ situation = "busy" },
				{ select = true },
			},
			actions = {
				{ nop = true },
			},
		},
		{
			line = 23,
			when = {
				{ situation = "vanish" },
				{ select = true },
			},
			actions = {
				{ say = "Go safely, and leave something of the happiness you bring!" },
			},
		},
		{
			line = 25,
			when = {
				{ words = { "bye" } },
			},
			actions = {
				{ say = "Go safely, and leave something of the happiness you bring!" },
				{ idle = true },
			},
		},
		{
			line = 26,
			when = {
				{ words = { "farewell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 27,
			when = {
				{ words = { "name" } },
			},
			actions = {
				{ say = "I am Vladruc Urghain. Welcome to my house!" },
			},
		},
		{
			line = 28,
			when = {
				{ words = { "job" } },
			},
			actions = {
				{ say = "I am a humble merchant of little importance to the beautiful Venore." },
			},
		},
		{
			line = 29,
			when = {
				{ words = { "thais" } },
			},
			actions = {
				{ say = "Sadly only through books I have come to know your great Thais, and to know her is to love her." },
			},
		},
		{
			line = 30,
			when = {
				{ words = { "books" } },
			},
			actions = {
				{ say = "These companions have been good friends and teachers to me." },
			},
		},
		{
			line = 31,
			when = {
				{ words = { "adventure" } },
			},
			actions = {
				{ say = "The time I sought out adventure is long gone indeed." },
			},
		},
		{
			line = 32,
			when = {
				{ words = { "Tibia" } },
			},
			actions = {
				{ say = "What a wonderful world we do live in ... so full of life." },
			},
		},
		{
			line = 33,
			when = {
				{ words = { "shop" } },
			},
			actions = {
				{ say = "Ah, feel free to browse and buy in my humble shop below." },
			},
		},
		{
			line = 34,
			when = {
				{ words = { "market" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 35,
			when = {
				{ words = { "time" } },
			},
			actions = {
				{ say = "It is %T." },
			},
		},
		{
			line = 36,
			when = {
				{ words = { "king" } },
			},
			actions = {
				{ say = "I am of noble blood myself. I have been so long master that none other should be master of me." },
			},
		},
		{
			line = 37,
			when = {
				{ words = { "tibianus" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 38,
			when = {
				{ words = { "venore" } },
			},
			actions = {
				{ say = "Our ways are not your ways, and there shall be to you many strange things." },
			},
		},
		{
			line = 39,
			when = {
				{ words = { "army" } },
			},
			actions = {
				{ say = "The Thaian garrsion serves its purpose very well." },
			},
		},
		{
			line = 40,
			when = {
				{ words = { "ferumbras" } },
			},
			actions = {
				{ say = "You think he is of ancient evil? Little you know about ancientness or evilness." },
			},
		},
		{
			line = 41,
			when = {
				{ words = { "excalibug" } },
			},
			actions = {
				{ say = "A terrifying weapon if it does exist at all." },
			},
		},
		{
			line = 42,
			when = {
				{ words = { "news" } },
			},
			actions = {
				{ say = "I am a reclusive person and learn little of the local gossip of the peasants." },
			},
		},
		{
			line = 43,
			when = {
				{ words = { "help" } },
			},
			actions = {
				{ say = "I am sorry, but I can't be of much assistance to you." },
			},
		},
		{
			line = 44,
			when = {
				{ words = { "monster" } },
			},
			actions = {
				{ say = "Oh yes, the children of the night ... you dwellers in the city cannot enter into the feelings of the hunter." },
			},
		},
		{
			line = 45,
			when = {
				{ words = { "dungeon" } },
			},
			actions = {
				{ say = "Such lovely places, unjustly shunned by the people." },
			},
		},
		{
			line = 46,
			when = {
				{ words = { "vampire" } },
			},
			actions = {
				{ say = "Please don't talk about such creatures. You are scaring me." },
			},
		},
		{
			line = 47,
			when = {
				{ words = { "thanks" } },
			},
			actions = {
				{ say = "That's nothing worth to be mentioned." },
			},
		},
		{
			line = 48,
			when = {
				{ words = { "thank" } },
				{ words = { "you" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 50,
			when = {
				{ words = { "offer" } },
			},
			actions = {
				{ say = "Please check my humble market downstairs for the wares that are offered." },
			},
		},
		{
			line = 51,
			when = {
				{ words = { "magic" } },
			},
			actions = {
				{ say = "Magic is a tool to be mastered." },
			},
		},
		{
			line = 52,
			when = {
				{ words = { "spells" } },
			},
			actions = {
				{ say = "I know a spell or two. You might want to buy some spells downstairs in the market." },
			},
		},
		{
			line = 53,
			when = {
				{ words = { "alchemy" } },
			},
			actions = {
				{ say = "You can buy some potions downstairs." },
			},
		},
		{
			line = 54,
			when = {
				{ words = { "blood" } },
			},
			actions = {
				{ say = "I like blood ... only the color, that is, of course ... <chuckles>" },
			},
		},
		{
			line = 55,
			when = {
				{ words = { "undead" } },
			},
			actions = {
				{ say = "It is not dead, which can eternal lie, and in strange aeons, even death may die." },
			},
		},
		{
			line = 56,
			when = {
				{ words = { "necroman" } },
			},
			actions = {
				{ say = "Death is the final frontier. Necromancers boldly go, where no one has gone before." },
			},
		},
		{
			line = 57,
			when = {
				{ words = { "coffin" } },
			},
			actions = {
				{ say = "The final restingplace for all of us, isn't it?" },
			},
		},
	},
}))

npc:register()
