-- Generated by import-npcs (NPC-2). Do not edit by hand.
-- Source: willard.npc

local npc = NpcType("Willard")
npc:appearance({ lookType = 131, lookHead = 58, lookBody = 104, lookLegs = 19, lookFeet = 116 })
npc:movement({ radius = 3, speed = 10, goStrength = 10 })
npc:health(100)
npc:sex(1)
npc:race(1)

npc:dialogue(NpcDialogue({
	policy = "queued_single_focus",
	rules = {
		{
			line = 13,
			when = {
				{ situation = "address" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "Greetings and Banor be with you, %N!" },
			},
		},
		{
			line = 14,
			when = {
				{ situation = "address" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 15,
			when = {
				{ situation = "address" },
				{ select = true },
			},
			actions = {
				{ idle = true },
			},
		},
		{
			line = 16,
			when = {
				{ situation = "busy" },
				{ words = { "hello$" } },
				{ select = true },
			},
			actions = {
				{ say = "I'm ready soon, %N. Please wait." },
				{ queue = true },
			},
		},
		{
			line = 17,
			when = {
				{ situation = "busy" },
				{ words = { "hi$" } },
				{ select = true },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 18,
			when = {
				{ situation = "busy" },
				{ select = true },
			},
			actions = {
				{ nop = true },
			},
		},
		{
			line = 19,
			when = {
				{ situation = "vanish" },
				{ select = true },
			},
			actions = {
				{ say = "Farewell." },
			},
		},
		{
			line = 21,
			when = {
				{ words = { "bye" } },
			},
			actions = {
				{ say = "Farewell." },
				{ idle = true },
			},
		},
		{
			line = 22,
			when = {
				{ words = { "name" } },
			},
			actions = {
				{ say = "I am Willard, the smith." },
			},
		},
		{
			line = 23,
			when = {
				{ words = { "job" } },
			},
			actions = {
				{ say = "I am the blacksmith of castle Bloodrock." },
			},
		},
		{
			line = 24,
			when = {
				{ words = { "time" } },
			},
			actions = {
				{ say = "Now it is %T." },
			},
		},
		{
			line = 25,
			when = {
				{ words = { "king" } },
			},
			actions = {
				{ say = "Hail to the King! He's our benevolent protector." },
			},
		},
		{
			line = 26,
			when = {
				{ words = { "tibianus" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 27,
			when = {
				{ words = { "army" } },
			},
			actions = {
				{ say = "I supply them with all they need." },
			},
		},
		{
			line = 28,
			when = {
				{ words = { "ferumbras" } },
			},
			actions = {
				{ say = "I would be honored if it's one of my blades that one day delivers him his punishment." },
			},
		},
		{
			line = 29,
			when = {
				{ words = { "excalibug" } },
			},
			actions = {
				{ say = "Adventurers search for this blade all over the world. Even here." },
			},
		},
		{
			line = 30,
			when = {
				{ words = { "thais" } },
			},
			actions = {
				{ say = "A fine city, but I love the peace of Edron more." },
			},
		},
		{
			line = 31,
			when = {
				{ words = { "tibia" } },
			},
			actions = {
				{ say = "It's my dream that one day the whole world will profit from the Thaian governance." },
			},
		},
		{
			line = 32,
			when = {
				{ words = { "carlin" } },
			},
			actions = {
				{ say = "If the king sees the time is right, he will certainly start a campaign to reclaim what belongs to Thais." },
			},
		},
		{
			line = 33,
			when = {
				{ words = { "edron" } },
			},
			actions = {
				{ say = "Edron is a fine city to live in." },
			},
		},
		{
			line = 34,
			when = {
				{ words = { "news" } },
			},
			actions = {
				{ say = "Rumors are too sinister things that a true warrior would care for them." },
			},
		},
		{
			line = 35,
			when = {
				{ words = { "rumors" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 37,
			when = {
				{ words = { "buy" } },
			},
			actions = {
				{ say = "What do you need? I sell weapons, armors, helmets, and shields." },
			},
		},
		{
			line = 38,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "sell" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 39,
			when = {
				{ words = { "do" } },
				{ words = { "you" } },
				{ words = { "have" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 40,
			when = {
				{ words = { "offer" } },
			},
			actions = {
				{ say = "My offers are weapons, ammunition, armors, helmets, legs, and shields." },
			},
		},
		{
			line = 41,
			when = {
				{ words = { "weapon" } },
			},
			actions = {
				{ say = "I have hand axes, axes, barbarian axes, spears, maces, clerical maces, battle hammers, swords, rapiers, daggers, sabres, bows, and crossbows. What's your choice?" },
			},
		},
		{
			line = 42,
			when = {
				{ words = { "ammunition" } },
			},
			actions = {
				{ say = "I have arrows for bows and bolts for crossbows. What do you want?" },
			},
		},
		{
			line = 43,
			when = {
				{ words = { "helmet" } },
			},
			actions = {
				{ say = "I am selling leather helmets and chain helmets. What do you want?" },
			},
		},
		{
			line = 44,
			when = {
				{ words = { "armor" } },
			},
			actions = {
				{ say = "I am selling leather, chain, and brass armor. What do you need?" },
			},
		},
		{
			line = 45,
			when = {
				{ words = { "shield" } },
			},
			actions = {
				{ say = "I am selling wooden shields, steel shields, and viking shields. What do you want?" },
			},
		},
		{
			line = 46,
			when = {
				{ words = { "trousers" } },
			},
			actions = {
				{ say = "I am selling chain legs. Do you want to buy any?" },
			},
		},
		{
			line = 47,
			when = {
				{ words = { "legs" } },
			},
			actions = {
				{ repeatPrevious = true },
			},
		},
		{
			line = 49,
			when = {
				{ words = { "dagger" } },
			},
			actions = {
				{ set = { var = "type", value = 2379 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 5 } },
				{ say = "Do you want to buy a dagger for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 50,
			when = {
				{ words = { "hand" } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 2380 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 8 } },
				{ say = "Do you want to buy a hand axe for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 51,
			when = {
				{ words = { "spear" } },
			},
			actions = {
				{ set = { var = "type", value = 2389 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 10 } },
				{ say = "Do you want to buy a spear for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 52,
			when = {
				{ words = { "rapier" } },
			},
			actions = {
				{ set = { var = "type", value = 2384 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 15 } },
				{ say = "Do you want to buy a rapier for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 53,
			when = {
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 2386 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 20 } },
				{ say = "Do you want to buy an axe for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 54,
			when = {
				{ words = { "barbar" } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 2429 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 590 } },
				{ say = "Do you want to buy a barbarian axe for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 55,
			when = {
				{ words = { "sabre" } },
			},
			actions = {
				{ set = { var = "type", value = 2385 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 35 } },
				{ say = "Do you want to buy a sabre for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 56,
			when = {
				{ words = { "sword" } },
			},
			actions = {
				{ set = { var = "type", value = 2376 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 85 } },
				{ say = "Do you want to buy a sword for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 57,
			when = {
				{ words = { "mace" } },
			},
			actions = {
				{ set = { var = "type", value = 2398 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 90 } },
				{ say = "Do you want to buy a mace for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 58,
			when = {
				{ words = { "cleric" } },
				{ words = { "mace" } },
			},
			actions = {
				{ set = { var = "type", value = 2423 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 540 } },
				{ say = "Do you want to buy a clerical mace for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 59,
			when = {
				{ words = { "battle" } },
				{ words = { "hammer" } },
			},
			actions = {
				{ set = { var = "type", value = 2417 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 350 } },
				{ say = "Do you want to buy a battle hammer for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 60,
			when = {
				{ words = { "bow" } },
			},
			actions = {
				{ set = { var = "type", value = 2456 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 400 } },
				{ say = "Do you want to buy a bow for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 61,
			when = {
				{ words = { "crossbow" } },
			},
			actions = {
				{ set = { var = "type", value = 2455 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 500 } },
				{ say = "Do you want to buy a crossbow for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 62,
			when = {
				{ words = { "arrow" } },
			},
			actions = {
				{ set = { var = "type", value = 2544 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 2 } },
				{ say = "Do you want to buy an arrow for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 63,
			when = {
				{ words = { "bolt" } },
			},
			actions = {
				{ set = { var = "type", value = 2543 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 3 } },
				{ say = "Do you want to buy a bolt for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 64,
			when = {
				{ words = { "throwing" } },
				{ words = { "star" } },
			},
			actions = {
				{ set = { var = "type", value = 2399 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 50 } },
				{ say = "Do you want to buy a throwing star for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 67,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "dagger" } },
			},
			actions = {
				{ set = { var = "type", value = 2379 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 5, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A daggers for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 68,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "hand" } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 2380 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 8, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A hand axes for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 69,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "spear" } },
			},
			actions = {
				{ set = { var = "type", value = 2389 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 10, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A spears for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 70,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "rapier" } },
			},
			actions = {
				{ set = { var = "type", value = 2384 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 15, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A rapiers for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 71,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 2386 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 20, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A axes for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 72,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "barbar" } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 2429 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 590, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A barbarian axes for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 73,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "sabre" } },
			},
			actions = {
				{ set = { var = "type", value = 2385 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 35, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A sabres for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 74,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "sword" } },
			},
			actions = {
				{ set = { var = "type", value = 2376 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 85, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A swords for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 75,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "mace" } },
			},
			actions = {
				{ set = { var = "type", value = 2398 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 90, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A maces for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 76,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "cleric" } },
				{ words = { "mace" } },
			},
			actions = {
				{ set = { var = "type", value = 2423 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 540, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A clerical maces for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 77,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "battle" } },
				{ words = { "hammer" } },
			},
			actions = {
				{ set = { var = "type", value = 2417 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 350, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A battle hammers for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 78,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "bow" } },
			},
			actions = {
				{ set = { var = "type", value = 2456 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 400, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A bows for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 79,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "crossbow" } },
			},
			actions = {
				{ set = { var = "type", value = 2455 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 500, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A crossbows for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 80,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "arrow" } },
			},
			actions = {
				{ set = { var = "type", value = 2544 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 2, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A arrows for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 81,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "bolt" } },
			},
			actions = {
				{ set = { var = "type", value = 2543 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 3, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A bolts for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 82,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "throwing" } },
				{ words = { "star" } },
			},
			actions = {
				{ set = { var = "type", value = 2399 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 50, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A throwing stars for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 84,
			when = {
				{ words = { "chain" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 2464 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 200 } },
				{ say = "Do you want to buy a chain armor for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 85,
			when = {
				{ words = { "brass" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 2465 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 450 } },
				{ say = "Do you want to buy a brass armor for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 86,
			when = {
				{ words = { "leather" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 2467 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 35 } },
				{ say = "Do you want to buy a leather armor for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 87,
			when = {
				{ words = { "chain" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 2458 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 52 } },
				{ say = "Do you want to buy a chain helmet for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 88,
			when = {
				{ words = { "leather" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 2461 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 12 } },
				{ say = "Do you want to buy a leather helmet for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 89,
			when = {
				{ words = { "steel" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 2509 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 240 } },
				{ say = "Do you want to buy a steel shield for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 90,
			when = {
				{ words = { "wooden" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 2512 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 15 } },
				{ say = "Do you want to buy a wooden shield for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 91,
			when = {
				{ words = { "viking" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 2531 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 260 } },
				{ say = "Do you want to buy a viking shield for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 92,
			when = {
				{ words = { "chain" } },
				{ words = { "legs" } },
			},
			actions = {
				{ set = { var = "type", value = 2648 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 80 } },
				{ say = "Do you want to buy chain legs for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 94,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "chain" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 2464 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 200, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A chain armors for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 95,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "brass" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 2465 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 450, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A brass armors for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 96,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "leather" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 2467 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 35, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A leather armors for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 97,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "chain" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 2458 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 52, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A chain helmets for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 98,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "leather" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 2461 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 12, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A leather helmets for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 99,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "steel" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 2509 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 240, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A steel shields for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 100,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "wooden" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 2512 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 15, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A wooden shields for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 101,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "viking" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 2531 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 260, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A viking shields for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 102,
			when = {
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "chain" } },
				{ words = { "legs" } },
			},
			actions = {
				{ set = { var = "type", value = 2648 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 80, rhs = { capture = 1 } } } } },
				{ say = "Do you want to buy %A chain legs for %P gold?" },
				{ set = { var = "topic", value = 1 } },
			},
		},
		{
			line = 104,
			when = {
				{ words = { "sell" } },
				{ words = { "two" } },
				{ words = { "handed" } },
				{ words = { "sword" } },
			},
			actions = {
				{ set = { var = "type", value = 2377 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 450 } },
				{ say = "Do you want to sell a two handed sword for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 105,
			when = {
				{ words = { "sell" } },
				{ words = { "battle" } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 2378 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 80 } },
				{ say = "Do you want to sell a battle axe for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 106,
			when = {
				{ words = { "sell" } },
				{ words = { "dagger" } },
			},
			actions = {
				{ set = { var = "type", value = 2379 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 2 } },
				{ say = "Do you want to sell this garbage? I give you %P gold, ok?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 107,
			when = {
				{ words = { "sell" } },
				{ words = { "hand" } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 2380 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 4 } },
				{ say = "Do you want to sell a hand axe for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 108,
			when = {
				{ words = { "sell" } },
				{ words = { "halberd" } },
			},
			actions = {
				{ set = { var = "type", value = 2381 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 400 } },
				{ say = "Do you want to sell a halberd for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 109,
			when = {
				{ words = { "sell" } },
				{ words = { "club" } },
			},
			actions = {
				{ set = { var = "type", value = 2382 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 1 } },
				{ say = "Are you sure, you want to sell this garbage? Hmm, I give you %P gold, ok?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 110,
			when = {
				{ words = { "sell" } },
				{ words = { "spike" } },
				{ words = { "sword" } },
			},
			actions = {
				{ set = { var = "type", value = 2383 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 240 } },
				{ say = "Do you want to sell a spike sword for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 111,
			when = {
				{ words = { "sell" } },
				{ words = { "rapier" } },
			},
			actions = {
				{ set = { var = "type", value = 2384 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 5 } },
				{ say = "Do you want to sell a rapier for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 112,
			when = {
				{ words = { "sell" } },
				{ words = { "sabre" } },
			},
			actions = {
				{ set = { var = "type", value = 2385 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 12 } },
				{ say = "Do you want to sell a sabre for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 113,
			when = {
				{ words = { "sell" } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 2386 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 7 } },
				{ say = "Do you want to sell an axe for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 114,
			when = {
				{ words = { "sell" } },
				{ words = { "spear" } },
			},
			actions = {
				{ set = { var = "type", value = 2389 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 3 } },
				{ say = "Do you want to sell this garbage? I give you %P gold, ok?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 115,
			when = {
				{ words = { "sell" } },
				{ words = { "morning" } },
				{ words = { "star" } },
			},
			actions = {
				{ set = { var = "type", value = 2394 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 90 } },
				{ say = "Do you want to sell a morning star for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 116,
			when = {
				{ words = { "sell" } },
				{ words = { "mace" } },
			},
			actions = {
				{ set = { var = "type", value = 2398 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 30 } },
				{ say = "Do you want to sell a mace for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 117,
			when = {
				{ words = { "sell" } },
				{ words = { "short" } },
				{ words = { "sword" } },
			},
			actions = {
				{ set = { var = "type", value = 2406 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 10 } },
				{ say = "Do you want to sell a short sword for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 118,
			when = {
				{ words = { "sell" } },
				{ words = { "battle" } },
				{ words = { "hammer" } },
			},
			actions = {
				{ set = { var = "type", value = 2417 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 120 } },
				{ say = "Do you want to sell a battle hammer for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 119,
			when = {
				{ words = { "sell" } },
				{ words = { "cleric" } },
				{ words = { "mace" } },
			},
			actions = {
				{ set = { var = "type", value = 2423 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 170 } },
				{ say = "Do you want to sell a clerical mace for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 120,
			when = {
				{ words = { "sell" } },
				{ words = { "barbar" } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 2429 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 185 } },
				{ say = "Do you want to sell a barbarian axe for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 121,
			when = {
				{ words = { "sell" } },
				{ words = { "sword" } },
			},
			actions = {
				{ set = { var = "type", value = 2376 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 25 } },
				{ say = "Do you want to sell a sword for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 123,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "two" } },
				{ words = { "handed" } },
				{ words = { "sword" } },
			},
			actions = {
				{ set = { var = "type", value = 2377 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 450, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A two handed swords for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 124,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "battle" } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 2378 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 80, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A battle axes for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 125,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "dagger" } },
			},
			actions = {
				{ set = { var = "type", value = 2379 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 2, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell this garbage? I give you %P gold, ok?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 126,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "hand" } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 2380 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 4, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A hand axes for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 127,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "halberd" } },
			},
			actions = {
				{ set = { var = "type", value = 2381 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 400, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A halberds for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 128,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "club" } },
			},
			actions = {
				{ set = { var = "type", value = 2382 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 1, rhs = { capture = 1 } } } } },
				{ say = "Are you sure, you want to sell this garbage? Hmm, I give you %P gold, ok?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 129,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "spike" } },
				{ words = { "sword" } },
			},
			actions = {
				{ set = { var = "type", value = 2383 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 240, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A spike swords for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 130,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "rapier" } },
			},
			actions = {
				{ set = { var = "type", value = 2384 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 5, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A rapiers for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 131,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "sabre" } },
			},
			actions = {
				{ set = { var = "type", value = 2385 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 12, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A sabres for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 132,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 2386 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 7, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A axes for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 133,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "spear" } },
			},
			actions = {
				{ set = { var = "type", value = 2389 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 3, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell this garbage? I give you %P gold, ok?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 134,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "morning" } },
				{ words = { "star" } },
			},
			actions = {
				{ set = { var = "type", value = 2394 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 90, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A morning stars for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 135,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "mace" } },
			},
			actions = {
				{ set = { var = "type", value = 2398 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 30, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A maces for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 136,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "short" } },
				{ words = { "sword" } },
			},
			actions = {
				{ set = { var = "type", value = 2406 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 10, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A short swords for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 137,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "battle" } },
				{ words = { "hammer" } },
			},
			actions = {
				{ set = { var = "type", value = 2417 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 120, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A battle hammers for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 138,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "cleric" } },
				{ words = { "mace" } },
			},
			actions = {
				{ set = { var = "type", value = 2423 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 170, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A clerical maces for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 139,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "barbar" } },
				{ words = { "axe" } },
			},
			actions = {
				{ set = { var = "type", value = 2429 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 185, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A barbarian axes for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 140,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "sword" } },
			},
			actions = {
				{ set = { var = "type", value = 2376 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 25, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A swords for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 142,
			when = {
				{ words = { "sell" } },
				{ words = { "leather" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 2467 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 12 } },
				{ say = "Do you want to sell a leather armor for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 143,
			when = {
				{ words = { "sell" } },
				{ words = { "chain" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 2464 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 70 } },
				{ say = "Do you want to sell a chain armor for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 144,
			when = {
				{ words = { "sell" } },
				{ words = { "brass" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 2465 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 150 } },
				{ say = "Do you want to sell a brass armor for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 145,
			when = {
				{ words = { "sell" } },
				{ words = { "plate" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 2463 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 400 } },
				{ say = "Do you want to sell a plate armor for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 146,
			when = {
				{ words = { "sell" } },
				{ words = { "chain" } },
				{ words = { "legs" } },
			},
			actions = {
				{ set = { var = "type", value = 2648 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 25 } },
				{ say = "Do you want to sell chain legs for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 147,
			when = {
				{ words = { "sell" } },
				{ words = { "leather" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 2461 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 4 } },
				{ say = "Do you want to sell a leather helmet for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 148,
			when = {
				{ words = { "sell" } },
				{ words = { "iron" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 2459 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 150 } },
				{ say = "Do you want to sell an iron helmet for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 149,
			when = {
				{ words = { "sell" } },
				{ words = { "chain" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 2458 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 17 } },
				{ say = "Do you want to sell a chain helmet for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 150,
			when = {
				{ words = { "sell" } },
				{ words = { "steel" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 2457 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 190 } },
				{ say = "Do you want to sell a steel helmet for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 151,
			when = {
				{ words = { "sell" } },
				{ words = { "wooden" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 2512 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 5 } },
				{ say = "Do you want to sell a wooden shield for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 152,
			when = {
				{ words = { "sell" } },
				{ words = { "battle" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 2513 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 95 } },
				{ say = "Do you want to sell a battle shield for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 153,
			when = {
				{ words = { "sell" } },
				{ words = { "steel" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 2509 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 80 } },
				{ say = "Do you want to sell a steel shield for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 154,
			when = {
				{ words = { "sell" } },
				{ words = { "viking" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 2531 } },
				{ set = { var = "amount", value = 1 } },
				{ set = { var = "price", value = 85 } },
				{ say = "Do you want to sell a viking shield for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 156,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "leather" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 2467 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 12, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A leather armors for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 157,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "chain" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 2464 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 70, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A chain armors for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 158,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "brass" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 2465 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 150, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A brass armors for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 159,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "plate" } },
				{ words = { "armor" } },
			},
			actions = {
				{ set = { var = "type", value = 2463 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 400, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A plate armors for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 160,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "chain" } },
				{ words = { "legs" } },
			},
			actions = {
				{ set = { var = "type", value = 2648 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 25, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A chain legs for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 161,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "leather" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 2461 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 4, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A leather helmets for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 162,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "iron" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 2459 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 150, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A iron helmets for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 163,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "chain" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 2458 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 17, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A chain helmets for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 164,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "steel" } },
				{ words = { "helmet" } },
			},
			actions = {
				{ set = { var = "type", value = 2457 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 190, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A steel helmets for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 165,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "wooden" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 2512 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 5, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A wooden shields for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 166,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "battle" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 2513 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 95, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A battle shields for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 167,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "steel" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 2509 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 80, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A steel shields for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 168,
			when = {
				{ words = { "sell" } },
				{ capture = 1 },
				{ expr = 1, op = "<", rhs = { capture = 1 } },
				{ words = { "viking" } },
				{ words = { "shield" } },
			},
			actions = {
				{ set = { var = "type", value = 2531 } },
				{ set = { var = "amount", value = { capture = 1 } } },
				{ set = { var = "price", value = { binary = { op = "*", lhs = 85, rhs = { capture = 1 } } } } },
				{ say = "Do you want to sell %A viking shields for %P gold?" },
				{ set = { var = "topic", value = 2 } },
			},
		},
		{
			line = 170,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
				{ expr = { countMoney = true }, op = ">=", rhs = { session = "price" } },
			},
			actions = {
				{ say = "Thank you. Here it is." },
				{ deleteMoney = true },
				{ create = { item = { session = "type" }, count = 1 } },
			},
		},
		{
			line = 171,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "Sorry, you do not have enough gold." },
			},
		},
		{
			line = 172,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 1 },
			},
			actions = {
				{ say = "Maybe you will buy it another time." },
			},
		},
		{
			line = 174,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
				{ words = { "yes" } },
				{ expr = { count = { session = "type" } }, op = ">=", rhs = { session = "amount" } },
			},
			actions = {
				{ say = "Ok. Here is your money." },
				{ delete = { item = { session = "type" }, count = 1 } },
				{ createMoney = true },
			},
		},
		{
			line = 175,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
				{ words = { "yes" } },
			},
			actions = {
				{ say = "Sorry, you do not have one." },
			},
		},
		{
			line = 176,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
				{ words = { "yes" } },
				{ expr = { session = "amount" }, op = ">", rhs = 1 },
			},
			actions = {
				{ say = "Sorry, you do not have so much." },
			},
		},
		{
			line = 177,
			when = {
				{ expr = { session = "topic" }, op = "=", rhs = 2 },
			},
			actions = {
				{ say = "Maybe next time." },
			},
		},
	},
}))

npc:register()
