[package]
name = "tfs-rust-lua"
version = "0.1.0"
edition = "2024"

[dependencies]
tfs-rust-common = { workspace = true }
tfs-rust-content = { workspace = true }
mlua = { workspace = true }
thiserror = { workspace = true }
tracing = "0.1"
quick-xml = { workspace = true }
serde = { version = "1.0", features = ["derive"] }

[[bin]]
name = "import-npcs"
path = "src/bin/import_npcs.rs"
